<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>18&nbsp; Quasi-Experiments – Detailed Course Notes for ECON 4750</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./16-unconfoundedness.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="4750_style.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./17-quasi_experiments.html"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Quasi-Experiments</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Detailed Course Notes for ECON 4750</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Start</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Statistical Programming</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-introduction_to_R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-programming_in_R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Programming in R</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Probability</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-random_variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Random Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-expectations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Expectation, Variance, and More</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Properties of Estimators</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-finite_sample_properties.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Finite Sample Properties</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-asymptotic_properties.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Asymptotic Properties</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Regression</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-interpreting_regressions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Interpreting Regressions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-regression_computation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Computation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-regression_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Advanced Topics</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-binary_outcomes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Binary Outcome Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Prediction</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-model_selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Model Selection</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-machine_learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Machine Learning</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Causal Inference</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-causal_inference_concepts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Concepts</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-experiments.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Experiments</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-unconfoundedness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Unconfoundedness</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-quasi_experiments.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Quasi-Experiments</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#panel-data-approaches" id="toc-panel-data-approaches" class="nav-link active" data-scroll-target="#panel-data-approaches"><span class="header-section-number">18.1</span> Panel Data Approaches</a>
  <ul class="collapse">
  <li><a href="#difference-in-differences" id="toc-difference-in-differences" class="nav-link" data-scroll-target="#difference-in-differences"><span class="header-section-number">18.1.1</span> Difference in differences</a></li>
  <li><a href="#computation" id="toc-computation" class="nav-link" data-scroll-target="#computation"><span class="header-section-number">18.1.2</span> Computation</a></li>
  </ul></li>
  <li><a href="#instrumental-variables" id="toc-instrumental-variables" class="nav-link" data-scroll-target="#instrumental-variables"><span class="header-section-number">18.2</span> Instrumental Variables</a>
  <ul class="collapse">
  <li><a href="#example-return-to-education" id="toc-example-return-to-education" class="nav-link" data-scroll-target="#example-return-to-education"><span class="header-section-number">18.2.1</span> Example: Return to Education</a></li>
  </ul></li>
  <li><a href="#regression-discontinuity" id="toc-regression-discontinuity" class="nav-link" data-scroll-target="#regression-discontinuity"><span class="header-section-number">18.3</span> Regression Discontinuity</a>
  <ul class="collapse">
  <li><a href="#example-causal-effect-of-alcohol-on-driving-deaths" id="toc-example-causal-effect-of-alcohol-on-driving-deaths" class="nav-link" data-scroll-target="#example-causal-effect-of-alcohol-on-driving-deaths"><span class="header-section-number">18.3.1</span> Example: Causal effect of Alcohol on Driving Deaths</a></li>
  </ul></li>
  <li><a href="#lab-7-drunk-driving-laws" id="toc-lab-7-drunk-driving-laws" class="nav-link" data-scroll-target="#lab-7-drunk-driving-laws"><span class="header-section-number">18.4</span> Lab 7: Drunk Driving Laws</a></li>
  <li><a href="#lab-7-solutions" id="toc-lab-7-solutions" class="nav-link" data-scroll-target="#lab-7-solutions"><span class="header-section-number">18.5</span> Lab 7: Solutions</a></li>
  <li><a href="#coding-questions" id="toc-coding-questions" class="nav-link" data-scroll-target="#coding-questions"><span class="header-section-number">18.6</span> Coding Questions</a></li>
  <li><a href="#extra-questions" id="toc-extra-questions" class="nav-link" data-scroll-target="#extra-questions"><span class="header-section-number">18.7</span> Extra Questions</a></li>
  <li><a href="#answers-to-some-extra-questions" id="toc-answers-to-some-extra-questions" class="nav-link" data-scroll-target="#answers-to-some-extra-questions"><span class="header-section-number">18.8</span> Answers to Some Extra Questions</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Quasi-Experiments</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><span class="math display">\[
\newcommand{\E}{\mathbb{E}}
\renewcommand{\P}{\textrm{P}}
\let\L\relax
\newcommand{\L}{\textrm{L}} %doesn't work in .qmd, place this command at start of qmd file to use it
\newcommand{\F}{\textrm{F}}
\newcommand{\var}{\textrm{var}}
\newcommand{\cov}{\textrm{cov}}
\newcommand{\corr}{\textrm{corr}}
\newcommand{\Var}{\mathrm{Var}}
\newcommand{\Cov}{\mathrm{Cov}}
\newcommand{\Corr}{\mathrm{Corr}}
\newcommand{\sd}{\mathrm{sd}}
\newcommand{\se}{\mathrm{s.e.}}
\newcommand{\T}{T}
\newcommand{\indicator}[1]{\mathbb{1}\{#1\}}
\newcommand\independent{\perp \!\!\! \perp}
\newcommand{\N}{\mathcal{N}}
\]</span></p>
<section id="panel-data-approaches" class="level2" data-number="18.1">
<h2 data-number="18.1" class="anchored" data-anchor-id="panel-data-approaches"><span class="header-section-number">18.1</span> Panel Data Approaches</h2>
<p>SW All of Ch. 10 and 13.4</p>
<p>In the previous section, we invoked the assumption of unconfoundedness and were in the setup where <span class="math inline">\(X\)</span> was fully observed. But suppose instead that you thought this alternative version of unconfoundedness held <span class="math display">\[\begin{align*}
  (Y(1),Y(0)) \independent D | (X,W)
\end{align*}\]</span> where <span class="math inline">\(X\)</span> were observed random variables, but <span class="math inline">\(W\)</span> were not observed. Following exactly the same argument as in the previous section, this would lead to a regression like <span class="math display">\[\begin{align*}
  Y_i = \alpha D_i + \beta_0 + \beta_1 X_i + \beta_2 W_i + U_i
\end{align*}\]</span> (I’m just including one <span class="math inline">\(X\)</span> and one <span class="math inline">\(W\)</span> for simplicity, but you can easily imagine the case where there are more.) If <span class="math inline">\(W\)</span> were observed, then we could just run this regression, but since <span class="math inline">\(W\)</span> is not observed, we run into the problem of omitted variable bias (i.e., if we just ignore <span class="math inline">\(W\)</span>, we won’t be estimating the causal effect <span class="math inline">\(\alpha\)</span>)</p>
<p>In this section, we’ll consider the case where a researcher has access to a different type of data called <strong>panel data</strong>. Panel data is data that follows the same individual (or firm, etc.) over time. In this case, it is often helpful to index variables by time. For example, <span class="math inline">\(Y_{it}\)</span> is the outcome for individual <span class="math inline">\(i\)</span> in time period <span class="math inline">\(t\)</span>. <span class="math inline">\(X_{it}\)</span> is the value of a regressor for individual <span class="math inline">\(i\)</span> in time period <span class="math inline">\(t\)</span> and <span class="math inline">\(D_{it}\)</span> is the value of the treatment for individual <span class="math inline">\(i\)</span> in time period <span class="math inline">\(t\)</span>. If some variable doesn’t vary over time (e.g., a regressor like race), we won’t use a <span class="math inline">\(t\)</span> subscript.</p>
<p>Panel data potentially gives us a way around the problem of not observing some variables that we would like to condition on in the model. This is particularly likely to be the case when <span class="math inline">\(W\)</span> does not vary over time. Let’s start with there are exactly two time periods of panel data. In that case, we can write <span class="math display">\[\begin{align*}
  Y_{it} = \alpha D_{it} + \beta_0 + \beta_1 X_{it} + \beta_2 W_i + U_{it}
\end{align*}\]</span> where we consider the case where <span class="math inline">\(D\)</span> and <span class="math inline">\(X\)</span> both change over time. Then, defining <span class="math inline">\(\Delta Y_{it} = Y_{it} - Y_{it-1}\)</span> (and using similar notation for other variables), notice that <span class="math display">\[\begin{align*}
  \Delta Y_{it} = \alpha \Delta D_{it} + \beta_1 \Delta X_{it} + \Delta U_{it}
\end{align*}\]</span> which, importantly, no longer involves the unobserved <span class="math inline">\(W_i\)</span> and suggests running the above regression and interpreting the estimated version of <span class="math inline">\(\alpha\)</span> as an estimate of the causal effect of participating in the treatment.</p>
<ul>
<li><p><strong>Time fixed effects</strong> — The previous regression did not include an intercept. It is common in applied work to allow for the intercept to vary over time (i.e., so that <span class="math inline">\(\beta_0 = \beta_{0,t}\)</span>) which allows for “aggregate shocks” such as recessions or common trends in outcomes over time. In practice, this amounts to just including an intercept in the previous regression, for example,</p>
<p><span class="math display">\[
    \Delta Y_{it} = \underbrace{\theta_t} + \alpha \Delta D_{it} + \beta_1 \Delta X_{it} + \Delta U_{it}
  \]</span></p></li>
</ul>
<p>Often, there may be many omitted, time invariant variables. In practice, these are usually just lumped into a single <strong>individual fixed effect</strong> — even if there are many time invariant, unobserved variables, we can difference them all out at the same time <span class="math display">\[\begin{align*}
  Y_{it} &amp;= \alpha D_{it} + \beta_{0,t} + \beta_1 X_{it} + \underbrace{\beta_2 W_{1i} + \beta_3 W_{2i} + \beta_4 W_{3i}} + U_{it} \\
  &amp;= \alpha D_{it} + \beta_{0,t} + \underbrace{\eta_i} + U_{it}
\end{align*}\]</span> and we can follow the same strategies as above.</p>
<p>Another case that is common in practice is when there are more than two time periods. This case is similar to the previous one except there are multiple ways to eliminate the unobserved fixed effect. The two most common are the</p>
<ul>
<li><p><strong>Within estimator</strong></p>
<p>To motivate this approach, notice that, if, for each individual, we average their outcomes over time, the we get <span class="math display">\[\begin{align*}
    \bar{Y}_i = \alpha \bar{D}_i + \beta_1 \bar{X}_i + (\textrm{time fixed effects}) + \bar{U}_i
  \end{align*}\]</span> (where I have just written “time fixed effects” to indicate that these are transformed version of original fixed but still show up here.) Subtracting this equation from the expression for <span class="math inline">\(Y_{it}\)</span> gives <span class="math display">\[\begin{align*}
    Y_{it} - \bar{Y}_i = \alpha (D_{it} - \bar{D}_i) + \beta_1 (X_{it} - \bar{X}_i) + (\textrm{time fixed effects}) + U_{it} - \bar{U}_i
  \end{align*}\]</span></p>
<p>This is a feasible regression to estimate (everything is observed here). This is called a within estimator because the terms <span class="math inline">\(\bar{Y}_i\)</span>, <span class="math inline">\(\bar{D}_i\)</span>, and <span class="math inline">\(\bar{X}_i\)</span> are the within-individual averages-over-time of the corresponding variable.</p></li>
<li><p><strong>First differences</strong></p>
<p>Another approach to eliminating the unobserved fixed effects is to directly consider <span class="math inline">\(\Delta Y_{it}\)</span>:</p>
<p><span class="math display">\[\begin{align*}
    \Delta Y_{it} = \alpha \Delta D_{it} + \beta_1 \Delta X_{it} + \Delta U_{it}
  \end{align*}\]</span></p>
<p>This is the same expression as we had before for the two period case. Only here you would include observations from all available time periods on <span class="math inline">\(\Delta Y_{it}, \Delta D_{it}, \Delta X_{it}\)</span> in the regression.</p></li>
</ul>
<p>It’s worth mentioning the cases where a fixed effects strategy can break down:</p>
<ul>
<li><p>Unobserved variables vary over time</p>
<p><span class="math display">\[
    Y_{it} = \alpha D_{it} + \beta_0 + \beta_1 X_{it} + \beta_2 \underbrace{W_{it}} + U_{it}
  \]</span> In this case,</p>
<p><span class="math display">\[
    \Delta Y_{it} = \alpha \Delta D_{it} + \beta_1 \Delta X_{it} + \beta_2 \underbrace{\Delta W_{it}} + \Delta U_{it}
  \]</span></p>
<p>which still involves the unobserved <span class="math inline">\(W_{it}\)</span>, and implies that the fixed effects regression will contain omitted variable bias.</p></li>
<li><p>The effect of unobserved variables varies over time</p>
<p><span class="math display">\[
    Y_{it} = \alpha D_{it} + \beta_0 + \beta_1 X_{it} + \underbrace{\beta_{2,t}} W_i + U_{it}
  \]</span> In this case,</p>
<p><span class="math display">\[
    \Delta Y_{it} = \alpha \Delta D_{it} + \beta_1 \Delta X_{it} + \underbrace{(\beta_{2,t} - \beta_{2,t-1})} W_i + \Delta U_{it}
  \]</span></p>
<p>which still involves the unobserved <span class="math inline">\(W_i\)</span> (even though it doesn’t vary over time) and, therefore, the fixed effects regressions we have been considering will contain omitted variable bias.</p></li>
</ul>
<p>Also, the assumption of treatment effect homogeneity can potentially matter a lot in this context. This will particularly be the case when (i) individuals can become treated at different points in time, and (ii) there are treatment effect dynamics (so that the effect of participating in the treatment can vary over time) — both of these are realistic in many applications. This is a main research area of mine and one I am happy to talk way more about.</p>
<section id="difference-in-differences" class="level3" data-number="18.1.1">
<h3 data-number="18.1.1" class="anchored" data-anchor-id="difference-in-differences"><span class="header-section-number">18.1.1</span> Difference in differences</h3>
<p>The panel data approaches that we have been talking about so far are closely related to a <strong>natural-experiment</strong> type of strategy called <strong>difference in differences</strong> (DID).</p>
<p>One important difference relative to the previous approach is that DID is typically implemented when some units (these are often states or particular locations) implement a policy at some time period while others do not; and, in particular, we observe some periods before any units participate in the treatment.</p>
<p>Let’s think about the case with exactly two time periods: <span class="math inline">\(t\)</span> and <span class="math inline">\(t-1\)</span>. In this case, we’ll suppose that the outcomes that we observe are <span class="math display">\[\begin{align*}
  Y_{it} &amp;= D_i Y_{it}(1) + (1-D_i) Y_{it}(0) \\
  Y_{it-1} &amp;= Y_{it-1}(0)
\end{align*}\]</span> In other words, in the second period, we observe treated potential outcomes for treated units and untreated potential outcomes for untreated units (this is just like the cross-sectional case above). But in the first period, we observe untreated potential outcomes for all units — because no one is treated yet.</p>
<p>DID is often motivated by an assumption called the parallel trends assumption:</p>
<p><strong>Parallel Trends Assumption</strong> <span class="math display">\[\begin{align*}
\E[\Delta Y_t(0) | D=1] = \E[\Delta Y_t(0) | D=0]
\end{align*}\]</span> This says that the <em>path</em> of outcomes that individuals in the treated group would have experienced if they had not been treated is the same as the path of outcomes that individual in the untreated group actually experienced.</p>
<p>As before, we continue to be interested in <span class="math display">\[\begin{align*}
  ATT = \E[Y_t(1) - Y_t(0) | D=1]
\end{align*}\]</span> Recall that the key identification challenge if for <span class="math inline">\(\E[Y_t(0)|D=1]\)</span> here, and notice that <span class="math display">\[\begin{align*}
  \E[Y_t(0) | D=1] &amp;= \E[\Delta Y_t(0) | D=1] + \E[Y_{t-1}(0) | D=1] \\
  &amp;= \E[\Delta Y_t(0) | D=0] + \E[Y_{t-1}(0)|D=1] \\
  &amp;= \E[\Delta Y_t | D=0] + \E[Y_{t-1}|D=1]
\end{align*}\]</span> where the first equality adds and subtracts <span class="math inline">\(\E[Y_{t-1}(0)|D=1]\)</span>, the second equality uses the parallel trends assumption, and the last equality holds because all the potential outcomes in the previous line are actually observed outcome. Plugging this expression into the one for <span class="math inline">\(ATT\)</span> yields: <span class="math display">\[\begin{align*}
  ATT = \E[\Delta Y_t | D=1] - \E[\Delta Y_t | D=0]
\end{align*}\]</span> In other words, under parallel trends, the <span class="math inline">\(ATT\)</span> can be recovered by comparing the path of outcomes that treated units experienced relative to the path of outcomes that untreated units experienced (the latter of which is the path of outcomes that treated units would have experienced if they had not participated in the treatment).</p>
<p>As above, it is often convenient to estimate <span class="math inline">\(ATT\)</span> using a regression. In fact, you can show that (in the case with two periods), <span class="math inline">\(\alpha\)</span> in the following regression is equal to the <span class="math inline">\(ATT\)</span>: <span class="math display">\[\begin{align*}
  Y_{it} = \alpha D_{it} + \theta_t + \eta_i + v_{it}
\end{align*}\]</span> where <span class="math inline">\(\E[v_t | D] = 0\)</span>.</p>
</section>
<section id="computation" class="level3" data-number="18.1.2">
<h3 data-number="18.1.2" class="anchored" data-anchor-id="computation"><span class="header-section-number">18.1.2</span> Computation</h3>
<p>The lab in this chapter uses panel data to think about causal effects, so I won’t provide an extended discussion here but rather just mention the syntax for a few panel data estimators. Let’s suppose that you had a data frame that, for the first few rows, looked like (this is totally made up data)</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  id year         Y       X1 X2
1  1 2019  87.92934 495.4021  1
2  1 2020 102.77429 495.6269  1
3  1 2021 110.84441 495.4844  0
4  2 2019  76.54302 492.8797  1
5  2 2020 104.29125 496.1825  1
6  2 2021 105.06056 492.0129  1</code></pre>
</div>
</div>
<p>This is what panel data typically looks like — here, we are following a single individual (who is distinguished by their <code>id</code> variable) over three years (from 2019-2021), there is an outcome <code>Y</code> and potential regressors <code>X1</code> and <code>X2</code>.</p>
<p>There are several packages in <code>R</code> for estimating the fixed effects models that we have been considering. I mainly use <code>plm</code> (for “panel linear models”), so I’ll show you that one and then mention one more.</p>
<p>For <code>plm</code>, if you want to estimate a fixed effects model in first differences, you would use the <code>plm</code> command with the following sort of syntax</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plm)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plm</span>(Y <span class="sc">~</span> X1 <span class="sc">+</span> X2 <span class="sc">+</span> <span class="fu">as.factor</span>(year), </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">data=</span>name_of_data,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">effect=</span><span class="st">"individual"</span>,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">model=</span><span class="st">"fd"</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">index=</span><span class="st">"id"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We include here <code>as.factor(year)</code> to include time fixed effects, <code>effect="individual"</code> means to include an individual fixed effect, <code>model="fd"</code> says to estimate the model in first differences, and <code>index="id"</code> means that the individual identifier is in the column “id”.</p>
<p>The code for estimating the model using a within transformation is very similar:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plm</span>(Y <span class="sc">~</span> X1 <span class="sc">+</span> X2 <span class="sc">+</span> <span class="fu">as.factor</span>(year), </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">data=</span>name_of_data,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">effect=</span><span class="st">"individual"</span>,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">model=</span><span class="st">"within"</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">index=</span><span class="st">"id"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The only difference is that <code>model="fd"</code> has been replaced with <code>model="within"</code>.</p>
<p>Let me also just mention that the <code>estimatr</code> package can estimate a fixed effects model using a within transformation. The code for this case would look like</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(estimatr)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lm_robust</span>(Y <span class="sc">~</span> X1 <span class="sc">+</span> X2 <span class="sc">+</span> <span class="fu">as.factor</span>(year), </span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">data=</span>name_of_data,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">fixed_effects=</span><span class="sc">~</span>id)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I think the advantage of using this approach is that it seems straightforward to get the heteroskedasticity robust standard errors (or cluster-robust standard errors) that are popular in economics (as we have done before for heteroskedasticity robust standard errors for a regression with just cross sectional data). But I am not sure how (or if it is possible) to use <code>estimatr</code> to estimate the fixed effects model in first differences.</p>
</section>
</section>
<section id="instrumental-variables" class="level2" data-number="18.2">
<h2 data-number="18.2" class="anchored" data-anchor-id="instrumental-variables"><span class="header-section-number">18.2</span> Instrumental Variables</h2>
<p>SW all of chapter 12</p>
<p>In the previous section, I used the word <strong>natural experiment</strong> but didn’t really define it. When an actual experiment is not actually available, a very common strategy used by researchers interested in causal effects is to consider natural experiments — these are not actual experiments, but more like the case where “something weird” happens that makes some individuals more likely to participate in the treatment without otherwise affecting their outcomes. This “something weird” is called an <strong>instrumental variable</strong>.</p>
<p>Let me give you some examples:</p>
<ul>
<li><p>This is not as popular of a topic as it used to be, but many economists used to be interested in the causal effect of military service on earnings. This is challenging because individuals “self-select” into the military (i.e., individuals don’t just randomly choose to join the military, and, while there may be many dimensions of choosing to join the military, probably one dimension is what a person expects the effect to be on their future earnings).</p>
<ul>
<li>A famous example of an instrumental variable in this case is an individual’s Vietname draft lottery number. Here, the idea is that a randomly generated lottery number (by construction) doesn’t have any direct effect on earnings, but it does affect the chances that someone participates in the military. This is therefore a natural experiment and could serve the role of an instrumental variable.</li>
</ul></li>
<li><p>For studying the effect of education on on earnings, researchers have used the day of birth as an instrument for years of education. The idea is that compulsory school laws are set up so that individuals can leave school when they reach a certain age (e.g., 16). But this means that, among students that want to drop out as early as they can, students who have an “early” birthday (usually around October) will have spent less time in school than students who have a “late” birthday (usually around July) at any particular age. This is a kind of natural experiment — comparing earnings of students who drop out at 16 for those who have early birthdays relative to late birthdays.</p></li>
</ul>
<p>Let’s formalize these arguments. Using the same arguments as before, suppose we have a regression that we’d like to run</p>
<p><span class="math display">\[
  Y_i = \beta_0 + \alpha D_i + \underbrace{\beta_1 W_i + U_i}_{V_i}
\]</span> and interpret our estimate of <span class="math inline">\(\alpha\)</span> as an estimate of the causal effect of participating in the treatment. And where, for simplicity, I am not including any <span class="math inline">\(X\)</span> covariates and where we do not observe <span class="math inline">\(W\)</span>. If <span class="math inline">\(D\)</span> is correlated with <span class="math inline">\(W\)</span>, then just ignoring <span class="math inline">\(W\)</span> and running a regression of <span class="math inline">\(Y\)</span> on <span class="math inline">\(D\)</span> will result in omitted variable bias so that regression does not recover an estimate of <span class="math inline">\(\alpha\)</span>. To help with the discussion below, we’ll define <span class="math inline">\(V_i\)</span> to be the entire unobservable term, <span class="math inline">\(\beta_1 W_i + U_i\)</span>, in the above equation.</p>
<p>An instrumental variable, which we’ll call <span class="math inline">\(Z\)</span>, needs to satisfy the following two conditions:</p>
<ol type="1">
<li><p><span class="math inline">\(\Cov(Z,V) = 0\)</span> — This condition is called the <strong>exclusion restriction</strong>, and it means that the instrument is uncorrelated with the error term in the above equation. In practice, we’d mainly need to make sure that it is uncorrelated with whatever we think is in <span class="math inline">\(W\)</span>.</p></li>
<li><p><span class="math inline">\(\Cov(Z,D) \neq 0\)</span> — This condition is called <strong>instrument relevance</strong>, and it means that the instrument needs to actually affect whether or not an individual participates in the treatment. We’ll see why this condition is important momentarily.</p></li>
</ol>
<p>Next, notice that</p>
<p><span class="math display">\[
  \begin{aligned}
  \Cov(Z,Y) &amp;= \Cov(Z,\beta_0 + \alpha D + V) \\
  &amp;= \alpha \Cov(Z,D)
  \end{aligned}
\]</span> which holds because <span class="math inline">\(\Cov(Z,\beta_0) = 0\)</span> (because <span class="math inline">\(\beta_0\)</span> is a constant) and <span class="math inline">\(\Cov(Z,V)=0\)</span> by the first condition of <span class="math inline">\(Z\)</span> being a valid instrument. This implies that</p>
<p><span class="math display">\[
  \alpha = \frac{\Cov(Z,Y)}{\Cov(Z,D)}
\]</span> That is, if we have a valid instrument, the above formula gives us a path to recovering the causal effect of <span class="math inline">\(D\)</span> on <span class="math inline">\(Y\)</span>. [Now you can also see why we needed the second condition — otherwise, we could divide by 0 here.]</p>
<p>The intuition for this is the following: changes in the instrument can cause changes in the outcome but only because they can change whether or not an individual participates in the treatment. These changes show up in the numerator. They are scaled by how much changes in the instrument result in changes in the treatment.</p>
<p>If there are other covariates in the model, the formula for <span class="math inline">\(\alpha\)</span> will become more complicated. But you can use the <code>ivreg</code> function in the <code>ivreg</code> package to make these complications for you.</p>
<section id="example-return-to-education" class="level3" data-number="18.2.1">
<h3 data-number="18.2.1" class="anchored" data-anchor-id="example-return-to-education"><span class="header-section-number">18.2.1</span> Example: Return to Education</h3>
<p>In this example, we’ll estimate the return to education using whether or not an individual lives close to a college as an instrument for attending college. The idea is that (at least after controlling for some other covariates), the distance that a person lives from a college should not directly affect their earnings but it could affect whether or not they attend college due to it being more or less convenient. I think that the papers that use this sort of an idea primarily have in mind that distance-to-college may affect whether or not a student attends a community college rather than a university.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ivreg)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(modelsummary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`modelsummary` 2.0.0 now uses `tinytable` as its default table-drawing
  backend. Learn more at: https://vincentarelbundock.github.io/tinytable/

Revert to `kableExtra` for one session:

  options(modelsummary_factory_default = 'kableExtra')
  options(modelsummary_factory_latex = 'kableExtra')
  options(modelsummary_factory_html = 'kableExtra')

Silence this message forever:

  config_modelsummary(startup_message = FALSE)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"SchoolingReturns"</span>, <span class="at">package=</span><span class="st">"ivreg"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>lm_reg <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(wage) <span class="sc">~</span> education <span class="sc">+</span> <span class="fu">poly</span>(experience, <span class="dv">2</span>, <span class="at">raw =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> ethnicity <span class="sc">+</span> smsa <span class="sc">+</span> south,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> SchoolingReturns)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>iv_reg <span class="ot">&lt;-</span> <span class="fu">ivreg</span>(<span class="fu">log</span>(wage) <span class="sc">~</span> education <span class="sc">+</span> <span class="fu">poly</span>(experience, <span class="dv">2</span>, <span class="at">raw =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> ethnicity <span class="sc">+</span> smsa <span class="sc">+</span> south, </span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> nearcollege <span class="sc">+</span> <span class="fu">poly</span>(age, <span class="dv">2</span>, <span class="at">raw =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> ethnicity <span class="sc">+</span> smsa <span class="sc">+</span> south,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> SchoolingReturns)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>reg_list <span class="ot">&lt;-</span> <span class="fu">list</span>(lm_reg, iv_reg)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="fu">modelsummary</span>(reg_list)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
 

  
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>tinytable_w9lcqhmu1nodavrwwvek</title>
    <style>
.table td.tinytable_css_9xo114m8qeljxanb4ueu, .table th.tinytable_css_9xo114m8qeljxanb4ueu {    border-bottom: solid 0.1em #d3d8dc; }
.table td.tinytable_css_ca7fbmvezcdiw3ndu9cc, .table th.tinytable_css_ca7fbmvezcdiw3ndu9cc {    text-align: left; }
.table td.tinytable_css_qezqddhlcjua2u9hp23u, .table th.tinytable_css_qezqddhlcjua2u9hp23u {    text-align: center; }
.table td.tinytable_css_kxerintmqtb2uyj3cfua, .table th.tinytable_css_kxerintmqtb2uyj3cfua {    text-align: center; }
.table td.tinytable_css_kzesth61iepfnkosp6v5, .table th.tinytable_css_kzesth61iepfnkosp6v5 {    border-bottom: solid 0.05em black; }
    </style>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script id="MathJax-script" async="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    <script>
    MathJax = {
      tex: {
        inlineMath: [['$', '$'], ['\\(', '\\)']]
      },
      svg: {
        fontCache: 'global'
      }
    };
    </script>
  

  
    <div class="container">
      <table class="table table-borderless" id="tinytable_w9lcqhmu1nodavrwwvek" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        <thead>
        
              <tr>
                <th scope="col"> </th>
                <th scope="col">(1)</th>
                <th scope="col">(2)</th>
              </tr>
        </thead>
        
        <tbody>
                <tr>
                  <td>(Intercept)                     </td>
                  <td>4.734    </td>
                  <td>4.066  </td>
                </tr>
                <tr>
                  <td>                                </td>
                  <td>(0.068)  </td>
                  <td>(0.608)</td>
                </tr>
                <tr>
                  <td>education                       </td>
                  <td>0.074    </td>
                  <td>0.133  </td>
                </tr>
                <tr>
                  <td>                                </td>
                  <td>(0.004)  </td>
                  <td>(0.051)</td>
                </tr>
                <tr>
                  <td>poly(experience, 2, raw = TRUE)1</td>
                  <td>0.084    </td>
                  <td>0.056  </td>
                </tr>
                <tr>
                  <td>                                </td>
                  <td>(0.007)  </td>
                  <td>(0.026)</td>
                </tr>
                <tr>
                  <td>poly(experience, 2, raw = TRUE)2</td>
                  <td>-0.002   </td>
                  <td>-0.001 </td>
                </tr>
                <tr>
                  <td>                                </td>
                  <td>(0.000)  </td>
                  <td>(0.001)</td>
                </tr>
                <tr>
                  <td>ethnicityafam                   </td>
                  <td>-0.190   </td>
                  <td>-0.103 </td>
                </tr>
                <tr>
                  <td>                                </td>
                  <td>(0.018)  </td>
                  <td>(0.077)</td>
                </tr>
                <tr>
                  <td>smsayes                         </td>
                  <td>0.161    </td>
                  <td>0.108  </td>
                </tr>
                <tr>
                  <td>                                </td>
                  <td>(0.016)  </td>
                  <td>(0.050)</td>
                </tr>
                <tr>
                  <td>southyes                        </td>
                  <td>-0.125   </td>
                  <td>-0.098 </td>
                </tr>
                <tr>
                  <td>                                </td>
                  <td>(0.015)  </td>
                  <td>(0.029)</td>
                </tr>
                <tr>
                  <td>Num.Obs.                        </td>
                  <td>3010     </td>
                  <td>3010   </td>
                </tr>
                <tr>
                  <td>R2                              </td>
                  <td>0.291    </td>
                  <td>0.176  </td>
                </tr>
                <tr>
                  <td>R2 Adj.                         </td>
                  <td>0.289    </td>
                  <td>0.175  </td>
                </tr>
                <tr>
                  <td>AIC                             </td>
                  <td>40329.6  </td>
                  <td>40778.6</td>
                </tr>
                <tr>
                  <td>BIC                             </td>
                  <td>40377.7  </td>
                  <td>40826.7</td>
                </tr>
                <tr>
                  <td>Log.Lik.                        </td>
                  <td>-1308.702</td>
                  <td>       </td>
                </tr>
                <tr>
                  <td>F                               </td>
                  <td>204.932  </td>
                  <td>       </td>
                </tr>
                <tr>
                  <td>RMSE                            </td>
                  <td>0.37     </td>
                  <td>0.40   </td>
                </tr>
        </tbody>
      </table>
    </div>

    <script>
      function styleCell_tinytable_tihmu5673egnyhaw77lb(i, j, css_id) {
        var table = document.getElementById("tinytable_w9lcqhmu1nodavrwwvek");
        table.rows[i].cells[j].classList.add(css_id);
      }
      function insertSpanRow(i, colspan, content) {
        var table = document.getElementById('tinytable_w9lcqhmu1nodavrwwvek');
        var newRow = table.insertRow(i);
        var newCell = newRow.insertCell(0);
        newCell.setAttribute("colspan", colspan);
        // newCell.innerText = content;
        // this may be unsafe, but innerText does not interpret <br>
        newCell.innerHTML = content;
      }
      function spanCell_tinytable_tihmu5673egnyhaw77lb(i, j, rowspan, colspan) {
        var table = document.getElementById("tinytable_w9lcqhmu1nodavrwwvek");
        const targetRow = table.rows[i];
        const targetCell = targetRow.cells[j];
        for (let r = 0; r < rowspan; r++) {
          // Only start deleting cells to the right for the first row (r == 0)
          if (r === 0) {
            // Delete cells to the right of the target cell in the first row
            for (let c = colspan - 1; c > 0; c--) {
              if (table.rows[i + r].cells[j + c]) {
                table.rows[i + r].deleteCell(j + c);
              }
            }
          }
          // For rows below the first, delete starting from the target column
          if (r > 0) {
            for (let c = colspan - 1; c >= 0; c--) {
              if (table.rows[i + r] && table.rows[i + r].cells[j]) {
                table.rows[i + r].deleteCell(j);
              }
            }
          }
        }
        // Set rowspan and colspan of the target cell
        targetCell.rowSpan = rowspan;
        targetCell.colSpan = colspan;
      }

window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(0, 0, 'tinytable_css_9xo114m8qeljxanb4ueu') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(0, 1, 'tinytable_css_9xo114m8qeljxanb4ueu') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(0, 2, 'tinytable_css_9xo114m8qeljxanb4ueu') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(0, 0, 'tinytable_css_ca7fbmvezcdiw3ndu9cc') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(1, 0, 'tinytable_css_ca7fbmvezcdiw3ndu9cc') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(2, 0, 'tinytable_css_ca7fbmvezcdiw3ndu9cc') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(3, 0, 'tinytable_css_ca7fbmvezcdiw3ndu9cc') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(4, 0, 'tinytable_css_ca7fbmvezcdiw3ndu9cc') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(5, 0, 'tinytable_css_ca7fbmvezcdiw3ndu9cc') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(6, 0, 'tinytable_css_ca7fbmvezcdiw3ndu9cc') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(7, 0, 'tinytable_css_ca7fbmvezcdiw3ndu9cc') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(8, 0, 'tinytable_css_ca7fbmvezcdiw3ndu9cc') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(9, 0, 'tinytable_css_ca7fbmvezcdiw3ndu9cc') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(10, 0, 'tinytable_css_ca7fbmvezcdiw3ndu9cc') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(11, 0, 'tinytable_css_ca7fbmvezcdiw3ndu9cc') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(12, 0, 'tinytable_css_ca7fbmvezcdiw3ndu9cc') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(13, 0, 'tinytable_css_ca7fbmvezcdiw3ndu9cc') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(14, 0, 'tinytable_css_ca7fbmvezcdiw3ndu9cc') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(15, 0, 'tinytable_css_ca7fbmvezcdiw3ndu9cc') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(16, 0, 'tinytable_css_ca7fbmvezcdiw3ndu9cc') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(17, 0, 'tinytable_css_ca7fbmvezcdiw3ndu9cc') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(18, 0, 'tinytable_css_ca7fbmvezcdiw3ndu9cc') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(19, 0, 'tinytable_css_ca7fbmvezcdiw3ndu9cc') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(20, 0, 'tinytable_css_ca7fbmvezcdiw3ndu9cc') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(21, 0, 'tinytable_css_ca7fbmvezcdiw3ndu9cc') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(22, 0, 'tinytable_css_ca7fbmvezcdiw3ndu9cc') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(0, 1, 'tinytable_css_qezqddhlcjua2u9hp23u') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(1, 1, 'tinytable_css_qezqddhlcjua2u9hp23u') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(2, 1, 'tinytable_css_qezqddhlcjua2u9hp23u') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(3, 1, 'tinytable_css_qezqddhlcjua2u9hp23u') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(4, 1, 'tinytable_css_qezqddhlcjua2u9hp23u') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(5, 1, 'tinytable_css_qezqddhlcjua2u9hp23u') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(6, 1, 'tinytable_css_qezqddhlcjua2u9hp23u') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(7, 1, 'tinytable_css_qezqddhlcjua2u9hp23u') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(8, 1, 'tinytable_css_qezqddhlcjua2u9hp23u') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(9, 1, 'tinytable_css_qezqddhlcjua2u9hp23u') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(10, 1, 'tinytable_css_qezqddhlcjua2u9hp23u') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(11, 1, 'tinytable_css_qezqddhlcjua2u9hp23u') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(12, 1, 'tinytable_css_qezqddhlcjua2u9hp23u') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(13, 1, 'tinytable_css_qezqddhlcjua2u9hp23u') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(14, 1, 'tinytable_css_qezqddhlcjua2u9hp23u') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(15, 1, 'tinytable_css_qezqddhlcjua2u9hp23u') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(16, 1, 'tinytable_css_qezqddhlcjua2u9hp23u') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(17, 1, 'tinytable_css_qezqddhlcjua2u9hp23u') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(18, 1, 'tinytable_css_qezqddhlcjua2u9hp23u') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(19, 1, 'tinytable_css_qezqddhlcjua2u9hp23u') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(20, 1, 'tinytable_css_qezqddhlcjua2u9hp23u') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(21, 1, 'tinytable_css_qezqddhlcjua2u9hp23u') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(22, 1, 'tinytable_css_qezqddhlcjua2u9hp23u') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(0, 2, 'tinytable_css_kxerintmqtb2uyj3cfua') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(1, 2, 'tinytable_css_kxerintmqtb2uyj3cfua') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(2, 2, 'tinytable_css_kxerintmqtb2uyj3cfua') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(3, 2, 'tinytable_css_kxerintmqtb2uyj3cfua') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(4, 2, 'tinytable_css_kxerintmqtb2uyj3cfua') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(5, 2, 'tinytable_css_kxerintmqtb2uyj3cfua') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(6, 2, 'tinytable_css_kxerintmqtb2uyj3cfua') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(7, 2, 'tinytable_css_kxerintmqtb2uyj3cfua') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(8, 2, 'tinytable_css_kxerintmqtb2uyj3cfua') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(9, 2, 'tinytable_css_kxerintmqtb2uyj3cfua') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(10, 2, 'tinytable_css_kxerintmqtb2uyj3cfua') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(11, 2, 'tinytable_css_kxerintmqtb2uyj3cfua') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(12, 2, 'tinytable_css_kxerintmqtb2uyj3cfua') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(13, 2, 'tinytable_css_kxerintmqtb2uyj3cfua') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(14, 2, 'tinytable_css_kxerintmqtb2uyj3cfua') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(15, 2, 'tinytable_css_kxerintmqtb2uyj3cfua') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(16, 2, 'tinytable_css_kxerintmqtb2uyj3cfua') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(17, 2, 'tinytable_css_kxerintmqtb2uyj3cfua') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(18, 2, 'tinytable_css_kxerintmqtb2uyj3cfua') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(19, 2, 'tinytable_css_kxerintmqtb2uyj3cfua') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(20, 2, 'tinytable_css_kxerintmqtb2uyj3cfua') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(21, 2, 'tinytable_css_kxerintmqtb2uyj3cfua') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(22, 2, 'tinytable_css_kxerintmqtb2uyj3cfua') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(14, 0, 'tinytable_css_kzesth61iepfnkosp6v5') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(14, 1, 'tinytable_css_kzesth61iepfnkosp6v5') })
window.addEventListener('load', function () { styleCell_tinytable_tihmu5673egnyhaw77lb(14, 2, 'tinytable_css_kzesth61iepfnkosp6v5') })
    </script>

  


</div>
</div>
<p>The main parameter of interest here is the coefficient on <code>education</code>. The IV estimates are noticeably larger than the OLS estimates (<code>0.133</code> relative to <code>0.074</code>). [This is actually quite surprising as you would think that OLS would tend to <em>over-estimate</em> the return to education. This is a very famous example, and there are actually quite a few “explanations” from labor economists about why this sort of result arises.]</p>
</section>
</section>
<section id="regression-discontinuity" class="level2" data-number="18.3">
<h2 data-number="18.3" class="anchored" data-anchor-id="regression-discontinuity"><span class="header-section-number">18.3</span> Regression Discontinuity</h2>
<p>SW 13.4</p>
<p>The final type of natural experiment that we will talk about is called <strong>regression discontinuity</strong>. The sort of natural experiment is available when there is a <strong>running variable</strong> with a threshold (i.e., cutoff) where individuals above the threshold are treated while individuals below the threshold are not treated. These sorts of thresholds/cutoffs are fairly common.</p>
<p>Here are some examples:</p>
<ul>
<li><p>Cutoffs that make students eligible for a scholarship (e.g., the Hope scholarship)</p></li>
<li><p>Rules about maximum numbers of students allowed in a classroom in a particular school district</p></li>
<li><p>Very close political elections</p></li>
<li><p>Very close union elections</p></li>
<li><p>Thresholds in tax laws</p></li>
</ul>
<p>Then, the idea is to compare outcomes among individuals that “barely” were treated relative to those that “barely” weren’t treated. By construction, this often has properties that are similar to an actual experiment as those that are just above the cutoff should have observed and unobserved characteristics that are the same as those just below the cutoff.</p>
<p>Typically, regression discontinuity designs are implemented using a regression that includes a binary variable for participating in the treatment, the running variable itself, and the interaction between the running variable and the treatment, <em>using only observations that are “close” to the cutoff</em>. [What should be considered “close” to the cutoff is actually a hard choice and there are tons of papers suggesting various approaches to decide what “close” means — we’ll largely avoid this and just pick what we think is close.] The estimated coefficient on the treatment indicator variable is an estimate of the average effect of participating in the treatment among those individuals who are close to the cutoff.</p>
<p>This will become clearer with an example.</p>
<section id="example-causal-effect-of-alcohol-on-driving-deaths" class="level3" data-number="18.3.1">
<h3 data-number="18.3.1" class="anchored" data-anchor-id="example-causal-effect-of-alcohol-on-driving-deaths"><span class="header-section-number">18.3.1</span> Example: Causal effect of Alcohol on Driving Deaths</h3>
<p>In this section, we’ll be interested in the causal effect of young adult alcohol consumption on the number of deaths in car accidents.</p>
<p>The idea here will be to compare the number of deaths in car accidents that involve someone who is 21 or just over to the number of deaths in car accidents that involve someone who is just under 21. The reason to make this comparison is that alcohol consumption markedly increases when individuals turn 21 (due to that being the legal drinking age in the U.S.). If alcohol consumption increases car accident deaths, then we should also be able to detect a jump in the number of car accident deaths involving those who are just over 21.</p>
<p>The data that we have consists of age groups by age up to a particular month (<code>agecell</code>) and the number of car accident deaths involving that age group (<code>mva</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"mlda"</span>, <span class="at">package=</span><span class="st">"masteringmetrics"</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># drop some data with missing observations</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>mlda <span class="ot">&lt;-</span> mlda[<span class="fu">complete.cases</span>(mlda),]</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co"># create treated variable</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>mlda<span class="sc">$</span>D <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(mlda<span class="sc">$</span>agecell <span class="sc">&gt;=</span> <span class="dv">21</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In regression discontinuity designs, it is very common to show a plot of the data. That’s what we’ll do here.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mlda, <span class="fu">aes</span>(<span class="at">x=</span>agecell, <span class="at">y=</span>mva)) <span class="sc">+</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept=</span><span class="dv">21</span>) <span class="sc">+</span> </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"age"</span>) <span class="sc">+</span> </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"moving vehicle accident deaths"</span>) <span class="sc">+</span> </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="17-quasi_experiments_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This figure at least suggests that the number of car accident deaths does appear to jump at age 21.</p>
<p>Now, let’s run the regression that we talked about earlier, involving a treatment dummy, age, and age interacted with the treatment.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>rd_reg <span class="ot">&lt;-</span> <span class="fu">lm</span>(mva <span class="sc">~</span> D <span class="sc">+</span> agecell <span class="sc">+</span> agecell<span class="sc">*</span>D, <span class="at">data=</span>mlda)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(rd_reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mva ~ D + agecell + agecell * D, data = mlda)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.4124 -0.7774 -0.2913  0.8495  3.2378 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  83.8492     9.3328   8.984 1.63e-11 ***
D            28.9450    13.8638   2.088   0.0426 *  
agecell      -2.5676     0.4661  -5.508 1.77e-06 ***
D:agecell    -1.1624     0.6592  -1.763   0.0848 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.299 on 44 degrees of freedom
Multiple R-squared:  0.7222,    Adjusted R-squared:  0.7032 
F-statistic: 38.13 on 3 and 44 DF,  p-value: 2.671e-12</code></pre>
</div>
</div>
<p>These results suggest that alcohol consumption increased car accident deaths (you can see this from the estimated coefficient on <code>D</code>). [The setup in this example is somewhat simplified; if you wanted to be careful about how much alcohol consumption increased car accident deaths, then we would probably need to scale up our estimate by how much alcohol consumption increases on average when people turn 21. Nevertheless, what we have presented above does suggest that alcohol consumption increases car accident deaths.]</p>
<p>Finally, let me show one more plot that is common to report in a regression discontinuity design.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get predicted values for plotting</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>mlda<span class="sc">$</span>preds <span class="ot">&lt;-</span> <span class="fu">predict</span>(rd_reg)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># make plot</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mlda, <span class="fu">aes</span>(<span class="at">x=</span>agecell, <span class="at">y=</span>mva, <span class="at">color=</span><span class="fu">as.factor</span>(D))) <span class="sc">+</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>preds)) <span class="sc">+</span> </span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept=</span><span class="dv">21</span>) <span class="sc">+</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">color=</span><span class="st">"treated"</span>, <span class="at">x=</span><span class="st">"age"</span>, <span class="at">y=</span><span class="st">"moving vehicle accident deaths"</span>) <span class="sc">+</span> </span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="17-quasi_experiments_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This shows the two lines that we effectively fit with the regression that included the binary variable for the treatment, the running variable, and their interaction. The “jump” between the red line and the blue line at <code>age=21</code> is our estimated effect of the treatment.</p>
</section>
</section>
<section id="lab-7-drunk-driving-laws" class="level2" data-number="18.4">
<h2 data-number="18.4" class="anchored" data-anchor-id="lab-7-drunk-driving-laws"><span class="header-section-number">18.4</span> Lab 7: Drunk Driving Laws</h2>
<p>For this lab, we will use the <code>Fatalities</code> data. We will study the causal effect of mandatory jail sentence policies for drunk driving on traffic fatalities. The <code>Fatalities</code> data consists of panel data of traffic fatality death rates, whether or not a state has a mandatory jail sentence policy or not as well as several other variables from 1982-1988. Economic theory suggests that raising the cost of some behavior (in this case, you can think of a mandatory jail sentence as raising the cost of drunk driving) will lead to less of that behavior. That being said, it’s both interesting to test this theory and also consider the magnitude of this effect. That’s what we’ll do in this problem.</p>
<ol type="1">
<li><p>This data comes in a somewhat messier format than some of the data that we have used previously. To start with, create a new column in the data called <code>afatal_per_million</code> that is the number of alcohol involved vehicle fatalities per millions people in a state in a particular year. The variable <code>afatal</code> contains the total number of alcohol involved vehicle fatalities, and the variable <code>pop</code> contains the total population in a state.</p></li>
<li><p>Using a subset of the data from 1988, run a regression of <code>afatal_per_million</code> on whether or not a state has a mandatory jail sentence policy <code>jail</code>. How do you interpret the results?</p></li>
<li><p>Using the same subset from part 2, run a regression of <code>afatal_per_million</code> on <code>jail</code>, unemployment rate (<code>unemp</code>), the tax on a case of beer (<code>beertax</code>), the percentage of southern baptists in the state (<code>baptist</code>), the percentage of residents residing in dry counties (<code>dry</code>), the percentage of young drivers in the state, (<code>youngdrivers</code>), and the average miles driven per person in a state (<code>miles</code>). How do you interpret the estimated coefficient on <code>jail</code>? Would you consider this to be a reasonable estimate of the (average) causal effect of mandatory jail policies on alcohol related fatalities?</p></li>
<li><p>Now, using the full data, let’s estimate a fixed effects model with alcohol related fatalities per million as the outcome and mandatory jail policies as a regressor. Estimate the model using first differences and make sure to include time fixed effects. How do you interpret the results?</p></li>
<li><p>Estimate the same model as in part 4, but using the within estimator instead of first differences. Compare these results to the ones from part 4.</p></li>
<li><p>Using the same within estimator as in part 5, include the same set of covariates from part 3 and interpret the estimated effect of mandatory jail policies. How do these estimates compare to the earlier ones?</p></li>
<li><p>Now, we’ll switch to using a difference in differences approach to estimating the effect of mandatory jail policies. First, we’ll manipulate the data some.</p>
<ol type="a">
<li><p>To keep things simple, let’s start by limiting the data to the years 1982 and 1988 and drop the in-between periods.</p></li>
<li><p>Second, let’s calculate the change in alcohol related fatalities per million between 1982 and 1998 and keep the covariates that we have been using from 1982. One way to do this, is to use the <code>pivot_wider</code> function from the <code>tidyr</code>. In the case of panel data, “long format” data means that each row in the data corresponds to a paricular observation <em>and</em> a particular time period. Thus, with long format data, there are <span class="math inline">\(n \times T\)</span> total rows in the data. On the other hand, “wide format” data means that each row holds all the data (across all time periods) for a particular observation. Converting back and forth between long and wide formats is a common data manipulation task. <strong>Hint:</strong> This step is probably unfamiliar, so I’d recommend seeing if you can use <code>?tidyr::pivot_wider</code> to see if you can figure out how to complete this step, but, if not, you can copy this code from the solutions in the next section.</p></li>
<li><p>Finally, drop all states that are already treated in 1982.</p></li>
</ol></li>
<li><p>Using the data that you constructed in part 7, implement the difference in differences regression of the change in alcohol related fatalities per million from 1982 to 1988 on the mandatory jail policy. How do you interpret these results and how do they compare to the previous ones? Now, additionally include the set of covariates that we have been using in this model. How do you interpret these results and how do they compare to the previous ones?</p></li>
<li><p>An alternative to DID, is to include the lagged outcome as a covariate. Using the data constructed in part 7, run a regression of alcohol related fatalities per million in 1988 on the mandatory jail policy and alcohol related fatalities per million in 1982. How do you interpret these results and how do they compare to the previous ones? Now include the additional covariates that we have been using in this model. How do you interpret these results and how do they compare to the previous ones?</p></li>
<li><p>Comment on your results from parts 1-9. Which, if any, of these are you most inclined to interpret as a reasonable estimate of the (average) causal effect of mandatory jail policies on alcohol related policies?</p></li>
</ol>
</section>
<section id="lab-7-solutions" class="level2" data-number="18.5">
<h2 data-number="18.5" class="anchored" data-anchor-id="lab-7-solutions"><span class="header-section-number">18.5</span> Lab 7: Solutions</h2>
<ol type="1">
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plm)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Fatalities, <span class="at">package=</span><span class="st">"AER"</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>Fatalities<span class="sc">$</span>afatal_per_million <span class="ot">&lt;-</span> <span class="dv">1000000</span> <span class="sc">*</span> (Fatalities<span class="sc">$</span>afatal <span class="sc">/</span> Fatalities<span class="sc">$</span>pop )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>Fatalities88 <span class="ot">&lt;-</span> <span class="fu">subset</span>(Fatalities, year<span class="sc">==</span><span class="dv">1988</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>reg88 <span class="ot">&lt;-</span> <span class="fu">lm</span>(afatal_per_million <span class="sc">~</span> jail, <span class="at">data=</span>Fatalities88)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg88)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = afatal_per_million ~ jail, data = Fatalities88)

Residuals:
    Min      1Q  Median      3Q     Max 
-36.123 -16.622  -1.469   8.642 112.260 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   59.496      4.273  13.923   &lt;2e-16 ***
jailyes        9.155      7.829   1.169    0.248    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 24.55 on 45 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.02949,   Adjusted R-squared:  0.007921 
F-statistic: 1.367 on 1 and 45 DF,  p-value: 0.2484</code></pre>
</div>
</div>
<p>The estimated coefficient on mandatory jail laws is 9.155. We should interpret this as just the difference between alcohol related fatalities per million in states that had mandatory jail laws in 1988 relative to states that did not have them. We cannot reject that there is no difference between states where the policy is in place relative to those that do not have the policy.</p>
<ol start="3" type="1">
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>reg88_covs <span class="ot">&lt;-</span> <span class="fu">lm</span>(afatal_per_million <span class="sc">~</span> jail <span class="sc">+</span> unemp <span class="sc">+</span> beertax <span class="sc">+</span> baptist <span class="sc">+</span> dry <span class="sc">+</span> youngdrivers <span class="sc">+</span> miles, <span class="at">data=</span>Fatalities88)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg88_covs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = afatal_per_million ~ jail + unemp + beertax + baptist + 
    dry + youngdrivers + miles, data = Fatalities88)

Residuals:
    Min      1Q  Median      3Q     Max 
-39.065  -9.907  -1.690   9.673  82.100 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)  -29.373536  32.500240  -0.904   0.3717  
jailyes        3.120574   6.849271   0.456   0.6512  
unemp          4.815081   1.892369   2.544   0.0150 *
beertax        2.311850   9.521684   0.243   0.8094  
baptist        0.661694   0.527228   1.255   0.2169  
dry           -0.026675   0.383956  -0.069   0.9450  
youngdrivers  -0.092100 142.804244  -0.001   0.9995  
miles          0.006802   0.002822   2.411   0.0207 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 19.41 on 39 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.4742,    Adjusted R-squared:  0.3798 
F-statistic: 5.024 on 7 and 39 DF,  p-value: 0.0003999</code></pre>
</div>
</div>
<p>The estimated coefficient on jail is 3.12. It is somewhat smaller than the previous estimate, though neither is statistically significant. We should interpret this as the partial effect of the mandatory jail policy, that is, that we estimate that mandatory jail laws increase the number of alcohol related fatalities per million by 3.12 on average controlling for the unemployment rate, beer tax, the fraction of southern baptists in the state, the fraction of residents in dry counties, the fraction of young drivers, and the average miles driven in the state. We cannot reject that the partial effect of mandatory jail policies is equal to 0.</p>
<ol start="4" type="1">
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>fd_reg <span class="ot">&lt;-</span> <span class="fu">plm</span>(afatal_per_million <span class="sc">~</span> jail <span class="sc">+</span> <span class="fu">as.factor</span>(year),</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">effect=</span><span class="st">"individual"</span>,</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">index=</span><span class="st">"state"</span>, <span class="at">model=</span><span class="st">"fd"</span>,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">data=</span>Fatalities)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fd_reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Oneway (individual) effect First-Difference Model

Call:
plm(formula = afatal_per_million ~ jail + as.factor(year), data = Fatalities, 
    effect = "individual", model = "fd", index = "state")

Unbalanced Panel: n = 48, T = 6-7, N = 335
Observations used in estimation: 287

Residuals:
     Min.   1st Qu.    Median   3rd Qu.      Max. 
-51.66677  -5.09887   0.23801   6.28688 119.08976 

Coefficients: (1 dropped because of singularities)
                    Estimate Std. Error t-value Pr(&gt;|t|)   
(Intercept)         -2.15376    0.80673 -2.6697 0.008035 **
jailyes              2.60763    5.28351  0.4935 0.622016   
as.factor(year)1983 -5.28423    1.82330 -2.8982 0.004050 **
as.factor(year)1984 -3.58247    2.29451 -1.5613 0.119577   
as.factor(year)1985 -5.60800    2.43517 -2.3029 0.022017 * 
as.factor(year)1986 -0.74192    2.28988 -0.3240 0.746180   
as.factor(year)1987 -2.16244    1.80716 -1.1966 0.232476   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Total Sum of Squares:    54692
Residual Sum of Squares: 51620
R-Squared:      0.056171
Adj. R-Squared: 0.035946
F-statistic: 2.77733 on 6 and 280 DF, p-value: 0.012223</code></pre>
</div>
</div>
<p>We should interpret the estimated coefficient on <code>jail</code> as an estimate of how much alcohol related traffic fatalities per million change on average under mandatory jail policies after accounting for time invariant variables whose effects do not change over time. Again, we cannot reject that the effect is equal to 0.</p>
<ol start="5" type="1">
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>within_reg <span class="ot">&lt;-</span> <span class="fu">plm</span>(afatal_per_million <span class="sc">~</span> jail <span class="sc">+</span> <span class="fu">as.factor</span>(year),</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">effect=</span><span class="st">"individual"</span>,</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">index=</span><span class="st">"state"</span>, <span class="at">model=</span><span class="st">"within"</span>,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">data=</span>Fatalities)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(within_reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Oneway (individual) effect Within Model

Call:
plm(formula = afatal_per_million ~ jail + as.factor(year), data = Fatalities, 
    effect = "individual", model = "within", index = "state")

Unbalanced Panel: n = 48, T = 6-7, N = 335

Residuals:
       Min.     1st Qu.      Median     3rd Qu.        Max. 
-95.1937300  -4.9678238   0.0088078   5.1611249  40.6263546 

Coefficients:
                    Estimate Std. Error t-value  Pr(&gt;|t|)    
jailyes               8.3327     4.9666  1.6777 0.0945164 .  
as.factor(year)1983  -7.9151     2.6936 -2.9384 0.0035734 ** 
as.factor(year)1984  -8.4863     2.7115 -3.1298 0.0019341 ** 
as.factor(year)1985 -12.7849     2.7331 -4.6778 4.518e-06 ***
as.factor(year)1986 -10.0726     2.7331 -3.6854 0.0002741 ***
as.factor(year)1987 -13.5276     2.7115 -4.9890 1.067e-06 ***
as.factor(year)1988 -13.6296     2.7279 -4.9964 1.030e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Total Sum of Squares:    53854
Residual Sum of Squares: 47607
R-Squared:      0.116
Adj. R-Squared: -0.054487
F-statistic: 5.24882 on 7 and 280 DF, p-value: 1.2051e-05</code></pre>
</div>
</div>
<p>The estimated coefficient on <code>jail</code> has the same interpretation as in the previous problem. The estimated effect here is marginally statistically significant. 6.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>within_reg_covs <span class="ot">&lt;-</span> <span class="fu">plm</span>(afatal_per_million <span class="sc">~</span> jail <span class="sc">+</span> unemp <span class="sc">+</span> beertax <span class="sc">+</span> baptist <span class="sc">+</span> dry <span class="sc">+</span> youngdrivers <span class="sc">+</span> miles,</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">effect=</span><span class="st">"individual"</span>,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">index=</span><span class="st">"state"</span>, <span class="at">model=</span><span class="st">"within"</span>,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">data=</span>Fatalities)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(within_reg_covs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Oneway (individual) effect Within Model

Call:
plm(formula = afatal_per_million ~ jail + unemp + beertax + baptist + 
    dry + youngdrivers + miles, data = Fatalities, effect = "individual", 
    model = "within", index = "state")

Unbalanced Panel: n = 48, T = 6-7, N = 335

Residuals:
     Min.   1st Qu.    Median   3rd Qu.      Max. 
-95.62306  -5.69773  -0.56903   4.79219  47.80871 

Coefficients:
                Estimate  Std. Error t-value  Pr(&gt;|t|)    
jailyes       4.9731e+00  4.9613e+00  1.0024   0.31702    
unemp        -1.1340e+00  5.6592e-01 -2.0038   0.04605 *  
beertax      -2.7456e+01  1.5080e+01 -1.8207   0.06972 .  
baptist       2.5083e+00  4.3324e+00  0.5790   0.56308    
dry           4.3092e-01  1.0870e+00  0.3964   0.69208    
youngdrivers  2.6357e+02  5.0169e+01  5.2537 2.957e-07 ***
miles        -6.8899e-04  7.3182e-04 -0.9415   0.34727    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Total Sum of Squares:    53854
Residual Sum of Squares: 48083
R-Squared:      0.10717
Adj. R-Squared: -0.065023
F-statistic: 4.80119 on 7 and 280 DF, p-value: 4.0281e-05</code></pre>
</div>
</div>
<p>We should interpret the estimated coefficient on <code>jail</code> as an estimate of how much alcohol related traffic fatalities per million change on average under mandatory jail policies after controlling for the unemployment rate, beer taxes, the fraction of the state that is southern baptist, the fraction of the state that lives in a dry county, the fraction of young drivers in a state, and the average number of miles driven per person in the stata, and accounting for time invariant variables whose effects do not change over time.</p>
<ol start="7" type="1">
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># part a: convert data to two period panel data</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>two_period <span class="ot">&lt;-</span> <span class="fu">subset</span>(Fatalities, year<span class="sc">==</span><span class="dv">1982</span> <span class="sc">|</span> year<span class="sc">==</span><span class="dv">1988</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co"># and drop some missing</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>two_period <span class="ot">&lt;-</span> <span class="fu">subset</span>(two_period, <span class="sc">!</span><span class="fu">is.na</span>(jail))</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>two_period <span class="ot">&lt;-</span> BMisc<span class="sc">::</span><span class="fu">makeBalancedPanel</span>(two_period, <span class="st">"state"</span>, <span class="st">"year"</span>)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>two_period<span class="sc">$</span>jail <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(two_period<span class="sc">$</span>jail<span class="sc">==</span><span class="st">"yes"</span>)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="co"># part b: convert into wide format</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>wide_df <span class="ot">&lt;-</span> <span class="fu">pivot_wider</span>(two_period, </span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>                       <span class="at">id_cols=</span><span class="st">"state"</span>, </span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>                       <span class="at">names_from=</span><span class="st">"year"</span>,</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>                       <span class="at">values_from=</span><span class="fu">c</span>(<span class="st">"jail"</span>, <span class="st">"afatal_per_million"</span>))</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a><span class="co"># add back other covariates from 1982</span></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>wide_df <span class="ot">&lt;-</span> <span class="fu">merge</span>(wide_df, <span class="fu">subset</span>(Fatalities, year<span class="sc">==</span><span class="dv">1982</span>)[,<span class="fu">c</span>(<span class="st">"unemp"</span>, <span class="st">"beertax"</span>, <span class="st">"baptist"</span>, <span class="st">"dry"</span>, <span class="st">"youngdrivers"</span>, <span class="st">"miles"</span>,<span class="st">"state"</span>)], <span class="at">by=</span><span class="st">"state"</span>)</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a><span class="co"># change in fatal accidents over time</span></span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>wide_df<span class="sc">$</span>Dafatal_per_million <span class="ot">&lt;-</span> wide_df<span class="sc">$</span>afatal_per_million_1988 <span class="sc">-</span> wide_df<span class="sc">$</span>afatal_per_million_1982</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a><span class="co"># part c: drop already treated states</span></span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>wide_df <span class="ot">&lt;-</span> <span class="fu">subset</span>(wide_df, jail_1982<span class="sc">==</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="8" type="1">
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>did <span class="ot">&lt;-</span> <span class="fu">lm</span>(Dafatal_per_million <span class="sc">~</span> jail_1988, <span class="at">data=</span>wide_df)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(did)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Dafatal_per_million ~ jail_1988, data = wide_df)

Residuals:
    Min      1Q  Median      3Q     Max 
-55.652 -10.993   5.033  10.405  76.822 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)  -12.585      4.242  -2.966  0.00532 **
jail_1988      5.102     11.695   0.436  0.66526   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 24.37 on 36 degrees of freedom
Multiple R-squared:  0.005259,  Adjusted R-squared:  -0.02237 
F-statistic: 0.1903 on 1 and 36 DF,  p-value: 0.6653</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>did_covs <span class="ot">&lt;-</span> <span class="fu">lm</span>(Dafatal_per_million <span class="sc">~</span> jail_1988 <span class="sc">+</span> unemp <span class="sc">+</span> beertax <span class="sc">+</span> baptist <span class="sc">+</span> dry <span class="sc">+</span> youngdrivers <span class="sc">+</span> miles, <span class="at">data=</span>wide_df)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(did_covs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Dafatal_per_million ~ jail_1988 + unemp + beertax + 
    baptist + dry + youngdrivers + miles, data = wide_df)

Residuals:
    Min      1Q  Median      3Q     Max 
-38.346 -12.383   1.456   9.092  60.585 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)    6.851636  50.643035   0.135   0.8933  
jail_1988     -1.853041  10.834391  -0.171   0.8653  
unemp          3.725007   1.919862   1.940   0.0618 .
beertax        8.300778  10.052007   0.826   0.4154  
baptist        0.527893   0.723263   0.730   0.4711  
dry           -0.955636   0.546475  -1.749   0.0906 .
youngdrivers  89.432017 234.379768   0.382   0.7055  
miles         -0.010360   0.005823  -1.779   0.0854 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 21.9 on 30 degrees of freedom
Multiple R-squared:  0.3303,    Adjusted R-squared:  0.174 
F-statistic: 2.114 on 7 and 30 DF,  p-value: 0.07276</code></pre>
</div>
</div>
<p>If we are willing to believe that, in the absence of the policy, that trends in alcohol related fatalities per million people would have followed the same trends over time for treated and untreated states, then we can interpret these as causal effects. These estimates are broadly similar to the previous ones though the second ones (that include additional covariates) are about the only ones where we ever get a negative estimate for the effect of mandatory jail policies. Like the previous estimates, neither of these estimates are statistically different from 0.</p>
<ol start="9" type="1">
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>lag_reg <span class="ot">&lt;-</span> <span class="fu">lm</span>(afatal_per_million_1988 <span class="sc">~</span> jail_1988 <span class="sc">+</span> afatal_per_million_1982, <span class="at">data=</span>wide_df)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lag_reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = afatal_per_million_1988 ~ jail_1988 + afatal_per_million_1982, 
    data = wide_df)

Residuals:
    Min      1Q  Median      3Q     Max 
-29.120 -12.663  -0.684   6.873  92.390 

Coefficients:
                        Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              19.0810    10.1089   1.888 0.067401 .  
jail_1988                 3.4323    10.3171   0.333 0.741363    
afatal_per_million_1982   0.5607     0.1303   4.303 0.000129 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 21.47 on 35 degrees of freedom
Multiple R-squared:  0.3462,    Adjusted R-squared:  0.3088 
F-statistic: 9.266 on 2 and 35 DF,  p-value: 0.0005896</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>lag_reg_covs <span class="ot">&lt;-</span> <span class="fu">lm</span>(afatal_per_million_1988 <span class="sc">~</span> jail_1988 <span class="sc">+</span> afatal_per_million_1982 <span class="sc">+</span> unemp <span class="sc">+</span> beertax <span class="sc">+</span> baptist <span class="sc">+</span> dry <span class="sc">+</span> youngdrivers <span class="sc">+</span> miles, <span class="at">data=</span>wide_df)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lag_reg_covs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = afatal_per_million_1988 ~ jail_1988 + afatal_per_million_1982 + 
    unemp + beertax + baptist + dry + youngdrivers + miles, data = wide_df)

Residuals:
    Min      1Q  Median      3Q     Max 
-27.840  -8.793  -1.364   5.146  71.409 

Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)             -17.292595  46.318477  -0.373  0.71161   
jail_1988                 0.817453   9.786782   0.084  0.93401   
afatal_per_million_1982   0.505371   0.173718   2.909  0.00689 **
unemp                     3.189918   1.736443   1.837  0.07647 . 
beertax                   2.885796   9.236174   0.312  0.75694   
baptist                   0.965785   0.668259   1.445  0.15911   
dry                      -0.567567   0.509915  -1.113  0.27482   
youngdrivers            120.615853 211.026841   0.572  0.57202   
miles                    -0.002692   0.005888  -0.457  0.65087   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 19.7 on 29 degrees of freedom
Multiple R-squared:  0.5443,    Adjusted R-squared:  0.4186 
F-statistic: 4.329 on 8 and 29 DF,  p-value: 0.001596</code></pre>
</div>
</div>
<p>These estimates directly control for alcohol related fatalities per million in the pre-treatment period 1982. These sorts of specifications are less common in economics, but, in my view, it seems like a reasonable approach here. That said, the results are more or less the same as earlier estimates.</p>
<ol start="10" type="1">
<li>We don’t have very strong evidence that mandatory jail policies reduced the number traffic fatalities. In my view, probably the best specifications for trying to understand the causal effects are the ones in part 7 (particularly, the ones that include covariates there), but I think that the the results in parts 4-9 are also informative. Broadly, these estimates are more or less similar — none of them are statistically significant and most are positive (which is an unexpected sign).</li>
</ol>
<p>Before we finish, let me mention a few caveats to these results:</p>
<ul>
<li><p>First, I would be very hesitant to interpret these results as definitively saying that mandatory jail policies have no effect on alcohol related traffic fatalities. The main reason to be clear about this is that our standard error are quite large. For example, in the second specification in part 7 (the one I like the most), a 95% confidence interval for our estimate is <span class="math inline">\([-23.1, 19.4]\)</span>. This is a wide confidence interval — the average number of alcohol related traffic fatalities per million across all states and time periods is only 66. So our estimates are basically still compatible with very large reductions in alcohol related traffic fatalities up to large increases in alcohol related traffic fatalities.</p></li>
<li><p>Let me make one more comment about the sign of our results. Many of our point estimates are positive; as we discussed earlier, it is hard to rationalize harsher punishments <em>increasing</em> alcohol related traffic fatalities. I think the main explanation for these results is just that our estimates are pretty noisy and, therefore, more or less “by chance” we are getting estimates that have an unexpected sign. But there are some other possible explanations that are worth mentioning. For one, there are a number of other policies related to drunk driving that occurred in the 1980s (particularly, related to legal drinking age) but perhaps others. It is not clear how these would interact with our estimates, but they could certainly play some role. Besides that, it seems to me that we have a pretty good set of covariates that enter our models, but there could be important covariates that we are missing. For this reason, some expertise in how to model state-level traffic fatalities is actually a very important skill here (actually probably the key skill here!)</p></li>
</ul>
</section>
<section id="coding-questions" class="level2" data-number="18.6">
<h2 data-number="18.6" class="anchored" data-anchor-id="coding-questions"><span class="header-section-number">18.6</span> Coding Questions</h2>
<ol type="1">
<li><p>For this problem, we will use the data <code>rand_hie</code>. This is data from the RAND health insurance experiment in the 1980s. In the experiment, participants were randomly assigned to get Catastrophic (the least amount of coverage), insurance that came with a Deductible, insurance that came with Cost Sharing (i.e., co-insurance so that an individual pays part of their medical insurance), and Free (so that there is no cost of medical care).</p>
<p>For this problem, we will be interested in whether or not changing the type of health insurance changed the amount of health care utilization and the health status of individuals.</p>
<p>We will focus on the difference between the least amount of health insurance (“Catastrophic”) and the most amount of health insurance (“Free”). In particular, you can start this problem by creating a new dataset by running the following command: <code>rand_hie_subset &lt;- subset(rand_hie, plan_type %in% c("Catastrophic", "Free"))</code></p>
<p>and use this data to answer the questions below.</p>
<ol type="a">
<li><p>Use a regression to estimate the average difference between total medical expenditure (<code>total_med_expenditure</code>) by plan type (<code>plan_type</code>) and report your results. Should you interpret these as average causal effects? Explain.</p></li>
<li><p>Use a regression to estimate the average difference between face to face doctors visits (<code>face_to_face_visits</code>) by plan type (<code>plan_type</code>) and report your results. Should you interpret these as average causal effects? Explain.</p></li>
<li><p>Use a regression to estimate the average difference between the overall health index (<code>health_index</code>) by plan type (<code>plan_type</code>) and report your results. Should you interpret these as average causal effects? Explain.</p></li>
<li><p>How do you interpret the results from parts a-c?</p></li>
</ol></li>
<li><p>For this problem, we will study the causal effect of having more children on women’s labor supply using the data <code>Fertility</code>.</p>
<ol type="a">
<li><p>Let’s start by running a regression of the number of hours that a woman typically works per week (<code>work</code>) on whether or not she has more than two children (<code>morekids</code>), her age and <span class="math inline">\(age^2\)</span>, and race/ethnicity (<code>afam</code> and <code>hispanic</code>). Report your results. How do you feel about interpreting the estimated coefficient on <code>morekids</code> as the causal effect of having more than two children? Explain.</p></li>
<li><p>One possible instrument in this setup is the sex composition of the first two children (i.e., whether they are both girls, both boys, or a boy and a girl). The thinking here is that, at least in the United States, parents tend to have a preference for having both a girl and a boy and that, therefore, parents whose first two children have the same sex may be more likely to have a third child than they would have been if they have a girl and a boy. Do you think that using a binary variable for whether or not the first two children have the same sex is a reasonable instrument of for <code>morekids</code> from part a?</p></li>
<li><p>Create a new variable called <code>samesex</code> that is equal to one for families whose first two children have the same sex. Using the same specification as in part a, use <code>samesex</code> as an instrument for <code>morekids</code> and report the results. Provide some discussion about your results.</p></li>
</ol></li>
<li><p>For this question, we will use the <code>AJR</code> data. A deep question in development economics is: Why are some countries much richer than other countries? One explanation for this is that richer countries have different institutions (e.g., property rights, democracy, etc.) that are conducive to growth. Its hard to study these questions though because institutions do not arise randomly — there could be reverse causality so that property rights, democracy, etc. are (perhaps partially) caused by being rich rather than the other way around. Alternatively, other factors (say a country’s geography) could cause both of these. We’ll consider one instrumental variables approach to thinking about this question in this problem.</p>
<ol type="a">
<li><p>Run a regression of the log of per capita GDP (the log of per capita GDP is stored in the variable <code>GDP</code>) on a measure of the protection against expropriation risk (this is a measure of how “good” a country’s institutions are (a larger number indicates “better” institutions) and it is in the variable <code>Exprop</code>). How do you interpret these results? Do you think it would be reasonable to interpret the estimated coefficient on <code>Exprop</code> as the causal effect of institutions on GDP.</p></li>
<li><p>One possible instrument for <code>Exprop</code> is settler mortality (we’ll use the log of this which is available in the variable <code>logMort</code>). Settler mortality is a measure of how dangerous it was for early settlers of a particular location. The idea is that places that have high settler mortality may have set up worse (sometimes called “extractive”) institutions than places that had lower settler mortality. But that settler mortality (from a long time ago) does not have any other direct effect on modern GDP. Provide some discussion about whether settler mortality is a valid instrument for institutions.</p></li>
<li><p>Estimate an IV regression of <code>GDP</code> on <code>Exprop</code> using <code>logMort</code> as an instrument for <code>Exprop</code>. How do you interpret the results? How do these results compare to the ones from part a?</p></li>
</ol></li>
<li><p>For this question, we’ll use the data <code>house</code> to study the causal effect of incumbency on the probability that a member of the House of Representatives gets re-elected.</p>
<ol type="a">
<li><p>One way to try to estimate the causal effect of incumbency is to just run a regression where the outcome is <code>democratic_vote_share</code> (this is the same outcome we’ll use below) and where the model includes a dummy variable for whether or not the democratic candidate is an incumbent. What are some limitions of this strategy?</p></li>
<li><p>The <code>house</code> data contains data about the margin of victory (is positive if they won the election and negative if they lost) for Democratic candidates in the current election and data about the Democratic margin of victory in the past election. Explain how you could use this data in a regression discontinuity design to estimate the causal effect of incumbency.</p></li>
<li><p>Use the <code>house</code> data to implement the regression discontinuity design that you proposed in part b. What do you estimate as the causal effect of incumbency?</p></li>
</ol></li>
<li><p>For this problem, we will use the data <code>banks</code>. We will study the causal effect of monetary policy on bank closures during the Great Depression. We’ll consider an interesting natural experiment in Mississippi where half the northern half of the state was in St.&nbsp;Louis’s federal reserve district (District 8) and the southern half of the state was in Atlanta’s federal reserve district (District 6). Atlanta had much looser monetary policy (meaning they substantially increased lending) than St.&nbsp;Louis during the early part of the Great Depression and our interest is in whether looser monetary policy made an difference.</p>
<ol type="a">
<li><p>Plot the total number of banks separately for District 6 and District 8 across all available time periods in the data.</p></li>
<li><p>An important event in the South early in the Great Depression was the collapse of Caldwell and Company — the largest banking chain in the South at the time. This happened in November 1930. The Atlanta Fed’s lending markedly increased quickly after this event while St.&nbsp;Louis’s did not. Calculate a DID estimate of the effect of looser monetary policy on the number of banks that are still in business. How do you interpret these results? <strong>Hint:</strong> You can calculate this by taking the difference between the number of banks in District 6 relative to the number of banks in District 8 across all time periods relative to the difference between the number of banks in District 6 relative to District 8 in the first period (July 1, 1929).</p></li>
</ol></li>
</ol>
</section>
<section id="extra-questions" class="level2" data-number="18.7">
<h2 data-number="18.7" class="anchored" data-anchor-id="extra-questions"><span class="header-section-number">18.7</span> Extra Questions</h2>
<ol type="1">
<li><p>What is the difference between treatment effect homogeneity and treatment effect heterogeneity?</p></li>
<li><p>Why do most researchers give up on trying to estimate the individual-level effect of participating in a treatment?</p></li>
<li><p>Explain what unconfoundedness means.</p></li>
<li><p>What is the key condition underlying a difference-in-differences approach to learn about the causal effect of some treatment on some outcome?</p></li>
<li><p>What are two key conditions for a valid instrument?</p></li>
<li><p>Suppose you are interested in the causal effect of participating in a union on a person’s income. Consider the following approaches.</p>
<ol type="a">
<li><p>Suppose you run the following regression</p>
<p><span class="math display">\[\begin{align*}
   Earnings_i = \beta_0 + \alpha Union_i + \beta_1 Education_i + U_i
\end{align*}\]</span></p>
<p>Would it be reasonable to interpret <span class="math inline">\(\hat{\alpha}\)</span> in this regression as an estimate of the causal effect of participating in a union on earnings? Explain.</p></li>
<li><p>Suppose you have access to panel data and run the following fixed effects regression <span class="math display">\[\begin{align*}
   Earnings_{it} = \beta_{0,t} + \alpha Union_{it} + \beta_1 Education_{it} + \eta_i + U_{it}
\end{align*}\]</span></p>
<p>where <span class="math inline">\(\eta_i\)</span> is an individual fixed effect. Would it be reasonable to interpert <span class="math inline">\(\hat{\alpha}\)</span> in this regression as an estimate of the causal effect of participating in a union on earnings? Explain. Can you think of any other advantages or disadvantages of this approach?</p></li>
<li><p>Going back to the case with cross-sectional data, consider the regression <span class="math display">\[\begin{align*}
   Earnings_i = \beta_0 + \alpha Union_i + U_i
\end{align*}\]</span> but using the variable <span class="math inline">\(Z_i = 1\)</span> if birthday is between Jan.&nbsp;1 and Jun.&nbsp;30 while <span class="math inline">\(Z_i=0\)</span> otherwise. Would it be reasonable to interpert <span class="math inline">\(\hat{\alpha}\)</span> in this regression as an estimate of the causal effect of participating in a union on earnings? Explain. Can you think of any other advantages or disadvantages of this approach?</p></li>
</ol></li>
<li><p>Suppose that you are interested in the effect of lower college costs on the probability of graduating from college. You have access to student-level data from Georgia where students are eligible for the Hope Scholarship if they can keep their GPA above 3.0.</p>
<ol type="a">
<li><p>What strategy can use to exploit this institional setting to learn about the causal effect of lower college costs on the probability of going to college?</p></li>
<li><p>What sort of data would you need in order to implement this strategy?</p></li>
<li><p>Can you think of any ways that the approach that you suggested could go wrong?</p></li>
<li><p>Another researcher reads the results from the approach you have implemented and complains that your results are only specific to students who have grades right around the 3.0 cutoff. Is this a fair criticism?</p></li>
</ol></li>
<li><p>Suppose you are willing to believe versions of unconfoundedness, a linear model for untreated potential outcomes, and treatment effect homogeneity so that you could write <span class="math display">\[\begin{align*}
  Y_i = \beta_0 + \alpha D_i + \beta_1 X_i + \beta_2 W_i + U_i
\end{align*}\]</span> with <span class="math inline">\(\E[U|D,X,W] = 0\)</span> so that you were willing to interpret <span class="math inline">\(\alpha\)</span> in this regression as the causal effect of <span class="math inline">\(D\)</span> on <span class="math inline">\(Y\)</span>. However, suppose that <span class="math inline">\(W\)</span> is not observed so that you cannot operationalize the above regression.</p>
<ol type="a">
<li><p>Since you do not observe <span class="math inline">\(W\)</span>, you are considering just running a regression of <span class="math inline">\(Y\)</span> on <span class="math inline">\(D\)</span> and <span class="math inline">\(X\)</span> and interpreting the estimated coefficient on <span class="math inline">\(D\)</span> as the causal effect of <span class="math inline">\(D\)</span> on <span class="math inline">\(Y\)</span>. Does this seem like a good idea?</p></li>
<li><p>In part (a), we can write a version of the model that you are thinking about estimating as <span class="math display">\[\begin{align*}
   Y_i = \delta_0 + \delta_1 D_i + \delta_2 X_i + \epsilon_i
\end{align*}\]</span> Suppose that <span class="math inline">\(\E[\epsilon | D, X] = 0\)</span> and suppose also that <span class="math display">\[\begin{align*}
W_i = \gamma_0 + \gamma_1 D_i + \gamma_2 X_i + V_i
  \end{align*}\]</span> with <span class="math inline">\(\E[V|D,X]=0\)</span>. Provide an expression for <span class="math inline">\(\delta_1\)</span> in terms of <span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\gamma\)</span>’s and <span class="math inline">\(\beta\)</span>’s. Explain what this expression means.</p></li>
</ol></li>
<li><p>Suppose you have access to an experiment where some participants were randomly assigned to participate in a job training program and others were randomly assigned not to participate. However, some individuals that were assigned to participate in the treatment decided not to actually participate. Let’s use the following notation: <span class="math inline">\(D=1\)</span> for individuals who actually participated and <span class="math inline">\(D=0\)</span> for individuals who did not participate. <span class="math inline">\(Z=1\)</span> for individuals who were assigned to the treatment and <span class="math inline">\(Z=0\)</span> for individuals assigned not to participate (here, <span class="math inline">\(D\)</span> and <span class="math inline">\(Z\)</span> are not exactly the same because some individuals who were assigned to the treatment did not actually participate).</p>
<p>You are considering several different approaches to dealing with this issue. Discuss which of the following are good or bad ideas:</p>
<ol type="a">
<li><p>Estimating <span class="math inline">\(ATT\)</span> by <span class="math inline">\(\bar{Y}_{D=1} - \bar{Y}_{D=0}\)</span>.</p></li>
<li><p>Run the regression <span class="math inline">\(Y_i = \beta_0 + \alpha D_i + U_i\)</span> using <span class="math inline">\(Z_i\)</span> as an instrument.</p></li>
</ol></li>
<li><p>Suppose you and a friend have conducted an experiment (things went well so that everyone complied with the treatment that they were assigned to, etc.). You interpret the difference <span class="math inline">\(\bar{Y}_{D=1} - \bar{Y}_{D=0}\)</span> as an estimate of the <span class="math inline">\(ATT\)</span>, but your friend says that you should interpret it as an estimate of the <span class="math inline">\(ATE\)</span>. In fact, according to your friend, random treatment assignment implies that <span class="math inline">\(\E[Y(1)] = \E[Y(1)|D=1] = \E[Y|D=1]\)</span> and <span class="math inline">\(\E[Y(0)] = \E[Y(0)|D=0] = \E[Y|D=0]\)</span> which implies that <span class="math inline">\(ATE = \E[Y|D=1] - \E[Y|D=0]\)</span>. Who is right?</p></li>
</ol>
</section>
<section id="answers-to-some-extra-questions" class="level2" data-number="18.8">
<h2 data-number="18.8" class="anchored" data-anchor-id="answers-to-some-extra-questions"><span class="header-section-number">18.8</span> Answers to Some Extra Questions</h2>
<p><strong>Answer to Question 4</strong></p>
<p>The key condition is the parallel trends assumption that says that, in the absence of participating in the treatment, the <em>path</em> of outcomes that individuals in the treated group is the same, on average, as the path of outcomes that individuals in the untreated group actually experienced.</p>
<p><strong>Answer to Question 9</strong></p>
<ol type="a">
<li><p>When some individuals do not comply with their treatment assignment, this approach is probably not so great. In particular, notice that the comparison in this part of the problem is among individuals who <em>actually</em> participated in the treatment relative to those who didn’t (the latter group includes both those assigned not to participate in the treatment along with those assigned to participate in the treatment, but ultimately didn’t actually participate). This suggests that this approach would generally lead to biased estimates of the <span class="math inline">\(ATT\)</span>. In the particular context of job training, you can see this would not be such a good idea if, for example, the people who were assigned to the job training program but who did not participate tended to do this because they were able to find a job before the job training program started.</p></li>
<li><p>This approach is likely to be better. By construction, <span class="math inline">\(Z\)</span> is not correlated with <span class="math inline">\(U\)</span> (since <span class="math inline">\(Z\)</span> is randomly assigned). <span class="math inline">\(Z\)</span> is also likely to be positively correlated with <span class="math inline">\(Z\)</span> (in particular, this will be the case if being randomly assigned to treatment increases the probability of being treated). This implies that <span class="math inline">\(Z\)</span> is a valid instrument and should be able to deliver a reasonable estimate of the effect of participating in the treatment.</p></li>
</ol>
<p><strong>Answer to Question 10</strong></p>
<p>While your friend’s explanation is not technically wrong, it seems to me that you are more right than your friend. There is an important issue related to external validity here. The group of people that show up to participate in the experiment could be (and likely are) quite different from the general population. Interpreting the results of the experiment as being an <span class="math inline">\(ATE\)</span> (in the sense of across the entire population) is therefore likely to be incorrect — or at least would require extra assumptions and/or justifications. Interpreting them as an <span class="math inline">\(ATT\)</span> (i.e., as the effect among those who participated in the treatment) is still perfectly reasonable though.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./16-unconfoundedness.html" class="pagination-link" aria-label="Unconfoundedness">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Unconfoundedness</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>