{
  "hash": "51c10332715fc744c0d17131ea09abd4",
  "result": {
    "engine": "knitr",
    "markdown": "# Linear Regression\n\nIn this chapter, our interest will shift to conditional expectations, such as $\\E[Y|X_1,X_2,X_3]$ (I'll write $X_1$, $X_2$, and $X_3$ in a lot of examples in this chapter, but you can think of there being an arbitrary number of $X$'s).\n\nI'll refer to $Y$ as the **outcome**.  You might also sometimes heae it called the **dependent variable**.\n\nI'll refer to the $X$'s as either **covariates** or **regressors** or **characteristics**.  You might also hear them called **independent variables** sometimes.\n\nBefore we start to get into the details, let us first discuss why we're interested in conditional expectations.  First, if we are interested in *making predictions*, it will often be the case that the \"best\" prediction that one can make is the conditional expectation.  This should make sense to you --- if you want to make a reasonable prediction about what the outcome will be for a new observation that has characteristics $x_1$, $x_2$, and $x_3$, a good way to do it would be to predict that their outcome would be the same as the mean outcome in the population among those that have the same characteristics; that is, $\\E[Y|X_1=x_1, X_2=x_2, X_3=x_3]$.\n\nNext, in economics, we are often interested in how much some outcome of interest changes when a particular covariate changes, holding other covariates constants.  To give some examples, we might be interested in the average return of actively managed mutual funds relative to passively managed mutual funds conditional on investing in assets in the same class (e.g., large cap stocks or international bonds).  As another example, we might be interested in the effect of an increase in the amount of fertilizer on average crop yield but while holding constant the temperature and precipitation.\n\nHow much the outcome, $Y$, changes on average when one of the covariates, $X_1$, changes by 1 unit and holding other covariates constant is what we'll call the **partial effect** of $X_1$ on $Y$.  Suppose $X_1$ is binary, then it is given by\n\n$$\n  PE(x_2,x_3) = \\E[Y | X_1=1, X_2=x_2, X_3=x_3] - \\E[Y | X_1=0,X_2=x_2,X_3=x_3]\n$$\nNotice that the partial effect can depend on $x_2$ and $x_3$.  For example, it could be that the effect of active management relative to passive management could be different across different asset classes.\n\nSlightly more generally, if $X_1$ is discrete, so that it can take on several different discrete values, then we define the partial effect as\n\n$$\n  PE(x_1,x_2,x_3) = \\E[Y | X_1=x_1+1, X_2=x_2, X_3=x_3] - \\E[Y | X_1=x_1,X_2=x_2,X_3=x_3]\n$$\nwhich now can depend on $x_1$, $x_2$, and $x_3$.  This is the average effect of going from $X_1=x_1$ to $X_1=x_1+1$ holding $x_2$ and $x_3$ constant.  \n\nFinally, consider the case where we are interested in the partial effect of $X_1$ which is continuous (for example, the partial effect of fertilizer input on crop yield).  In this case the  partial effect is given by the *partial derivative* of $\\E[Y|X_1,X_2,X_3]$ with respect to $X_1$.\n\n$$\n  PE(x_1,x_2,x_3) = \\frac{\\partial \\, \\E[Y|X_1=x_1, X_2=x_2, X_3=x_3]}{\\partial \\, x_1}\n$$\nThis partial derivative is analogous to what we have been doing before --- we are making a small change of $X_1$ while holding $X_2$ and $X_3$ constant at $x_2$ and $x_3$.\n\n::: {.side-comment}\n\n<span class=\"side-comment\">Side-Comment:</span> This is probably the part of the class where we will jump around in the book the most this semester.  \n\nThe pedagogical approach of the textbook is to introduce the notion of causality very early and to emphasize the requirements on linear regression models in order to deliver causality, while increasing the complexity of the models over several chapters.\n\nThis is totally reasonable, but I prefer to start by teaching the mechanics of regressions: how to compute them, how to interpret them (even if you are not able to meet the requirements of causality), and how to use them to make predictions.  Then, we'll have a serious discussion about causality over the last few weeks of the semester.  \n\nIn practice, this means we'll cover parts Chapters 4-8 in the textbook now, and then we'll circle back to some of the issues covered in these chapters again towards the end of the semester.  \n\n:::\n\n## Nonparametric Regression / Curse of Dimensionality\n\nIf you knew nothing about regressions, it would seem natural to try to estimate $\\E[Y|X_1=x_1,X_2=x_2,X_3=x_3]$ by just calculating the average of $Y$ among observations that have values of the regressors equal to $x_1$, $x_2$, and $x_3$ (if these are discrete) or that are, in some sense, close to $x_1$, $x_2$, and $x_3$ (if these are continuous).\n\nThis is actually a pretty attractive idea.\n\nHowever, you run into the issue that it is practically challenging to do this when the number of regressors starts to get large (i.e., if you have 10 regressors, generally, you would need tons of data to be able to find a suitable number of observations that are \"close\" to any particular value of the regressors).  \n\nLet me give a more concrete example.  Suppose that you were trying to estimate mean house price as a function of a house's characteristics.  If the only characteristic of the house that you knew was the number of bedrooms, then it would be pretty easy to just calculate the average house price among houses with 2, 3, 4, etc. bedrooms.  Now suppose that you knew both the number of bedrooms and the number of square feet.  In this case, if we wanted to estimate mean house prices as a function of these characteristics, we would need to find houses that have the same number of bedrooms and (at least) a similar number of square feet.  This starts to \"slice\" the data that you have more thinly.  If you continue with this idea (suppose that you want to estimate mean house price as a function of number of bedrooms, number of bathrooms, number of square feet, what year the house was built in, whether or not it has a basement, what zip code it is located in, etc.) then you will start to stretch your data extremely thin to the point that you may have very few relevant observations (or perhaps no relevant observations) for particular values of the characteristics.  \n\nThis issue is called the \"curse of dimensionality\".\n\nWe will focus on linear models for $\\E[Y|X_1,X_2,X_3]$ largely to get around the curse of dimensionality.\n\n::: {.side-comment}\n\nThis idea of using observations that are very close in terms of characteristics in order to estimate a conditional expectation is called **nonparametric** econometrics/statistics. You can take entire courses (typically graduate-level) on this topic if you were interested. The reason that it is is called nonparametric is that it doesn't involve making any functional form assumptions (like linearity) but the cost is that it would typically require many more observations (due to the curse of dimensionality).\n\n:::\n\n## Linear Regression Models\n\nSW 4.1\n\nIn order to get around the curse of dimensionality that we discussed in the previous section, we will often an impose a **linear model** for the conditional expectation.  For example,\n\n$$\n  \\E[Y|X] = \\beta_0 + \\beta_1 X\n$$\nor\n\n$$\n  \\E[Y|X_1,X_2,X_3] = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\beta_3 X_3\n$$\nIf we know the values of $\\beta_0$, $\\beta_1$, $\\beta_2$, and $\\beta_3$, then it is straighforward for us to make predictions.  In particular, suppose that we want to predict the outcome for a new observation with characteristics $x_1$, $x_2$, and $x_3$.  Our prediction would be\n\n$$\n  \\beta_0 + \\beta_1 x_1 + \\beta_2 x_2 + \\beta_3 x_3\n$$\n\n::: {.example}\n\nSuppose that you are studying intergenerational income mobility and that you are interested in predicting a child's income whose parents' income was \\$50,000 and whose mother had 12 years of education.  Let $Y$ denote child's income, $X_1$ denote parents' income, and $X_2$ denote mother's education.  Further, suppose that $\\E[Y|X_1,X_2] = 20,000 + 0.5 X_1 + 1000 X_2$.  \n\nIn this case, you would predict child's income to be\n\n$$\n  20,000 + 0.5 (50,000) + 1000(12) = 57,000\n$$\n:::\n\n::: {.side-comment}\n\n<span class=\"side-comment\">Side-Comment:</span>\n\nThe above model can be equivalently written as\n\\begin{align*}\n  Y = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\beta_3 X_3 + U\n\\end{align*}\nwhere $U$ is called the **error term** and satisfies $\\E[U|X_1,X_2,X_3] = 0$.  There will be a few times where this formulation will be useful for us.\n\n:::\n\n## Computation\n\nEven if we know that $\\E[Y|X_1,X_2,X_3] = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\beta_3 X_3$, in general, we do not know the values of the population parameters (the $\\beta$'s).  This is analogous to the framework in the previous chapter where we were interested in \nthe population parameter $\\E[Y]$ and estimated it by $\\bar{Y}$.\n\nIn this section, we'll discuss how to estimate $(\\beta_0,\\beta_1,\\beta_2,\\beta_3)$ using `R`.  We'll refer to the estimated values of the parameters as $(\\hat{\\beta}_0, \\hat{\\beta}_1, \\hat{\\beta}_2, \\hat{\\beta}_3)$.  As in the previous section, it will not be the case that the estimated $\\hat{\\beta}$'s are exactly equal to the population $\\beta$'s.  Later on in this chapter, we will establish properties like consistency (so that, as long as we have a large sample, the estimated $\\hat{\\beta}$'s should be \"close\" to the population $\\beta$'s) and asymptotic normality (so that we can conduct inference).\n\nAlso later on in this chapter, we'll talk about how `R` itself actually makes these computations.\n\nThe main function in `R` for estimating linear regressions is the `lm` function (`lm` stands for linear model).  The key things to specify for running a regression in `R` are a `formula` argument which tells `lm` which variables are the outcome and which variables are the regressors and a `data` argument which tells the `lm` command what data we are using to estimate the regression.  Let's give an example using the `mtcars` data.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg <- lm(mpg ~ hp + wt, data=mtcars)\n```\n:::\n\n\n\n\n\n\nWhat this line of code does is to run a regression.  The formula is `mpg ~ hp + wt`.  In other words `mpg` (standing for miles per gallon) is the outcome, and we are running a regression on `hp` (horse power) and `wt` (weight).  The `~` symbol is a \"tilde\".  In order to add regressors, we separate them with a `+`.  The second argument `data=mtcars` says to use the `mtcars` data.  All of the variables in the formula need to correspond to column names in the data.  We saved the results of the regression in a variable called `reg`.  It's most common to report the results of the regression using the `summary` command.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(reg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mpg ~ hp + wt, data = mtcars)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-3.941 -1.600 -0.182  1.050  5.854 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 37.22727    1.59879  23.285  < 2e-16 ***\nhp          -0.03177    0.00903  -3.519  0.00145 ** \nwt          -3.87783    0.63273  -6.129 1.12e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.593 on 29 degrees of freedom\nMultiple R-squared:  0.8268,\tAdjusted R-squared:  0.8148 \nF-statistic: 69.21 on 2 and 29 DF,  p-value: 9.109e-12\n```\n\n\n:::\n:::\n\n\n\n\n\nThe main thing that this reports is the estimated parameters.  Our estimate of the \"Intercept\" (i.e., this is $\\hat{\\beta}_0$) is in the first row of the table; our estimate is `37.227`.  The estimated coefficient on `hp` is `-0.0318`, and the estimated coefficient on `wt` is `-3.878`.  \n\nYou can also see standard errors for each estimated parameter, a t-statistic, and a p-value in the other columns.  We will talk about these in more detail in the next section.  \n\nFor now, we'll also ignore the information provided at the bottom of the summary.\n\nNow that we have estimated the parameters, we can use these to predict $mpg$ given a value of $hp$ and $wt$.  For example, suppose that you wanted to predict the $mpg$ of a 2500 pound car (note: weight in $mtcars$ is in 1000s of pounds) and 120 horsepower car, you could compute\n\n$$\n  37.227 - 0.0318(120) - 3.878(2.5) = 23.716\n$$\nAlternatively, there is a built-in function in `R` called `predict` that can be used to generate predicted values.  We just need to specify the values that we would like to get predicted values for by passing in a data frame with the relevant columns though the `newdata` argument.  For example,\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred <- predict(reg, newdata=data.frame(hp=120,wt=2.5))\nround(pred,3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    1 \n23.72 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n:::  {.side-comment}\n\nA popular alternative to `R`'s `lm` function is the `lm_robust` function from the `estimatr` package.  This provides different standard errors from the default standard errors provided by `lm` that are, at least in most applications in economics, typically a better choice --- we'll have a further discussion on this topic when we talk about inference later on in this chapter.\n\n:::\n\n\n\n## Partial Effects\n\nAs we discussed in the beginning of this chapter, besides predicting outcomes, a second main goal for us is to think about partial effects of a regressor on the outcome.  We'll consider partial effects over the next few sections.\n\nIn the model, \n\\begin{align*}\n  \\E[Y | X_1, X_2, X_3]  &= \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\beta_3 X_3\n\\end{align*}\n\nIf $X_1$ is continuous, then \n\\begin{align*}\n  \\beta_1 = \\frac{\\partial \\E[Y|X_1,X_2,X_3]}{\\partial X_1}\n\\end{align*}\n\nThus, $\\beta_1$ is the partial effect of $X_1$ on $Y$.    In other words, $\\beta_1$ should be interpreted as how much $Y$ increases, on average, when $X_1$ increases by one unit holding $X_2$ and $X_3$ constant.  *Make sure to get this interpretation right!*\n\n\n::: {.example}\n\nContinuing the same example as above about intergenerational income mobility and where $Y$ denotes child's income, $X_1$ denotes parents' income, $X_2$ denotes mother's education, and \n\n$$\n  \\E[Y|X_1,X_2] = 20,000 + 0.5 X_1 + 1000 X_2\n$$\nThe partial effect of parents' income on child's income is 0.5.  This means that, for every one dollar increase in parents' income, child's income is 0.5 dollars higher on average holding mother's education constant.\n\n:::\n\n### Computation\n\nLet's run the same regression as in the previous section, but think about partial effects in this case.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg1 <- lm(mpg ~ hp + wt, data=mtcars)\nsummary(reg1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mpg ~ hp + wt, data = mtcars)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-3.941 -1.600 -0.182  1.050  5.854 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 37.22727    1.59879  23.285  < 2e-16 ***\nhp          -0.03177    0.00903  -3.519  0.00145 ** \nwt          -3.87783    0.63273  -6.129 1.12e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.593 on 29 degrees of freedom\nMultiple R-squared:  0.8268,\tAdjusted R-squared:  0.8148 \nF-statistic: 69.21 on 2 and 29 DF,  p-value: 9.109e-12\n```\n\n\n:::\n:::\n\n\n\n\n\n\nThe partial effect of horsepower on miles per gallon is -0.032.  In other words, we estimate that if horsepower increases by one then, on average, miles per gallon decreases by 0.032 holding weight constant.  \n\nThe t-statistic and p-value are computed for the null hypothesis that the corresponding coefficient is equal to 0.  For example, for `hp` the t-statistic is equal to `-3.519` which is greater than 1.96 and indicates that the partial effect of `hp` is statistically significant at a 5% significance level.  The corresponding p-value for `hp` is `0.0145` indicating that there is only about a 1.5% chance of getting a t-statistic this extreme if the partial effect of `hp` were actually 0 (i.e., under $H_0 : \\beta_1=0$).\n\n::: {.practice}\n\n<span class=\"practice\">Practice: </span>What is the partial effect of `wt` in the previous example?  Provide a careful interpretation.  Is the partial effect of `wt` statistically significant?  Explain.  What is the p-value for `wt`?  How do you interpret the p-value?\n\n:::\n\n::: {.side-comment}\n\n<span class=\"side-comment\">Side-Comment:</span> One horsepower is a very small increase in horsepower, so it might be a good idea to multiply the coefficient by some larger number, say 50.  In this case, we could say that we estimate that if horsepower increases by 50 then, on average, miles per gallon decreases by 1.59 ($=50 \\times 0.03177$) holding weight constant.  From the above discussion, we know that this effect is statistically different from 0.  That said, it is not clear to me if we should interpret this as a large partial effect; I do not know too much about cars, but a 50 horsepower increase seems rather large while a 1.59 decrease in miles per gallon seems relatively small (at least to me).\n\n:::\n\n## Binary Regressors\n\nSW 5.3\n\nLet's continue with the same model as above\n\n$$\n  \\E[Y|X_1,X_2,X_3] = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\beta_3 X_3\n$$\n\nIf $X_1$ is discrete (let's say binary):\n\\begin{align*}\n  \\beta_1 = \\E[Y|X_1=1,X_2,X_3] - \\E[Y|X_1=0,X_2,X_3]\n\\end{align*}\n$\\beta_1$ is still the partial effect of $X_1$ on $Y$ and should be interpreted as how much $Y$ increases, on average, when $X_1$ changes from 0 to 1, holding $X_2$ and $X_3$ constant.\n\nIf $X_1$ can take more than just the values 0 and 1, but is still discrete (an example is a person's years of education), then \n\n$$\n  \\beta_1 = \\E[Y | X_1=x_1+1, X_2, X_3] - \\E[Y|X_1=x_1, X_2, X_3]\n$$\nwhich holds for any possible value that $X_1$ could take, so that $\\beta_1$ is the effect of a 1 unit increase in $X_1$ on $Y$, on average, holding constant $X_2$ and $X_3$.\n\n::: {.example}\n\nSuppose that you work for an airline and you are interested in predicting the number of passengers for a Saturday morning flight from Atlanta to Memphis.  Let $Y$ denote the number of passengers, $X_1$ be equal to 1 for a morning flight and 0 otherwise, and let $X_2$ be equal to 1 for a weekday flight and 0 otherwise.  Further suppose that $\\E[Y|X_1,X_2] = 80 + 20 X_1 - 15 X_2$.  \n\nIn this case, you would predict,\n\n$$\n  80 + 20 (1) - 15 (0) = 100\n$$\npassengers on the flight.\n\nIn addition, the partial effect of being morning flight is equal to 20.  This indicates that, on average, morning flights have 20 more passengers than non-morning flights holding whether or not the flight occurs on a weekday constant.\n\n:::\n\n### Computation\n\nIn order to include a binary or discrete covariate in a regression in `R` is straightforward.  The following regression uses the `mtcars` data and adds a binary regressor, `am`, indicating whether or not a car has an automatic transmission.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg2 <- lm(mpg ~ hp + wt + am, data=mtcars)\nsummary(reg2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mpg ~ hp + wt + am, data = mtcars)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.4221 -1.7924 -0.3788  1.2249  5.5317 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 34.002875   2.642659  12.867 2.82e-13 ***\nhp          -0.037479   0.009605  -3.902 0.000546 ***\nwt          -2.878575   0.904971  -3.181 0.003574 ** \nam           2.083710   1.376420   1.514 0.141268    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.538 on 28 degrees of freedom\nMultiple R-squared:  0.8399,\tAdjusted R-squared:  0.8227 \nF-statistic: 48.96 on 3 and 28 DF,  p-value: 2.908e-11\n```\n\n\n:::\n:::\n\n\n\n\n\n\nIn this example, cars that had an automatic transmission got about 2 more miles per gallon than cars that had an automatic transmission on average, holding horsepower and weight constant (though the p-value is only 0.14).\n\n\n\n## Nonlinear Regression Functions\n\nSW 8.1, 8.2\n\nAlso, please read all of SW Ch. 8\n\nSo far, the the partial effects that we have been interested in have corresponded to a particular parameter in the regression, usually $\\beta_1$.  I think this can sometimes be a source of confusion as, at least in my view, we are not typically interested in the parameters for their own sake, but rather are interested in partial effects.  It just so happens that in some leading cases, they coincide.\n\nIn addition, while the $\\beta$'s in the sort of models we have considered so far are easy to interpret, in some cases, it might be *restrictive* to think that the partial effects are the same across different values of the covariates.\n\nIn this section, we'll see the first of several cases where partial effects do not coincide with a particular parameter.\n\nSuppose that\n\n$$ \n  \\E[Y|X_1,X_2,X_3] = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_1^2 + \\beta_3 X_2 + \\beta_4 X_3\n$$\n\nLet's start with making predictions using this model.  If you know the values of $\\beta_0,\\beta_1,\\beta_2,\\beta_3,$ and $\\beta_4$, then to get a prediction, you would still just plug in the values of the regressors that you'd like to get a prediction for (including $x_1^2$).  \n\nNext, in this model, the partial effect of $X_1$ is given by\n\n$$\n  \\frac{\\partial \\, \\E[Y|X_1,X_2,X_3]}{\\partial \\, X_1} = \\beta_1 + 2\\beta_2 X_1\n$$\nIn other words, the partial effect of $X_1$ depends on the value that $X_1$ takes.  \n\nIn this case, it is sometimes useful to report the partial effect for some different values of $X_1$.  In other cases, it is useful to report the **average partial effect** (APE) which is the mean of the partial effects across the distribution of the covariates. In this case, the APE is given by\n\n$$\n  APE = \\beta_1 + 2 \\beta_2 \\E[X_1]\n$$\nand, once you have estimated the regression, you can compute an estimate of $APE$ by\n\n$$\n  \\widehat{APE} = \\hat{\\beta}_1 + 2 \\hat{\\beta}_2 \\bar{X}_1\n$$\n\n::: {.example}\n\nLet's continue our example on intergenerational income mobility where $Y$ denotes child's income, $X_1$ denotes parents' income, and $X_2$ denotes mother's education.  Now, suppose that\n\n$$\n  \\E[Y|X_1,X_2] = 15,000 + 0.7 X_1 - 0.000002 X_1^2 + 800 X_2\n$$\nThen, predicted child's income when parents' income is equal to \\$50,000 is given by\n\n$$\n  15,000 + 0.7 (50,000) - 0.000002 (50,000)^2 + 800 (12) = 54,600\n$$\nIn addition, the partial effect of parents' income is given by\n\n$$\n  0.7 - 0.000004 X_1 \n$$\nLet's compute a few different partial effects for different values of parents' income\n\n| $X_1$ | PE |\n|:-------------:|:-------------:|\n| 20,000 | 0.62 |\n| 50,000 | 0.50 | \n| 100,000 | 0.30 | \n\nwhich indicates that the partial effect of parents' income is decreasing --- i.e., the effect of additional parents' income is largest for children whose parents have the lowest income and gets smaller for those whose parents have high incomes.\n\nFinally, if you wanted to compute the $APE$, you would just plug in $\\E[X_1]$ (or $\\bar{X}_1$) into the expression for the partial effect.\n\n:::\n\n### Computation\n\nIncluding a quadratic (or other higher order term) in `R` is relatively straightforward.  Let's just do an example.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg3 <- lm(mpg ~ hp + I(hp^2), data=mtcars)\nsummary(reg3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mpg ~ hp + I(hp^2), data = mtcars)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4.5512 -1.6027 -0.6977  1.5509  8.7213 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  4.041e+01  2.741e+00  14.744 5.23e-15 ***\nhp          -2.133e-01  3.488e-02  -6.115 1.16e-06 ***\nI(hp^2)      4.208e-04  9.844e-05   4.275 0.000189 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.077 on 29 degrees of freedom\nMultiple R-squared:  0.7561,\tAdjusted R-squared:  0.7393 \nF-statistic: 44.95 on 2 and 29 DF,  p-value: 1.301e-09\n```\n\n\n:::\n:::\n\n\n\n\n\nThe only thing that is new here is `I(hp^2)`.  The `I` function stands for inhibit (you can read the documentation using `?I`).  For us, this is not too important.  You can understand it like this: there is no variable names `hp^2` in the data, but if we put the name of a variable that is in the data (here: `hp`) then we can apply a function to it (here: squaring it) before including it as a regressor.\n\nInterestingly, here it seems there are nonlinear effects of horsepower on miles per gallon.  Let's just quickly report the estimated partial effects for a few different values of horsepower.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhp_vec <- c(100,200,300)\n# there might be a native function in r\n# to compute these partial effects; I just\n# don't know it.\npe <- function(hp) {\n  # partial effect is b1 + 2b2*hp\n  pes <- coef(reg3)[2] + 2*coef(reg3)[3]*hp\n  # print using a data frame\n  data.frame(hp=hp, pe=round(pes,3))\n}\npe(hp_vec)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   hp     pe\n1 100 -0.129\n2 200 -0.045\n3 300  0.039\n```\n\n\n:::\n:::\n\n\n\n\n\nwhich suggests that the partial effect of horsepower on miles per gallon is large (though negative) at small values of horsepower and decreasing up to essentially no effect at larger values of horsepower.\n\n## Interpreting Interaction Terms\n\nSW 8.3\n\nAnother way to allow for partial effects that vary across different values of the regressors is to include **interaction terms**.\n\nConsider the following regression model\n\n$$\n  \\E[Y|X_1,X_2,X_3] = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\beta_3 X_1 X_2 + \\beta_4 X_3\n$$\n\nThe term $X_1 X_2$ is called the interaction term.  In this model, the partial effect of $X_1$ is given by\n\n$$\n  \\frac{\\partial \\, \\E[Y|X_1,X_2,X_3]}{\\partial \\, X_1} = \\beta_1 + \\beta_3 X_2\n$$\n\nIn this model, the effect of $X_1$ varies with $X_2$.  As in the previous section, you could report the partial effect for different values of $X_2$ or consider $APE = \\beta_1 + \\beta_3 \\E[X_2]$.\n\nThere are a couple of other things worth pointing out for interaction terms\n\n- It is very common for one of the interaction terms, say, $X_2$ to be a binary variable.  This gives a way to easily test if the effect of $X_1$ is the same across the two \"groups\" defined by $X_2$.  For example, suppose you wanted to check if the partial effect of education was the same for men and women.  You could run a regression like\n\n    $$\n      Wage = \\beta_0 + \\beta_1 Education + \\beta_2 Female + \\beta_3 Education \\cdot Female + U\n    $$\n\n    From the previous discussion, the partial effect of education is given by\n\n    $$\n      \\beta_1 + \\beta_3 Female\n    $$\n\n    Thus, the partial effect education for men is given by $\\beta_1$, and the partial effect of education for women is given by $\\beta_1 + \\beta_3$.  Thus, if you want to test if the partial effect of education differs for men and women, you can just test if $\\beta_3=0$.  If $\\beta_3>0$, it suggests a higher partial effect of education for women, and if $\\beta_3 < 0$, it suggests a lower partial effect of education for women.\n\n- Another interesting case is when $X_1$ and $X_2$ are both binary.  In this case, a model that includes an interaction term is called a **saturated model**.  It is called this because it is actually nonparametric.  In particular, notice that in the model $\\E[Y|X_1,X_2] = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\beta_3 X_1 X_2$,\n\n    $$\n    \\begin{aligned}\n      \\E[Y|X_1=0,X_2=0] &= \\beta_0 \\\\\n      \\E[Y|X_1=1,X_2=0] &= \\beta_0 + \\beta_1 \\\\\n      \\E[Y|X_1=0,X_2=1] &= \\beta_0 + \\beta_2 \\\\\n      \\E[Y|X_1=1,X_2=1] &= \\beta_0 + \\beta_1 + \\beta_2 + \\beta_3\n    \\end{aligned}\n    $$\n    \n    This exhausts all possible combinations of the regressors and means that you can recover each possible value of the conditional expectation from the parameters of the model.\n    \n    It would be possible to write down a saturated model in cases with more than two binary regressors (or even discrete regressors) --- you would just need to include more interaction terms.  The key thing is that there be no continuous regressors.  That said, as you start to add more and more discrete regressors and their interactions, you will effectively start to run into the curse of dimensionality issues that we discussed earlier.\n    \n    As an example, consider our earlier example of flights from Atlanta to Memphis where $Y$ denoted the number of passengers, $X_1$ was equal to 1 for a a morning flight and 0 otherwise, and $X_2$ was equal to one for a weekday flight and 0 otherwise.  Suppose that $\\E[Y|X_1,X_2] = 90 - 15 X_1 - 5 X_2 + 25 X_1 X_2$.  Then, \n    \n    $$\n    \\begin{aligned}\n      \\E[Y|X_1=0,X_2=0] &= 90 \\quad & \\textrm{non-morning, weekend} \\\\\n      \\E[Y|X_1=1,X_2=0] &= 90 - 15 = 75 \\quad & \\textrm{morning, weekend} \\\\\n      \\E[Y|X_1=0,X_2=1] &= 90 - 5 = 85 \\quad  & \\textrm{non-morning, weekday} \\\\\n      \\E[Y|X_1=1,X_2=1] &= 90 - 15 - 5 + 25 = 100 \\quad & \\textrm{morning, weekend}\n    \\end{aligned}\n    $$\n\n### Computation\n\nIncluding interaction terms in regressions in `R` is straightforward.  Using the `mtcars` data, we can do it as follows\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg4 <- lm(mpg ~ hp + wt + am + hp*am, data=mtcars)\nsummary(reg4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mpg ~ hp + wt + am + hp * am, data = mtcars)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-3.435 -1.510 -0.697  1.284  5.245 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 33.34196    2.79711  11.920 2.89e-12 ***\nhp          -0.02918    0.01449  -2.014  0.05407 .  \nwt          -3.05617    0.94036  -3.250  0.00309 ** \nam           3.55141    2.35742   1.506  0.14355    \nhp:am       -0.01129    0.01466  -0.770  0.44809    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.556 on 27 degrees of freedom\nMultiple R-squared:  0.8433,\tAdjusted R-squared:  0.8201 \nF-statistic: 36.33 on 4 and 27 DF,  p-value: 1.68e-10\n```\n\n\n:::\n:::\n\n\n\n\n\n\nThe interaction term in the results is in the row that starts with `hp:am`.  These estimates suggest that, while horsepower does seem to decrease miles per gallon controlling for weight and whether or not the car has an automatic transmission, the effect of horsepower does not seem to vary much by whether or not the car has an automatic transmission (at least not in a big enough way that we can detect it with the data that we have).  \n\n## Elasticities\n\nSW 8.2\n\nEconomists are often interested in **elasticities**, that is, the percentage change in $Y$ when $X$ changes by 1%.\n\nRecall that the definition of percentage change of moving from, say, $x_{old}$ to $x_{new}$ is given by\n\n$$\n  \\textrm{\\% change} = \\frac{x_{new} - x_{old}}{x_{old}} \\times 100\n$$\n\nElasticities are closely connected to natural logarithms; following the most common notation in economics, we'll refer to the natural logarithm using the notation: $\\log$.  Further, recall that the derivative of the $\\log$ function is given by\n\n$$\n  \\frac{d \\, \\log(x)}{d \\, x} = \\frac{1}{x} \\implies d\\, \\log(x) = \\frac{d \\, x}{x}\n$$\nwhich further implies that\n\n$$\n  \\Delta \\log(x) := \\log(x_{new}) - \\log(x_{old}) \\approx \\frac{x_{new} - x_{old}}{x_{old}}\n$$\nand, thus, that\n\n$$\n  100 \\cdot \\Delta \\log(x) \\approx \\textrm{\\% change}\n$$ \nwhere the approximation is better when $x_{new}$ and $x_{old}$ are close to each other.\n\nNow, we'll use these properties of logarithms in order to interpret several linear models \n\n- For simplicity, I am going to not include an error term or extra covariates, but you should continue to interpret parameter estimates as \"on average\" and \"holding other regressors constant\" (if there are other regressors in the model).\n\n- **Log-Log** Model\n\n    $$\n    \\log(Y) = \\beta_0 + \\beta_1 \\log(X)\n    $$\n    \n    In this case, \n    \n    $$\n    \\begin{aligned}\n    \\beta_1 &= \\frac{ d \\, \\log(Y) }{d \\, \\log(X)} \\\\\n    &= \\frac{ d \\, \\log(Y) \\cdot 100 }{d \\, \\log(X) \\cdot 100} \\\\\n    &\\approx \\frac{ \\% \\Delta Y}{ \\% \\Delta X}\n    \\end{aligned}\n    $$\n    \n    All that to say, in a regression of the log of an outcome on the log of a regressor, you should interpret the corresponding coefficient as the average percentage change in the outcome when the regressor changes by 1%.  The log-log model is sometimes called a **constant elasticity** model.\n    \n- **Log-Level** model\n\n    $$\n    \\log(Y) = \\beta_0 + \\beta_1 X\n    $$\n    \n    In this case, \n    \n    $$\n    \\begin{aligned}\n    \\beta_1 &= \\frac{ d \\, \\log(Y) }{d \\, X} \\\\\n    \\implies 100 \\beta_1 &= \\frac{ d \\, \\log(Y) \\cdot 100 }{d \\, X} \\\\\n    \\implies 100 \\beta_1 &\\approx \\frac{ \\% \\Delta Y}{ d \\, X}\n    \\end{aligned}\n    $$\n    \n    Thus, in a regression of the log of an outcome on the *level* of a regressor, you should multiply the corresponding coefficient by 100 and interpret it as the average percentage change in the outcome when the regressor changes by 1 unit.\n    \n- **Level-Log** model\n\n    $$\n      Y = \\beta_0 + \\beta_1 \\log(X)\n    $$\n    \n    In this case,\n    \n    $$\n      \\begin{aligned}\n      \\beta_1 &= \\frac{d\\, Y}{d \\, \\log(X)} \\\\\n      \\implies \\frac{\\beta_1}{100} &= \\frac{d \\, Y}{d \\, \\log(X) \\cdot 100} \\\\\n      \\implies \\frac{\\beta_1}{100} &\\approx \\frac{d \\, Y}{\\% \\Delta X}\n      \\end{aligned}\n    $$\n    \n    Thus, in a regression of the level of an outcome on the log of a regressor, you should divide the corresponding coefficient by 100 and interpret it as the average change in the outcome when the regressor changes by 1%.\n    \n::: {.example}\n  \nLet's continue the same example on intergenerational income mobility where $Y$ denotes child's income, $X_1$ denotes parents' income and $X_2$ denotes mother's education.  We'll consider how to interpret several different models.\n\n$$\n  \\log(Y) = 8.8 + 0.4 \\log(X_1) + 0.008 X_2 + U\n$$\nIn this model, we estimate that, on average, when parents' income increases by 1%, child's income increases by 0.4% holding mother's education constant.\n\nNext, consider, \n$$\n  \\log(Y) = 8.9 + 0.00004 X_1 + 0.007 X_2 + U\n$$\nIn this model, we estimate that, on average, when parents' income increases by \\$1, child's income increases by 0.004% (alternatively, when parents' income increase by \\$1000, child's income increases by 4%) holding mother's education constant.\n\nFinally, consider\n\n$$\n  Y = -1,680,000 + 160,000 \\log(X_1) + 900 X_2 + U\n$$\nIn this case, we estimate that, on average, when parents' income increases by 1%, child's income increases by \\$1,600 holding mother's education constant.\n\n:::\n\n### Computation\n\nEstimating models that include logarithms in `R` is straightforward.  \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg5 <- lm(log(mpg) ~ log(hp) + wt, data=mtcars) \nreg6 <- lm(log(mpg) ~ hp + wt, data=mtcars) \nreg7 <- lm(mpg ~ log(hp) + wt, data=mtcars)\n```\n:::\n\n\n\n\n\n\nLet's show the results all at once using the `modelsummary` function from the `modelsummary` package.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(modelsummary)\n\nmodel_list <- list(reg5, reg6, reg7)\nmodelsummary(model_list)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!DOCTYPE html> \n<html lang=\"en\">\n  <head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <title>tinytable_qarhtayi3x7psxx2gynw</title>\n    <style>\n.table td.tinytable_css_4oioc82l7621a6zd74gf, .table th.tinytable_css_4oioc82l7621a6zd74gf {    border-bottom: solid 0.1em #d3d8dc; }\n.table td.tinytable_css_k07csoe7567cki4t3uyd, .table th.tinytable_css_k07csoe7567cki4t3uyd {    text-align: left; }\n.table td.tinytable_css_sukx4bd5q8p4sw050gv5, .table th.tinytable_css_sukx4bd5q8p4sw050gv5 {    text-align: center; }\n.table td.tinytable_css_u23oqw30052ecusyjogc, .table th.tinytable_css_u23oqw30052ecusyjogc {    text-align: center; }\n.table td.tinytable_css_urkdm2zqe87sojsywx8x, .table th.tinytable_css_urkdm2zqe87sojsywx8x {    text-align: center; }\n.table td.tinytable_css_c2zscdufr3m2m7rfuh0z, .table th.tinytable_css_c2zscdufr3m2m7rfuh0z {    border-bottom: solid 0.05em black; }\n    </style>\n    <script src=\"https://polyfill.io/v3/polyfill.min.js?features=es6\"></script>\n    <script id=\"MathJax-script\" async src=\"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"></script>\n    <script>\n    MathJax = {\n      tex: {\n        inlineMath: [['$', '$'], ['\\\\(', '\\\\)']]\n      },\n      svg: {\n        fontCache: 'global'\n      }\n    };\n    </script>\n  </head>\n\n  <body>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_qarhtayi3x7psxx2gynw\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\"> </th>\n                <th scope=\"col\">(1)</th>\n                <th scope=\"col\">(2)</th>\n                <th scope=\"col\">(3)</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td>(Intercept)</td>\n                  <td>4.832  </td>\n                  <td>3.829  </td>\n                  <td>59.571 </td>\n                </tr>\n                <tr>\n                  <td>           </td>\n                  <td>(0.222)</td>\n                  <td>(0.069)</td>\n                  <td>(4.977)</td>\n                </tr>\n                <tr>\n                  <td>log(hp)    </td>\n                  <td>-0.266 </td>\n                  <td>       </td>\n                  <td>-5.922 </td>\n                </tr>\n                <tr>\n                  <td>           </td>\n                  <td>(0.056)</td>\n                  <td>       </td>\n                  <td>(1.266)</td>\n                </tr>\n                <tr>\n                  <td>wt         </td>\n                  <td>-0.179 </td>\n                  <td>-0.201 </td>\n                  <td>-3.286 </td>\n                </tr>\n                <tr>\n                  <td>           </td>\n                  <td>(0.027)</td>\n                  <td>(0.027)</td>\n                  <td>(0.615)</td>\n                </tr>\n                <tr>\n                  <td>hp         </td>\n                  <td>       </td>\n                  <td>-0.002 </td>\n                  <td>       </td>\n                </tr>\n                <tr>\n                  <td>           </td>\n                  <td>       </td>\n                  <td>(0.000)</td>\n                  <td>       </td>\n                </tr>\n                <tr>\n                  <td>Num.Obs.   </td>\n                  <td>32     </td>\n                  <td>32     </td>\n                  <td>32     </td>\n                </tr>\n                <tr>\n                  <td>R2         </td>\n                  <td>0.885  </td>\n                  <td>0.869  </td>\n                  <td>0.859  </td>\n                </tr>\n                <tr>\n                  <td>R2 Adj.    </td>\n                  <td>0.877  </td>\n                  <td>0.860  </td>\n                  <td>0.849  </td>\n                </tr>\n                <tr>\n                  <td>AIC        </td>\n                  <td>140.3  </td>\n                  <td>144.5  </td>\n                  <td>150.0  </td>\n                </tr>\n                <tr>\n                  <td>BIC        </td>\n                  <td>146.1  </td>\n                  <td>150.4  </td>\n                  <td>155.9  </td>\n                </tr>\n                <tr>\n                  <td>Log.Lik.   </td>\n                  <td>28.501 </td>\n                  <td>26.395 </td>\n                  <td>-71.017</td>\n                </tr>\n                <tr>\n                  <td>F          </td>\n                  <td>111.812</td>\n                  <td>96.232 </td>\n                  <td>88.442 </td>\n                </tr>\n                <tr>\n                  <td>RMSE       </td>\n                  <td>0.10   </td>\n                  <td>0.11   </td>\n                  <td>2.23   </td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n\n    <script>\n      function styleCell_tinytable_hulrfnx6e1xlc8ydipm0(i, j, css_id) {\n        var table = document.getElementById(\"tinytable_qarhtayi3x7psxx2gynw\");\n        table.rows[i].cells[j].classList.add(css_id);\n      }\n      function insertSpanRow(i, colspan, content) {\n        var table = document.getElementById('tinytable_qarhtayi3x7psxx2gynw');\n        var newRow = table.insertRow(i);\n        var newCell = newRow.insertCell(0);\n        newCell.setAttribute(\"colspan\", colspan);\n        // newCell.innerText = content;\n        // this may be unsafe, but innerText does not interpret <br>\n        newCell.innerHTML = content;\n      }\n      function spanCell_tinytable_hulrfnx6e1xlc8ydipm0(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_qarhtayi3x7psxx2gynw\");\n        const targetRow = table.rows[i];\n        const targetCell = targetRow.cells[j];\n        for (let r = 0; r < rowspan; r++) {\n          // Only start deleting cells to the right for the first row (r == 0)\n          if (r === 0) {\n            // Delete cells to the right of the target cell in the first row\n            for (let c = colspan - 1; c > 0; c--) {\n              if (table.rows[i + r].cells[j + c]) {\n                table.rows[i + r].deleteCell(j + c);\n              }\n            }\n          }\n          // For rows below the first, delete starting from the target column\n          if (r > 0) {\n            for (let c = colspan - 1; c >= 0; c--) {\n              if (table.rows[i + r] && table.rows[i + r].cells[j]) {\n                table.rows[i + r].deleteCell(j);\n              }\n            }\n          }\n        }\n        // Set rowspan and colspan of the target cell\n        targetCell.rowSpan = rowspan;\n        targetCell.colSpan = colspan;\n      }\n\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(0, 0, 'tinytable_css_4oioc82l7621a6zd74gf') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(0, 1, 'tinytable_css_4oioc82l7621a6zd74gf') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(0, 2, 'tinytable_css_4oioc82l7621a6zd74gf') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(0, 3, 'tinytable_css_4oioc82l7621a6zd74gf') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(0, 0, 'tinytable_css_k07csoe7567cki4t3uyd') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(1, 0, 'tinytable_css_k07csoe7567cki4t3uyd') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(2, 0, 'tinytable_css_k07csoe7567cki4t3uyd') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(3, 0, 'tinytable_css_k07csoe7567cki4t3uyd') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(4, 0, 'tinytable_css_k07csoe7567cki4t3uyd') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(5, 0, 'tinytable_css_k07csoe7567cki4t3uyd') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(6, 0, 'tinytable_css_k07csoe7567cki4t3uyd') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(7, 0, 'tinytable_css_k07csoe7567cki4t3uyd') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(8, 0, 'tinytable_css_k07csoe7567cki4t3uyd') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(9, 0, 'tinytable_css_k07csoe7567cki4t3uyd') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(10, 0, 'tinytable_css_k07csoe7567cki4t3uyd') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(11, 0, 'tinytable_css_k07csoe7567cki4t3uyd') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(12, 0, 'tinytable_css_k07csoe7567cki4t3uyd') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(13, 0, 'tinytable_css_k07csoe7567cki4t3uyd') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(14, 0, 'tinytable_css_k07csoe7567cki4t3uyd') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(15, 0, 'tinytable_css_k07csoe7567cki4t3uyd') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(16, 0, 'tinytable_css_k07csoe7567cki4t3uyd') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(0, 1, 'tinytable_css_sukx4bd5q8p4sw050gv5') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(1, 1, 'tinytable_css_sukx4bd5q8p4sw050gv5') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(2, 1, 'tinytable_css_sukx4bd5q8p4sw050gv5') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(3, 1, 'tinytable_css_sukx4bd5q8p4sw050gv5') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(4, 1, 'tinytable_css_sukx4bd5q8p4sw050gv5') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(5, 1, 'tinytable_css_sukx4bd5q8p4sw050gv5') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(6, 1, 'tinytable_css_sukx4bd5q8p4sw050gv5') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(7, 1, 'tinytable_css_sukx4bd5q8p4sw050gv5') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(8, 1, 'tinytable_css_sukx4bd5q8p4sw050gv5') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(9, 1, 'tinytable_css_sukx4bd5q8p4sw050gv5') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(10, 1, 'tinytable_css_sukx4bd5q8p4sw050gv5') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(11, 1, 'tinytable_css_sukx4bd5q8p4sw050gv5') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(12, 1, 'tinytable_css_sukx4bd5q8p4sw050gv5') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(13, 1, 'tinytable_css_sukx4bd5q8p4sw050gv5') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(14, 1, 'tinytable_css_sukx4bd5q8p4sw050gv5') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(15, 1, 'tinytable_css_sukx4bd5q8p4sw050gv5') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(16, 1, 'tinytable_css_sukx4bd5q8p4sw050gv5') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(0, 2, 'tinytable_css_u23oqw30052ecusyjogc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(1, 2, 'tinytable_css_u23oqw30052ecusyjogc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(2, 2, 'tinytable_css_u23oqw30052ecusyjogc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(3, 2, 'tinytable_css_u23oqw30052ecusyjogc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(4, 2, 'tinytable_css_u23oqw30052ecusyjogc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(5, 2, 'tinytable_css_u23oqw30052ecusyjogc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(6, 2, 'tinytable_css_u23oqw30052ecusyjogc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(7, 2, 'tinytable_css_u23oqw30052ecusyjogc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(8, 2, 'tinytable_css_u23oqw30052ecusyjogc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(9, 2, 'tinytable_css_u23oqw30052ecusyjogc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(10, 2, 'tinytable_css_u23oqw30052ecusyjogc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(11, 2, 'tinytable_css_u23oqw30052ecusyjogc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(12, 2, 'tinytable_css_u23oqw30052ecusyjogc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(13, 2, 'tinytable_css_u23oqw30052ecusyjogc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(14, 2, 'tinytable_css_u23oqw30052ecusyjogc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(15, 2, 'tinytable_css_u23oqw30052ecusyjogc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(16, 2, 'tinytable_css_u23oqw30052ecusyjogc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(0, 3, 'tinytable_css_urkdm2zqe87sojsywx8x') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(1, 3, 'tinytable_css_urkdm2zqe87sojsywx8x') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(2, 3, 'tinytable_css_urkdm2zqe87sojsywx8x') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(3, 3, 'tinytable_css_urkdm2zqe87sojsywx8x') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(4, 3, 'tinytable_css_urkdm2zqe87sojsywx8x') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(5, 3, 'tinytable_css_urkdm2zqe87sojsywx8x') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(6, 3, 'tinytable_css_urkdm2zqe87sojsywx8x') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(7, 3, 'tinytable_css_urkdm2zqe87sojsywx8x') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(8, 3, 'tinytable_css_urkdm2zqe87sojsywx8x') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(9, 3, 'tinytable_css_urkdm2zqe87sojsywx8x') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(10, 3, 'tinytable_css_urkdm2zqe87sojsywx8x') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(11, 3, 'tinytable_css_urkdm2zqe87sojsywx8x') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(12, 3, 'tinytable_css_urkdm2zqe87sojsywx8x') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(13, 3, 'tinytable_css_urkdm2zqe87sojsywx8x') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(14, 3, 'tinytable_css_urkdm2zqe87sojsywx8x') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(15, 3, 'tinytable_css_urkdm2zqe87sojsywx8x') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(16, 3, 'tinytable_css_urkdm2zqe87sojsywx8x') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(8, 0, 'tinytable_css_c2zscdufr3m2m7rfuh0z') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(8, 1, 'tinytable_css_c2zscdufr3m2m7rfuh0z') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(8, 2, 'tinytable_css_c2zscdufr3m2m7rfuh0z') })\nwindow.addEventListener('load', function () { styleCell_tinytable_hulrfnx6e1xlc8ydipm0(8, 3, 'tinytable_css_c2zscdufr3m2m7rfuh0z') })\n    </script>\n\n  </body>\n\n</html>\n```\n\n:::\n:::\n\n\n\n\n\n- In the first model, we estimate that, on average, a 1% increase in horsepower decreases miles per gallon by 0.266% holding weight constant.  \n\n- In the second model, we estimate that, on average,  a 1 unit increase in horsepower decreases miles per gallon by 0.2% holding weight constant.  \n\n- In the third model, we estimate that, on average, a 1% increase in horsepower decreases miles per gallon by .059 holding weight constant.\n  \n\n\n## Omitted Variable Bias\n\nSW 6.1\n\nSuppose that we are interested in the following regression model\n\n$$\n  \\E[Y|X_1, X_2, Q] = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\beta_3 Q\n$$\nand, in particular, we are interested in the the partial effect\n\n$$\n  \\frac{ \\partial \\, \\E[Y|X_1,X_2,Q]}{\\partial \\, X_1} = \\beta_1\n$$\nBut we are faced with the issue that we do not observe $Q$ (which implies that we cannot control for it in the regression)\n\nRecall that we can equivalently write\n\n$$\n  Y = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\beta_3 Q + U (\\#eq:ovb-y)\n$$\nwhere $\\E[U|X_1,X_2,Q]=0$.  \n\nNow, for simplicity, suppose that\n\n$$\n  \\E[Q | X_1, X_2] = \\gamma_0 + \\gamma_1 X_1 + \\gamma_2 X_2\n$$\n\nNow, let's consider the idea of just running a regression of $Y$ on $X_1$ and $X_2$ (and just not including $Q$); in other words, consider the regression\n$$\n  \\E[Y|X_1,X_2] = \\delta_0 + \\delta_1 X_1 + \\delta_2 X_2\n$$\nWe are interested in the question of whether or not we can recover $\\beta_1$ if we do this.  If we consider this \"feasible\" regression, notice if we plug in the expression for $Y$ from Equation \\@ref(eq:ovb-y),\n\n$$\n  \\begin{aligned}\n  \\E[Y|X_1,X_2] &= \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\beta_3 \\E[Q|X_1,X_2] \\\\\n  &= \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\beta_3 (\\gamma_0 + \\gamma_1 X_1 + \\gamma_2 X_2) \\\\\n  &= \\underbrace{(\\beta_0 + \\beta_3 \\gamma_0)}_{\\delta_0} + \\underbrace{(\\beta_1 + \\beta_3 \\gamma_1)}_{\\delta_1} X_1 + \\underbrace{(\\beta_2 + \\beta_3 \\gamma_2)}_{\\delta_2} X_2\n  \\end{aligned}\n$$\n\nIn other words, if we run the feasible regression of $Y$ on $X_1$ and $X_2$, $\\delta_1$ (the coefficient on $X_1$) is not equal to $\\beta_1$; rather, it is equal to $(\\beta_1 + \\beta_3 \\gamma_1)$.  \n\nThat you are not generally able to recover $\\beta_1$ in this case is called **omitted variable bias**\n\nThere are two cases where you will recover $\\delta_1 = \\beta_1$ though which occur when $\\beta_3 \\gamma_1 = 0$:\n\n- $\\beta_3=0$.  This would be the case where $Q$ has no effect on $Y$\n\n- $\\gamma_1=0$.  This would be the case where $X_1$ and $Q$ are uncorrelated after controlling for $X_2$.\n\nInterestingly, there may be some case where you can \"sign\" the bias; i.e., figure out if $\\beta_3 \\gamma_1$ is positive or negative.  For example, you might have theoretical reasons to suspect that $\\gamma_1 > 0$ and $\\beta_3 > 0$.  In this case,\n\n$$\n  \\delta_1 = \\beta_1 + \\textrm{something positive}\n$$\nwhich implies that $\\delta_1$ (i.e., running a regression that ignores $Q$) would cause us to tend to over-estimate $\\beta_1$.  \n\n::: {.side-comment}\n\n<span class=\"side-comment\">Side-Comment:</span>\n\n* The book talks about omitted variable bias in the context of causality (this is probably the leading case), but we have not talked about causality yet.  The same issues arise if we just say that we have some *regression of interest* but are unable to estimate it because some covariates are unobserved.  \n\n* The relationship to causality (which is not so important for now), is that under certain conditions, we may have a particular partial effect that we would be willing to interpret as being the \"causal effect\", but if we are unable to control for some variables that would lead to this interpretation, then we get to the issues pointed out in the textbook.\n\n:::\n\n## How to estimate the parameters in a regression model\n\nSW 4.2, 6.3\n\nLet's start with the simple linear regression model (i.e., where there is just one regressor):\n\n$$\n  Y = \\beta_0 + \\beta_1 X + U\n$$\nwith $\\E[U|X]=0$.  This model holds for every observation in the data, so we can write\n\n$$\n  Y_i = \\beta_0 + \\beta_1 X_i + U_i\n$$\nThe question for this section is: How can we estimate $\\beta_0$ and $\\beta_1$?  First, notice that, any choice that we make for an estimate of $\\beta_0$ of $\\beta_1$ amounts to picking a line.  Our strategy will be to estimate $\\beta_0$ and $\\beta_1$ by choosing values of them that result in the \"best fit\" of a line to the available data.\n\nThis begs the question: How do you choose the line that best fits the data?  Let me give you an example\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n\n<img src=\"ols_lines.jpg\">\n\nIt's clear from the figure that the blue line \"fits better\" than the green line or the red line.  If you take a second and think about the reason why this is the case, you will notice that the reason why you know that it fits better is because the points *tend to be closer* to the blue line than to the red line or the green line. \n\nIn the figure, I drew three additional lines that are labeled $U_i^b$, $U_i^g$, and $U_i^r$ which are just the difference between the blue line, the green line, and the red line and the corresponding data point in the figure.  That is,\n\n\n$$\n  \\begin{aligned}\n  U_i^b &= Y_i - b_0^b - b_1^b X_i \\\\\n  U_i^g &= Y_i - b_0^g - b_1^g X_i \\\\\n  U_i^r &= Y_i - b_0^r - b_1^r X_i\n  \\end{aligned}\n$$\nwhere, for example, $b_0^b$ and $b_1^b$ are the intercept and slope of the blue line, $b_0^g$ and $b_1^g$ are the intercept and slope of the green line, etc.  Clearly, the blue line fits this data point than the others, but we need to deal with a couple of issues to formalize this thinking.  First, $U_i^b$ and $U_i^r$ are both less than 0 (because both of those lines sit above the data point) indicating that we can't just choose the line where $U_i$ is the smallest --- for this point, that strategy would result in us liking the red line the most.  Instead, we need a measure of distance that turns negative values of $U_i$ into positive values and is larger for big negative values of $U_i$ too.  We'll use the same quadratic distance that we've used before to deal with this issue; that is, we'll define the distance between a line and the point as ${U_i^b}^2$ for the blue line, ${U_i^g}^2$ and ${U_i^r}^2$ for the green and red lines.  \n\nSecond, the above discussion computes the distance between the line and the data for a single point.  We want to extend this argument to all the data points.  And we can do that by computing the average distance between the line and the points across all points.  That is given by\n\n$$\n  \\frac{1}{n}\\sum_{i=1}^n {U_i^b}^2, \\quad \\frac{1}{n}\\sum_{i=1}^n {U_i^g}^2, \\quad \\frac{1}{n}\\sum_{i=1}^n {U_i^r}^2\n$$\nfor the blue line, green line, and red line.  These are actually numbers that we can compute.  \n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# intercept and slope of each line\n# (I just picked these)\nint_blue <- 2\nslope_blue <- 1\nint_green <- 3\nslope_green <- -1.5\nint_red <- 6\nslope_red <- 0.5\n\n# compute \"errors\"\nUb <- Y - int_blue - slope_blue*X\nUg <- Y - int_green - slope_green*X\nUr <- Y - int_red - slope_red*X\n\n# compute distances\ndist_blue <- mean(Ub^2)\ndist_green <- mean(Ug^2)\ndist_red <- mean(Ur^2)\n\n# report distances\nround(data.frame(dist_blue, dist_green, dist_red), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  dist_blue dist_green dist_red\n1     0.255      5.828   14.728\n```\n\n\n:::\n:::\n\n\n\n\n\n\nThis corroborates our earlier intuition --- the blue line appears to fit the data much better than the other two lines.  \n\nIt turns out that we can use the same sort of idea as above to choose not just among three possible lines to fit the data, but to choose among *all possible lines*.  More generally than we have been doing, let's write\n\n$$\n  Y_i = b_0 + b_1 X_i + U_i(b_0,b_1)\n$$\nIn other words, for any values of $b_0$ and $b_1$ that we would like to plug in (say like for the green line or red line in the figure above), we can define $U_i(b_0,b_1)$ to be whatever is leftover between the line and the actual data.\n\nWe can choose the line (by choosing values of $b_0$ and $b_1$) that minimizes the average distance between the line and the points.  In other words, we will set\n\n$$\n  \\begin{aligned}\n  (\\hat{\\beta}_0, \\hat{\\beta}_1) &= \\underset{b_0,b_1}{\\textrm{argmin}} \\frac{1}{n} \\sum_{i=1}^n U_i(b_0,b_1)^2 \\\\\n  &= \\underset{b_0,b_1}{\\textrm{argmin}} \\frac{1}{n} \\sum_{i=1}^n (Y_i - b_0 - b_1 X_i)^2\n  \\end{aligned}\n$$\nThis is a complicated looking mathematical expression, but I think the intuition is pretty easy to understand.  It says that we want to find the values of $b_0$ and $b_1$ that make the distance between the points and the line as small as possible on average.  Whatever these values are, that is what we are going to set $\\hat{\\beta}_0$ and $\\hat{\\beta}_1$ --- our estimates of $\\beta_0$ and $\\beta_1$ --- to be.\n\nHow can you do this?  One idea is to do it numerically --- you could try out a ton of different combinations of $b_0$ and $b_1$ and pick which one fits the best.  Your computer could probably actually do this, but it would become quite a hard problem as we added more and more regressors.  \n\nIt turns out that we can actually find a solution for the values of $b_0$ and $b_1$ that minimize the above expression using calculus.\n\nYou probably recall how to minimize a function.  You take its derivative, set it equal to 0, and solve that equation.  [It's actually a little more complicated than that because you need to ensure that you're finding a minimum rather than a maximum, but the above equation is actually quadratic, so it will have a minimum.]\n\nThat's all that we will do here --- just the thing we need to take the derivative of looks complicated.  Actually, the $\\frac{1}{n}$ and $\\sum$ terms will just hang around.  For the rest though, we need to use the *chain rule*; that is, we need to take the derivative of the outside and then multiply by the derivative of the inside.  We also need to take the derivative both with respect to $b_0$ and with respect to $b_1$.\n\nLet's start by taking the derivative with respect to $b_0$ and setting it equal to 0.\n\n$$\n  -\\frac{2}{n}\\sum_{i=1}^n (Y_i - \\hat{\\beta}_0 - \\hat{\\beta}_1 X_i) = 0 (\\#eq:foc-bet0)\n$$\nwhere the $2$ comes from taking the deriviative of the squared part and the negative sign at the beginning comes from taking the derivative of $-b_0$ on the inside.  I also replaced $b_0$ and $b_1$ here since $\\hat{\\beta}_0$ and $\\hat{\\beta}_1$ are the values that will solve this equation.\n\nNext, let's take the derivative with respect to $b_1$:\n$$\n  -\\frac{2}{n} \\sum_{i=1}^n (Y_i - \\hat{\\beta}_0 - \\hat{\\beta}_1 X_i) X_i = 0 (\\#eq:foc-bet1)\n$$  \nwhere the 2 comes from taking the derivative of the squared part, and the negative sign at the beginning and $X_i$ at the end come from taking the derivative of the inside with respect to $b_1$.  \n\nAll we have to do now is to solve these Equations \\@ref(eq:foc-bet0) and \\@ref(eq:foc-bet1) for $\\hat{\\beta}_0$ and $\\hat{\\beta}_1$.  Before we do it, let me just mention that we are about to do some fairly challenging algebra, but that is all it is.  Conceptually, it is just the same as solving a system of two equations with two unknowns that you probably did at some point in high school.\n\nStarting with the first equation, \n\n$$\n  \\begin{aligned}\n  & \\phantom{\\implies} -\\frac{2}{n} \\sum_{i=1}^n (Y_i - \\hat{\\beta}_0 - \\hat{\\beta}_1 X_i) &= 0 \\\\\n  & \\implies \\frac{1}{n} \\sum_{i=1}^n (Y_i - \\hat{\\beta}_0 - \\hat{\\beta}_1 X_i) &= 0 \\\\\n  & \\implies \\bar{Y} - \\hat{\\beta}_0 - \\hat{\\beta}_1 \\bar{X} &= 0 \\\\\n  & \\implies \\boxed{\\hat{\\beta}_0 = \\bar{Y} - \\hat{\\beta}_1 \\bar{X}} \n  \\end{aligned} \n$$\nwhere the second line holds by dividing both sides by $-2$, the third line holds by pushing the summation through the sums/differences and simplifying terms, and the last line holds by rearranging to solve for $\\hat{\\beta}_0$.\n\n\nNow, let's use the above result and Equation \\@ref(eq:foc-bet1) to solve for $\\hat{\\beta}_1$.\n\n$$\n  \\begin{aligned}\n  & \\phantom{\\implies} -\\frac{2}{n} \\sum_{i=1}^n (Y_i - \\hat{\\beta}_0 - \\hat{\\beta}_1) X_i &= 0 \\\\\n  & \\implies  \\frac{1}{n} \\sum_{i=1}^n (Y_i - \\hat{\\beta}_0 - \\hat{\\beta}_1) X_i) X_i &= 0 \\\\\n  & \\implies  \\frac{1}{n} \\sum_{i=1}^n (Y_i - (\\bar{Y} - \\hat{\\beta}_1 \\bar{X}) - \\hat{\\beta}_1 X_i) X_i &= 0 \\\\\n  & \\implies  \\frac{1}{n} \\sum_{i=1}^n X_i Y_i - \\bar{Y} \\frac{1}{n} \\sum_{i=1}^n X_i + \\hat{\\beta}_1 \\bar{X} \\frac{1}{n} \\sum_{i=1}^n X_i - \\hat{\\beta}_1 \\frac{1}{n} \\sum_{i=1}^n X_i^2 &= 0  \\\\\n\\end{aligned}\n$$\nLet me explain each line and then we will keep going.  The second line holds because the $-2$ can just be canceled on each side, the third line holds by plugging in the expression we derived for $\\hat{\\beta}_0$ above, and the last line holds by splitting up the summation and bringing out terms that do not change across $i$.  Let's keep going\n\n$$\n\\begin{aligned}\n  \\implies  \\frac{1}{n} \\sum_{i=1}^n X_i Y_i - \\bar{X}\\bar{Y} &= \\hat{\\beta}_1\\left(\\frac{1}{n} \\sum_{i=1}^n X_i^2 - \\bar{X}^2 \\right) \\\\\n  \\implies  \\hat{\\beta}_1 &= \\frac{\\frac{1}{n} \\sum_{i=1}^n X_i Y_i - \\bar{X}\\bar{Y}}{\\frac{1}{n} \\sum_{i=1}^n X_i^2 - \\bar{X}^2} \\\\\n  \\implies  & \\boxed{\\hat{\\beta}_1 = \\frac{\\widehat{\\Cov}(X,Y)}{\\widehat{\\Var}(X)}}\n  \\end{aligned}\n$$\nwhere the first line holds by using the definition of $\\bar{X}$ and moving some terms to the other side.  The second equality holds by dividing both sides by $\\left(\\frac{1}{n} \\displaystyle \\sum_{i=1}^n X_i^2 - \\bar{X}^2 \\right)$, and the last equality holds by the definition of sample covariance and variance.\n\n::: {.side-comment}\n\n<span class=\"side-comment\">Side-Comment:</span> I'd like to point out one more time that our estimates $\\hat{\\beta}_0$ and $\\hat{\\beta}_1$ are generally not exactly equal to $\\beta_0$ and $\\beta_1$.  The figure earlier in this section was generated using simulated data where I set $\\beta_0=2$ and $\\beta_1=1$.  However, we estimate $\\hat{\\beta}_0 = 1.75$ and $\\hat{\\beta}_1 = 0.95$ using the simulated data in that figure.  These lines are close to each other, but not exactly the same.\n\nFurther, recall that we defined the **error term** $U_i$ from\n\n$$\n  Y_i = \\beta_0 + \\beta_1 X_i + U_i\n$$\nwhich is the difference between individual $i$'s outcome and the *population* regression line.  \n\nSimilarly, we define the **residual** $\\hat{U}_i$ as\n\n$$\n  Y_i = \\hat{\\beta}_0 + \\hat{\\beta}_1 X_i + \\hat{U}_i\n$$\nso that $\\hat{U}_i$ is the difference between individual $i$'s outcome and the estimated regression line.  Moreover, since generally $\\beta_0 \\neq \\hat{\\beta}_0$ and $\\beta_1 \\neq \\hat{\\beta}_1$, generally $U_i \\neq \\hat{U}_i$.\n\n\n:::\n\n### Computation\n\nBefore moving on, let's just confirm that the formulas that we derived are actually what `R` uses in order to estimates the parameters in a regression.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# using lm\nreg8 <- lm(mpg ~ hp, data=mtcars)\nsummary(reg8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mpg ~ hp, data = mtcars)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-5.7121 -2.1122 -0.8854  1.5819  8.2360 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 30.09886    1.63392  18.421  < 2e-16 ***\nhp          -0.06823    0.01012  -6.742 1.79e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.863 on 30 degrees of freedom\nMultiple R-squared:  0.6024,\tAdjusted R-squared:  0.5892 \nF-statistic: 45.46 on 1 and 30 DF,  p-value: 1.788e-07\n```\n\n\n:::\n\n```{.r .cell-code}\n# using our formulas\nbet1 <- cov(mtcars$mpg, mtcars$hp) / var(mtcars$hp)\n\nbet0 <- mean(mtcars$mpg) - bet1*mean(mtcars$hp)\n\n# print results\ndata.frame(bet0=bet0, bet1=bet1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      bet0        bet1\n1 30.09886 -0.06822828\n```\n\n\n:::\n:::\n\n\n\n\n\n\nand they are identical.\n\n\n### More than one regressor\n\nNow, let's suppose that you want to estimate a more complicated regressions like\n\n$$\n  Y = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\beta_3 X_3 + U\n$$\n\nor, even more generally,\n\n$$\n  Y = \\beta_0 + \\beta_1 X_1 + \\cdots + \\beta_k X_k + U\n$$\nWe can still choose the line that best fits the data by solving\n\n$$\n  (\\hat{\\beta}_0, \\hat{\\beta}_1, \\ldots, \\hat{\\beta}_k) = \\underset{b_0,b_1,\\ldots,b_k}{\\textrm{argmin}} \\frac{1}{n} \\sum_{i=1}^n (Y_i - b_0 - b_1 X_{1i} - \\cdots - b_k X_{ki})^2\n$$\nTo do it, we would need to take the derivative with respect to $b_0, b_1, \\ldots, b_k$.  This will give a system of equations with $(k+1)$ equations and $(k+1)$ unknowns.  You can solve this --- it actually is quite easy / very similar to what we just did if you know just a little bit of linear algebra, but this is beyond the scope of our course --- and it is quite easy for the computer to solve.\n\n## Inference\n\nSW 4.5, 5.1, 5.2, 6.6\n\nWe discussed in class the practical issues of inference in linear regression models.  \n\nThese results rely on arguments building on the Central Limit Theorem (this should not surprise you as it is similar to the case for the asymptotic distribution of $\\sqrt{n}(\\bar{Y} - \\E[Y]))$ that we discussed earlier in the semester.  \n\nIn this section, I sketch these types of arguments for you.  This material is advanced, but I suggest that you study this material.  \n\nWe are going to show that, in the simple linear regression model, \n\\begin{align*}\n  \\sqrt{n}(\\hat{\\beta}_1 - \\beta_1) \\rightarrow N(0,V) \\quad \\textrm{as} \\ n \\rightarrow \\infty\n\\end{align*}\nwhere \n\\begin{align*}\n  V = \\frac{\\E[(X-\\E[X])^2 U^2]}{\\var(X)^2}\n\\end{align*}\nand discuss how to use this result to conduct inference.\n\nLet's start by showing why this result holds.\n\nTo start with, recall that\n\\begin{align}\n  \\hat{\\beta}_1 = \\frac{\\widehat{\\cov}(X,Y)}{\\widehat{\\var}(X)} (\\#eq:b1)\n\\end{align}\n\nBefore providing a main result, let's start with noting the following:\n\n*Helpful Intermediate Result 1*\nNotice that\n\\begin{align*}\n  \\frac{1}{n}\\sum_{i=1}^n \\Big( (X_i - \\bar{X})\\bar{Y}\\Big) &= \\bar{Y} \\frac{1}{n}\\sum_{i=1}^n \\Big( X_i-\\bar{X} \\Big) \\\\\n  &= \\bar{Y} \\left( \\frac{1}{n}\\sum_{i=1}^n X_i - \\frac{1}{n}\\sum_{i=1}^n \\bar{X} \\right) \\\\\n  &= \\bar{Y} \\Big(\\bar{X} - \\bar{X} \\Big) \\\\\n  &= 0\n\\end{align*}\nwhere the first equality just pulls $\\bar{Y}$ out of the summation (it is a constant with respect to the summation), the second equality pushes the summation through the difference, the first part of the third equality holds by the definition of $\\bar{X}$ and the second part holds because it is an average of a constant.\n\nThis implies that\n\\begin{align}\n  \\frac{1}{n}\\sum_{i=1}^n \\Big( (X_i - \\bar{X})(Y_i - \\bar{Y})\\Big) = \\frac{1}{n}\\sum_{i=1}^n \\Big( (X_i - \\bar{X})Y_i\\Big) (\\#eq:hr1)\n\\end{align}\nand very similar arguments (basically the same arguments in reverse) also imply that\n\\begin{align}\n  \\frac{1}{n}\\sum_{i=1}^n \\Big( (X_i - \\bar{X})X_i\\Big) = \\frac{1}{n}\\sum_{i=1}^n \\Big( (X_i - \\bar{X})(X_i - \\bar{X})\\Big) (\\#eq:hr2)\n\\end{align}\nWe use both \\@ref(eq:hr1) and \\@ref(eq:hr2) below.\n\n\\vspace{100pt}\n\nNext, consider the numerator in \\@ref(eq:b1)\n\\begin{align*}\n  \\widehat{\\cov}(X,Y) &= \\frac{1}{n} \\sum_{i=1}^n (X_i - \\bar{X})(Y_i - \\bar{Y}) \\\\\n  &= \\frac{1}{n} \\sum_{i=1}^n (X_i - \\bar{X})Y_i \\\\\n  &= \\frac{1}{n} \\sum_{i=1}^n (X_i - \\bar{X})(\\beta_0 + \\beta_1 X_i + U_i) \\\\\n  &= \\underbrace{\\beta_0 \\frac{1}{n} \\sum_{i=1}^n (X_i - \\bar{X})}_{(A)} + \\underbrace{\\beta_1 \\frac{1}{n} \\sum_{i=1}^n (X_i - \\bar{X}) X_i}_{(B)} + \\underbrace{\\frac{1}{n} \\sum_{i=1}^n (X_i - \\bar{X}) U_i}_{(C)}) \\\\\n\\end{align*}\nwhere the first equality holds by the definition of sample covariance, the second equality holds by \\@ref(eq:hr1), the third equality plugs in for $Y_i$, and the last equality combines terms and passes the summation through the additions/subtractions.\n\n\nNow, let's consider each of these in turn.\n\nFor (A),\n\\begin{align*}\n  \\frac{1}{n} \\sum_{i=1}^n X_i = \\bar{X} \\qquad \\textrm{and} \\qquad \\frac{1}{n} \\sum_{i=1}^n \\bar{X} = \\bar{X}\n\\end{align*}\nwhich implies that this term is equal to 0.\n\nFor (B), notice that\n\\begin{align*}\n  \\beta_1 \\frac{1}{n} \\sum_{i=1}^n (X_i - \\bar{X}) X_i &= \\beta_1 \\frac{1}{n} \\sum_{i=1}^n (X_i - \\bar{X}) (X_i - \\bar{X}) \\\\\n  &= \\beta_1 \\widehat{\\var}(X)\n\\end{align*}\nwhere the first equality holds by \\@ref(eq:hr2) and the second equality holds by the definition of sample variance.\n\nFor (C), well, we'll just carry that one around for now.\n\nPlugging in the expressions for (A), (B), and (C) back into Equation \\@ref(eq:b1) implies that\n\\begin{align*}\n  \\hat{\\beta}_1 = \\beta_1 + \\frac{1}{n} \\sum_{i=1}^n \\frac{(X_i - \\bar{X}) U_i}{\\widehat{\\var}(X)}\n\\end{align*}\nNext, re-arranging terms and multiplying both sides by $\\sqrt{n}$ implies that\n\\begin{align*}\n  \\sqrt{n}(\\hat{\\beta}_1 - \\beta_1) &= \\sqrt{n} \\left(\\frac{1}{n} \\sum_{i=1}^n \\frac{(X_i - \\bar{X}) U_i}{\\widehat{\\var}(X)}\\right) \\\\\n  & \\approx \\sqrt{n} \\left(\\frac{1}{n} \\sum_{i=1}^n \\frac{(X_i - \\E[X]) U_i}{\\var(X)}\\right)\n\\end{align*}\nThe last line (the approximately one) is kind of a weak argument, but basically you can replace $\\bar{X}$ and $\\widehat{\\var}(X)$ and the effect of this replacement will converge to 0 in large samples (this is the reason for the approximately) --- if you want a more complete explanation, sign up for my graduate econometrics class next semester.\n\nIs this helpful?  It may not be obvious, but the right hand side of the above equation is actually something that we can apply the Central Limit Theorem to.  In particular, maybe it is helpful to define $Z_i = \\frac{(X_i - \\E[X]) U_i}{\\var(X)}$.  We know that we could apply a Central Limit Theorem to $\\sqrt{n}\\left( \\frac{1}{n} \\sum_{i=1}^n Z_i \\right)$ if (i) $Z_i$ had mean 0, and (ii) it is iid.  That it is iid holds immediately from the random sampling assumption.  For mean 0,\n\\begin{align*}\n  \\E[Z] &= \\E\\left[ \\frac{(X - \\E[X]) U}{\\var(X)}\\right] \\\\\n  &= \\frac{1}{\\var(X)} \\E[(X - \\E[X]) U] \\\\\n  &= \\frac{1}{\\var(X)} \\E[(X - \\E[X]) \\underbrace{\\E[U|X]}_{=0}] \\\\\n  &= 0\n\\end{align*}\nwhere the only challenging line here is the third one holds from the Law of Iterated Expectations.  This means that we can apply the central limit theorem, and in particular,\n$\\sqrt{n} \\left( \\frac{1}{n} \\sum_{i=1}^n Z_i \\right) \\rightarrow N(0,V)$ where $V=\\var(Z) = \\E[Z^2]$ (where the 2nd equality here holds because $Z$ has mean 0).  Now, just substituting back in for $Z$ implies that\n\\begin{align*}\n  \\sqrt{n}(\\hat{\\beta}_1 - \\beta_1) \\rightarrow N(0,V)\n\\end{align*}\nwhere \n\\begin{align}\n  V &= \\E\\left[ \\left( \\frac{(X - \\E[X]) U}{\\var(X)} \\right)^2 \\right] \\nonumber \\\\\n  &= \\E\\left[ \\frac{(X - \\E[X])^2 U^2}{\\var(X)^2}\\right] (\\#eq:V)\n\\end{align}\nwhich is what we were aiming for.  \n\nGiven this result, all our previous work on standard errors, t-statistics, p-values, and confidence intervals applies. First, let me mention the way that you would estimate $V$ (same as always, just replace the population quantities with corresponding sample quantities).\n\n$$\n  \\hat{V} = \\frac{ \\frac{1}{n} \\displaystyle \\sum_{i=1}^n (X_i - \\bar{X})^2 \\hat{U}_i^2}{\\widehat{\\Var}(X)^2}\n$$\n\nwhere $\\hat{U}_i$ are the residuals.\n\nNow, standard errors are just the same as before (the only difference is that $\\hat{V}$ itself has changed)\n\n$$\n\\begin{aligned}\n  \\textrm{s.e.}(\\hat{\\beta}) &= \\frac{\\sqrt{\\hat{V}}}{\\sqrt{n}}\n\\end{aligned}\n$$\n\nBy far the most common null hypothesis is $H_0: \\beta = 0$, which suggests the following t-statistic:\n\n$$\n  t = \\frac{\\hat{\\beta}}{\\textrm{s.e.}(\\hat{\\beta})}\n$$\nOne can continue to calculate a p-value by\n\n$$\n  \\textrm{p-value} = 2 \\Phi(-|t|)\n$$\nand a 95% confidence interval is given by\n\n$$\n  CI = [\\hat{\\beta} - 1.96 \\textrm{s.e.}(\\hat{\\beta}), \\hat{\\beta} + 1.96 \\textrm{s.e.}(\\hat{\\beta})]\n$$\n\n### Computation\n\nLet's check if what we derived is what we can compute using `R`.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# this is the same regression as in the previous section\nsummary(reg8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mpg ~ hp, data = mtcars)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-5.7121 -2.1122 -0.8854  1.5819  8.2360 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 30.09886    1.63392  18.421  < 2e-16 ***\nhp          -0.06823    0.01012  -6.742 1.79e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.863 on 30 degrees of freedom\nMultiple R-squared:  0.6024,\tAdjusted R-squared:  0.5892 \nF-statistic: 45.46 on 1 and 30 DF,  p-value: 1.788e-07\n```\n\n\n:::\n\n```{.r .cell-code}\n# show previous calcuations\ndata.frame(bet0=bet0, bet1=bet1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      bet0        bet1\n1 30.09886 -0.06822828\n```\n\n\n:::\n\n```{.r .cell-code}\n# components of Vhat\nY <- mtcars$mpg\nX <- mtcars$hp\nUhat <- Y - bet0 - bet1*X\nXbar <- mean(X)\nvarX <- mean( (X-Xbar)^2 )\nVhat <- mean( (X-Xbar)^2 * Uhat^2 ) / ( varX^2 )\nn <- nrow(mtcars)\nse <- sqrt(Vhat)/sqrt(n)\nt_stat <- bet1/se\np_val <- 2*pnorm(-abs(t_stat))\nci_L <- bet1 - 1.96*se\nci_U <- bet1 + 1.96*se\n\n# print results\nround(data.frame(se, t_stat, p_val, ci_L, ci_U),5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       se   t_stat p_val     ci_L     ci_U\n1 0.01313 -5.19644     0 -0.09396 -0.04249\n```\n\n\n:::\n:::\n\n\n\n\n\nInterestingly, these are not *exactly* the same as what comes from the `lm` command.  Here's what the difference is: `R` makes a simplifying assumption called \"homoskedasticity\" that simplifies the expression for the variance.  This can result in slightly different standard errors (and therefore slightly different t-statistics, p-values, and confidence intervals too) than the ones we calculated.  \n\nAn alternative package that is popular among economists for estimating regressions and getting \"heteroskedasticity robust\" standard errors is the `estimatr` package.  \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(estimatr)\n\nreg9 <- lm_robust(mpg ~ hp, data=mtcars, se_type=\"HC0\")\nsummary(reg9)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm_robust(formula = mpg ~ hp, data = mtcars, se_type = \"HC0\")\n\nStandard error type:  HC0 \n\nCoefficients:\n            Estimate Std. Error t value  Pr(>|t|) CI Lower CI Upper DF\n(Intercept) 30.09886    2.01067  14.970 1.851e-15 25.99252 34.20520 30\nhp          -0.06823    0.01313  -5.196 1.338e-05 -0.09504 -0.04141 30\n\nMultiple R-squared:  0.6024 ,\tAdjusted R-squared:  0.5892 \nF-statistic:    27 on 1 and 30 DF,  p-value: 1.338e-05\n```\n\n\n:::\n:::\n\n\n\n\n\nThe \"HC0\" standard errors are \"heteroskedasticity consistent\" standard errors, and you can see that they match what we calculated above.\n\n## Lab 4: Birthweight and Smoking\n\nFor this lab, we'll use the data `Birthweight_Smoking` and study the relationship between infant birthweight and mother's smoking behavior.\n\n1. Run a regression of $birthweight$ on $smoker$.  How do you interpret the results?\n\n2. Use the `datasummary_balance` function from the `modelsummary` package to provide summary statistics for each variable in the data separately by smoking status of the mother.  Do you notice any interesting patterns?\n\n3. Now run a regression of $birthweight$ on $smoker$, $educ$, $nprevisit$, $age$, and $alcohol$.  How do you interpret the coefficient on $smoker$?  How does its magnitude compare to the result from #1?  What do you make of this?\n\n4. Now run a regression of $birthweight$ on $smoker$, the interaction of $smoker$ and $age$ and the other covariates (including $age$) from #3.  How do you interpret the coefficient on $smoker$ and the coefficient on the interaction term?\n\n5. Now run a regression of $birthweight$ on $smoker$, the interaction of $smoker$ and $alcohol$ and the other covariates from #3.  How do you interpret the coefficient on $smoker$ and the coefficient on the interaction term?\n\n6. Now run a regression of $birthweight$ on $age$ and $age^2$.  Plot the predicted value of birthweight as a function of age for ages from 18 to 44.  What do you make of this?\n\n7. Now run a regression of $\\log(birthweight)$ on $smoker$ and the other covariates from #3.  How do you interpret the coefficient on $smoker$?\n\n## Lab 4: Solutions\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(haven)\nlibrary(modelsummary)\nlibrary(dplyr)\nlibrary(ggplot2)\n\n# load data\nBirthweight_Smoking <- read_dta(\"data/birthweight_smoking.dta\")\n```\n:::\n\n\n\n\n\n\n1.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg1 <- lm(birthweight ~ smoker, data=Birthweight_Smoking)\nsummary(reg1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = birthweight ~ smoker, data = Birthweight_Smoking)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-3007.06  -313.06    26.94   366.94  2322.94 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  3432.06      11.87 289.115   <2e-16 ***\nsmoker       -253.23      26.95  -9.396   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 583.7 on 2998 degrees of freedom\nMultiple R-squared:  0.0286,\tAdjusted R-squared:  0.02828 \nF-statistic: 88.28 on 1 and 2998 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n\nWe estimate that, on average, smoking reduces an infant's birthweight by about 250 grams.  The estimated effect is strongly statistically significant, and (I am not an expert but) that seems like a large effect of smoking to me.\n\n2. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create smoker factor --- just to make table look nicer\nBirthweight_Smoking$smoker_factor <- as.factor(ifelse(Birthweight_Smoking$smoker==1, \"smoker\", \"non-smoker\"))\ndatasummary_balance(~smoker_factor, \n                    data=dplyr::select(Birthweight_Smoking, -smoker),\n                    fmt=2)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!DOCTYPE html> \n<html lang=\"en\">\n  <head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <title>tinytable_fnkosp6v5wc9nj5xsmen</title>\n    <style>\n.table td.tinytable_css_0wj5ukr8wy5uhoklgh1w, .table th.tinytable_css_0wj5ukr8wy5uhoklgh1w {    border-bottom: solid 0.1em #d3d8dc; }\n.table td.tinytable_css_kat6mjavdlqv6d66c60t, .table th.tinytable_css_kat6mjavdlqv6d66c60t {    text-align: center; }\n.table td.tinytable_css_yeirwnepfx0dberxdwq7, .table th.tinytable_css_yeirwnepfx0dberxdwq7 {    border-bottom: solid 0.05em #d3d8dc; }\n.table td.tinytable_css_mr41pmzkrskbzq2wwfay, .table th.tinytable_css_mr41pmzkrskbzq2wwfay {    text-align: left; }\n.table td.tinytable_css_glwjfsvv4um6wxtbb6ls, .table th.tinytable_css_glwjfsvv4um6wxtbb6ls {    text-align: right; }\n.table td.tinytable_css_7qilal07vhifv3twpcex, .table th.tinytable_css_7qilal07vhifv3twpcex {    text-align: right; }\n.table td.tinytable_css_ckvnpaim2gd9ea2wt06b, .table th.tinytable_css_ckvnpaim2gd9ea2wt06b {    text-align: right; }\n.table td.tinytable_css_ir7ilipqq9lab0pvr2w1, .table th.tinytable_css_ir7ilipqq9lab0pvr2w1 {    text-align: right; }\n.table td.tinytable_css_fwnqznx6ifd2332rx8oo, .table th.tinytable_css_fwnqznx6ifd2332rx8oo {    text-align: right; }\n.table td.tinytable_css_h2qomll05al1uxnu6wyr, .table th.tinytable_css_h2qomll05al1uxnu6wyr {    text-align: right; }\n.table td.tinytable_css_nt4mmhwnpgu4lsyopf3r, .table th.tinytable_css_nt4mmhwnpgu4lsyopf3r {    text-align: center; }\n    </style>\n    <script src=\"https://polyfill.io/v3/polyfill.min.js?features=es6\"></script>\n    <script id=\"MathJax-script\" async src=\"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"></script>\n    <script>\n    MathJax = {\n      tex: {\n        inlineMath: [['$', '$'], ['\\\\(', '\\\\)']]\n      },\n      svg: {\n        fontCache: 'global'\n      }\n    };\n    </script>\n  </head>\n\n  <body>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_fnkosp6v5wc9nj5xsmen\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n<tr>\n<th scope=\"col\" align=\"center\" colspan=1> </th>\n<th scope=\"col\" align=\"center\" colspan=2>non-smoker (N=2418)</th>\n<th scope=\"col\" align=\"center\" colspan=2>smoker (N=582)</th>\n<th scope=\"col\" align=\"center\" colspan=1> </th>\n<th scope=\"col\" align=\"center\" colspan=1> </th>\n</tr>\n        \n              <tr>\n                <th scope=\"col\"> </th>\n                <th scope=\"col\">Mean</th>\n                <th scope=\"col\">Std. Dev.</th>\n                <th scope=\"col\">Mean</th>\n                <th scope=\"col\">Std. Dev.</th>\n                <th scope=\"col\">Diff. in Means</th>\n                <th scope=\"col\">Std. Error</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td>nprevist   </td>\n                  <td>11.19  </td>\n                  <td>3.50  </td>\n                  <td>10.18  </td>\n                  <td>4.23  </td>\n                  <td>-1.01  </td>\n                  <td>0.19 </td>\n                </tr>\n                <tr>\n                  <td>alcohol    </td>\n                  <td>0.01   </td>\n                  <td>0.11  </td>\n                  <td>0.05   </td>\n                  <td>0.22  </td>\n                  <td>0.04   </td>\n                  <td>0.01 </td>\n                </tr>\n                <tr>\n                  <td>tripre1    </td>\n                  <td>0.83   </td>\n                  <td>0.38  </td>\n                  <td>0.70   </td>\n                  <td>0.46  </td>\n                  <td>-0.13  </td>\n                  <td>0.02 </td>\n                </tr>\n                <tr>\n                  <td>tripre2    </td>\n                  <td>0.14   </td>\n                  <td>0.34  </td>\n                  <td>0.22   </td>\n                  <td>0.41  </td>\n                  <td>0.08   </td>\n                  <td>0.02 </td>\n                </tr>\n                <tr>\n                  <td>tripre3    </td>\n                  <td>0.03   </td>\n                  <td>0.16  </td>\n                  <td>0.06   </td>\n                  <td>0.24  </td>\n                  <td>0.04   </td>\n                  <td>0.01 </td>\n                </tr>\n                <tr>\n                  <td>tripre0    </td>\n                  <td>0.01   </td>\n                  <td>0.08  </td>\n                  <td>0.02   </td>\n                  <td>0.15  </td>\n                  <td>0.02   </td>\n                  <td>0.01 </td>\n                </tr>\n                <tr>\n                  <td>birthweight</td>\n                  <td>3432.06</td>\n                  <td>584.62</td>\n                  <td>3178.83</td>\n                  <td>580.01</td>\n                  <td>-253.23</td>\n                  <td>26.82</td>\n                </tr>\n                <tr>\n                  <td>unmarried  </td>\n                  <td>0.18   </td>\n                  <td>0.38  </td>\n                  <td>0.43   </td>\n                  <td>0.50  </td>\n                  <td>0.25   </td>\n                  <td>0.02 </td>\n                </tr>\n                <tr>\n                  <td>educ       </td>\n                  <td>13.15  </td>\n                  <td>2.21  </td>\n                  <td>11.88  </td>\n                  <td>1.62  </td>\n                  <td>-1.27  </td>\n                  <td>0.08 </td>\n                </tr>\n                <tr>\n                  <td>age        </td>\n                  <td>27.27  </td>\n                  <td>5.37  </td>\n                  <td>25.32  </td>\n                  <td>5.06  </td>\n                  <td>-1.95  </td>\n                  <td>0.24 </td>\n                </tr>\n                <tr>\n                  <td>drinks     </td>\n                  <td>0.03   </td>\n                  <td>0.47  </td>\n                  <td>0.19   </td>\n                  <td>1.23  </td>\n                  <td>0.16   </td>\n                  <td>0.05 </td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n\n    <script>\n      function styleCell_tinytable_a2u9hp23ukxerintmqtb(i, j, css_id) {\n        var table = document.getElementById(\"tinytable_fnkosp6v5wc9nj5xsmen\");\n        table.rows[i].cells[j].classList.add(css_id);\n      }\n      function insertSpanRow(i, colspan, content) {\n        var table = document.getElementById('tinytable_fnkosp6v5wc9nj5xsmen');\n        var newRow = table.insertRow(i);\n        var newCell = newRow.insertCell(0);\n        newCell.setAttribute(\"colspan\", colspan);\n        // newCell.innerText = content;\n        // this may be unsafe, but innerText does not interpret <br>\n        newCell.innerHTML = content;\n      }\n      function spanCell_tinytable_a2u9hp23ukxerintmqtb(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_fnkosp6v5wc9nj5xsmen\");\n        const targetRow = table.rows[i];\n        const targetCell = targetRow.cells[j];\n        for (let r = 0; r < rowspan; r++) {\n          // Only start deleting cells to the right for the first row (r == 0)\n          if (r === 0) {\n            // Delete cells to the right of the target cell in the first row\n            for (let c = colspan - 1; c > 0; c--) {\n              if (table.rows[i + r].cells[j + c]) {\n                table.rows[i + r].deleteCell(j + c);\n              }\n            }\n          }\n          // For rows below the first, delete starting from the target column\n          if (r > 0) {\n            for (let c = colspan - 1; c >= 0; c--) {\n              if (table.rows[i + r] && table.rows[i + r].cells[j]) {\n                table.rows[i + r].deleteCell(j);\n              }\n            }\n          }\n        }\n        // Set rowspan and colspan of the target cell\n        targetCell.rowSpan = rowspan;\n        targetCell.colSpan = colspan;\n      }\n\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(1, 0, 'tinytable_css_0wj5ukr8wy5uhoklgh1w') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(1, 1, 'tinytable_css_0wj5ukr8wy5uhoklgh1w') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(1, 2, 'tinytable_css_0wj5ukr8wy5uhoklgh1w') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(1, 3, 'tinytable_css_0wj5ukr8wy5uhoklgh1w') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(1, 4, 'tinytable_css_0wj5ukr8wy5uhoklgh1w') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(1, 5, 'tinytable_css_0wj5ukr8wy5uhoklgh1w') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(1, 6, 'tinytable_css_0wj5ukr8wy5uhoklgh1w') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(0, 0, 'tinytable_css_kat6mjavdlqv6d66c60t') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(0, 1, 'tinytable_css_kat6mjavdlqv6d66c60t') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(0, 2, 'tinytable_css_kat6mjavdlqv6d66c60t') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(0, 3, 'tinytable_css_kat6mjavdlqv6d66c60t') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(0, 4, 'tinytable_css_kat6mjavdlqv6d66c60t') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(0, 5, 'tinytable_css_kat6mjavdlqv6d66c60t') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(0, 6, 'tinytable_css_kat6mjavdlqv6d66c60t') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(0, 1, 'tinytable_css_yeirwnepfx0dberxdwq7') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(0, 2, 'tinytable_css_yeirwnepfx0dberxdwq7') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(0, 0, 'tinytable_css_mr41pmzkrskbzq2wwfay') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(1, 0, 'tinytable_css_mr41pmzkrskbzq2wwfay') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(2, 0, 'tinytable_css_mr41pmzkrskbzq2wwfay') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(3, 0, 'tinytable_css_mr41pmzkrskbzq2wwfay') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(4, 0, 'tinytable_css_mr41pmzkrskbzq2wwfay') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(5, 0, 'tinytable_css_mr41pmzkrskbzq2wwfay') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(6, 0, 'tinytable_css_mr41pmzkrskbzq2wwfay') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(7, 0, 'tinytable_css_mr41pmzkrskbzq2wwfay') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(8, 0, 'tinytable_css_mr41pmzkrskbzq2wwfay') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(9, 0, 'tinytable_css_mr41pmzkrskbzq2wwfay') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(10, 0, 'tinytable_css_mr41pmzkrskbzq2wwfay') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(11, 0, 'tinytable_css_mr41pmzkrskbzq2wwfay') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(12, 0, 'tinytable_css_mr41pmzkrskbzq2wwfay') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(0, 1, 'tinytable_css_glwjfsvv4um6wxtbb6ls') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(1, 1, 'tinytable_css_glwjfsvv4um6wxtbb6ls') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(2, 1, 'tinytable_css_glwjfsvv4um6wxtbb6ls') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(3, 1, 'tinytable_css_glwjfsvv4um6wxtbb6ls') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(4, 1, 'tinytable_css_glwjfsvv4um6wxtbb6ls') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(5, 1, 'tinytable_css_glwjfsvv4um6wxtbb6ls') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(6, 1, 'tinytable_css_glwjfsvv4um6wxtbb6ls') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(7, 1, 'tinytable_css_glwjfsvv4um6wxtbb6ls') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(8, 1, 'tinytable_css_glwjfsvv4um6wxtbb6ls') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(9, 1, 'tinytable_css_glwjfsvv4um6wxtbb6ls') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(10, 1, 'tinytable_css_glwjfsvv4um6wxtbb6ls') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(11, 1, 'tinytable_css_glwjfsvv4um6wxtbb6ls') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(12, 1, 'tinytable_css_glwjfsvv4um6wxtbb6ls') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(0, 2, 'tinytable_css_7qilal07vhifv3twpcex') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(1, 2, 'tinytable_css_7qilal07vhifv3twpcex') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(2, 2, 'tinytable_css_7qilal07vhifv3twpcex') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(3, 2, 'tinytable_css_7qilal07vhifv3twpcex') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(4, 2, 'tinytable_css_7qilal07vhifv3twpcex') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(5, 2, 'tinytable_css_7qilal07vhifv3twpcex') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(6, 2, 'tinytable_css_7qilal07vhifv3twpcex') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(7, 2, 'tinytable_css_7qilal07vhifv3twpcex') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(8, 2, 'tinytable_css_7qilal07vhifv3twpcex') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(9, 2, 'tinytable_css_7qilal07vhifv3twpcex') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(10, 2, 'tinytable_css_7qilal07vhifv3twpcex') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(11, 2, 'tinytable_css_7qilal07vhifv3twpcex') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(12, 2, 'tinytable_css_7qilal07vhifv3twpcex') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(0, 3, 'tinytable_css_ckvnpaim2gd9ea2wt06b') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(1, 3, 'tinytable_css_ckvnpaim2gd9ea2wt06b') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(2, 3, 'tinytable_css_ckvnpaim2gd9ea2wt06b') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(3, 3, 'tinytable_css_ckvnpaim2gd9ea2wt06b') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(4, 3, 'tinytable_css_ckvnpaim2gd9ea2wt06b') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(5, 3, 'tinytable_css_ckvnpaim2gd9ea2wt06b') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(6, 3, 'tinytable_css_ckvnpaim2gd9ea2wt06b') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(7, 3, 'tinytable_css_ckvnpaim2gd9ea2wt06b') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(8, 3, 'tinytable_css_ckvnpaim2gd9ea2wt06b') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(9, 3, 'tinytable_css_ckvnpaim2gd9ea2wt06b') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(10, 3, 'tinytable_css_ckvnpaim2gd9ea2wt06b') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(11, 3, 'tinytable_css_ckvnpaim2gd9ea2wt06b') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(12, 3, 'tinytable_css_ckvnpaim2gd9ea2wt06b') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(0, 4, 'tinytable_css_ir7ilipqq9lab0pvr2w1') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(1, 4, 'tinytable_css_ir7ilipqq9lab0pvr2w1') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(2, 4, 'tinytable_css_ir7ilipqq9lab0pvr2w1') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(3, 4, 'tinytable_css_ir7ilipqq9lab0pvr2w1') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(4, 4, 'tinytable_css_ir7ilipqq9lab0pvr2w1') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(5, 4, 'tinytable_css_ir7ilipqq9lab0pvr2w1') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(6, 4, 'tinytable_css_ir7ilipqq9lab0pvr2w1') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(7, 4, 'tinytable_css_ir7ilipqq9lab0pvr2w1') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(8, 4, 'tinytable_css_ir7ilipqq9lab0pvr2w1') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(9, 4, 'tinytable_css_ir7ilipqq9lab0pvr2w1') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(10, 4, 'tinytable_css_ir7ilipqq9lab0pvr2w1') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(11, 4, 'tinytable_css_ir7ilipqq9lab0pvr2w1') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(12, 4, 'tinytable_css_ir7ilipqq9lab0pvr2w1') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(0, 5, 'tinytable_css_fwnqznx6ifd2332rx8oo') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(1, 5, 'tinytable_css_fwnqznx6ifd2332rx8oo') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(2, 5, 'tinytable_css_fwnqznx6ifd2332rx8oo') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(3, 5, 'tinytable_css_fwnqznx6ifd2332rx8oo') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(4, 5, 'tinytable_css_fwnqznx6ifd2332rx8oo') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(5, 5, 'tinytable_css_fwnqznx6ifd2332rx8oo') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(6, 5, 'tinytable_css_fwnqznx6ifd2332rx8oo') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(7, 5, 'tinytable_css_fwnqznx6ifd2332rx8oo') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(8, 5, 'tinytable_css_fwnqznx6ifd2332rx8oo') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(9, 5, 'tinytable_css_fwnqznx6ifd2332rx8oo') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(10, 5, 'tinytable_css_fwnqznx6ifd2332rx8oo') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(11, 5, 'tinytable_css_fwnqznx6ifd2332rx8oo') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(12, 5, 'tinytable_css_fwnqznx6ifd2332rx8oo') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(0, 6, 'tinytable_css_h2qomll05al1uxnu6wyr') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(1, 6, 'tinytable_css_h2qomll05al1uxnu6wyr') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(2, 6, 'tinytable_css_h2qomll05al1uxnu6wyr') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(3, 6, 'tinytable_css_h2qomll05al1uxnu6wyr') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(4, 6, 'tinytable_css_h2qomll05al1uxnu6wyr') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(5, 6, 'tinytable_css_h2qomll05al1uxnu6wyr') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(6, 6, 'tinytable_css_h2qomll05al1uxnu6wyr') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(7, 6, 'tinytable_css_h2qomll05al1uxnu6wyr') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(8, 6, 'tinytable_css_h2qomll05al1uxnu6wyr') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(9, 6, 'tinytable_css_h2qomll05al1uxnu6wyr') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(10, 6, 'tinytable_css_h2qomll05al1uxnu6wyr') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(11, 6, 'tinytable_css_h2qomll05al1uxnu6wyr') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(12, 6, 'tinytable_css_h2qomll05al1uxnu6wyr') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(0, 0, 'tinytable_css_nt4mmhwnpgu4lsyopf3r') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(0, 1, 'tinytable_css_nt4mmhwnpgu4lsyopf3r') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(0, 2, 'tinytable_css_nt4mmhwnpgu4lsyopf3r') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(0, 3, 'tinytable_css_nt4mmhwnpgu4lsyopf3r') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(0, 4, 'tinytable_css_nt4mmhwnpgu4lsyopf3r') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(0, 5, 'tinytable_css_nt4mmhwnpgu4lsyopf3r') })\nwindow.addEventListener('load', function () { styleCell_tinytable_a2u9hp23ukxerintmqtb(0, 6, 'tinytable_css_nt4mmhwnpgu4lsyopf3r') })\n    </script>\n\n  </body>\n\n</html>\n```\n\n:::\n:::\n\n\n\n\n\n\nThe things that stand out to me are:\n\n- Birthweight tends to be notably lower for smokers relative to non-smokers.  The difference is about 7.4% lower birthweight for babies whose mothers smoked.\n\n- That said, smoking is also correlated with a number of other things that could be related to lower birthweights.  Mothers who smoke went to fewer pre-natal visits on average, were more likely to be unmarried, were more likely to have drink alcohol during their pregnancy, were more likely to be less educated.  They also were, on average, somewhat younger than mothers who did not smoke.\n\n3. \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg3 <- lm(birthweight ~ smoker + educ + nprevist + age + alcohol,\n           data=Birthweight_Smoking)\nsummary(reg3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = birthweight ~ smoker + educ + nprevist + age + alcohol, \n    data = Birthweight_Smoking)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2728.91  -305.26    24.69   359.63  2220.42 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 2924.963     74.185  39.428  < 2e-16 ***\nsmoker      -206.507     27.367  -7.546 5.93e-14 ***\neduc           5.644      5.532   1.020    0.308    \nnprevist      32.979      2.914  11.318  < 2e-16 ***\nage            2.360      2.178   1.083    0.279    \nalcohol      -39.512     76.365  -0.517    0.605    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 570.3 on 2994 degrees of freedom\nMultiple R-squared:  0.07402,\tAdjusted R-squared:  0.07247 \nF-statistic: 47.86 on 5 and 2994 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n\nHere we estimate that smoking reduces an infant's birthweight by about 200 grams on average holding education, number of pre-natal visits, age, and whether or not the mother consumed alcohol constant.  The magnitude of the estimated effect is somewhat smaller than the previous estimate.  Due to the discussion in #2 (particularly, that smoking was correlated with a number of other characteristics that are likely associated with lower birthweights), this decrease in the magnitude is not surprising.\n\n4. \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg4 <- lm(birthweight ~ smoker + I(smoker*age) + educ + nprevist + age + alcohol,\n           data=Birthweight_Smoking)\nsummary(reg4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = birthweight ~ smoker + I(smoker * age) + educ + \n    nprevist + age + alcohol, data = Birthweight_Smoking)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2722.56  -305.12    23.93   363.43  2244.67 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     2853.819     77.104  37.013  < 2e-16 ***\nsmoker           231.578    134.854   1.717 0.086036 .  \nI(smoker * age)  -17.145      5.168  -3.317 0.000919 ***\neduc               4.895      5.528   0.885 0.375968    \nnprevist          32.482      2.913  11.151  < 2e-16 ***\nage                5.528      2.375   2.328 0.019999 *  \nalcohol          -22.556     76.409  -0.295 0.767864    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 569.4 on 2993 degrees of freedom\nMultiple R-squared:  0.07741,\tAdjusted R-squared:  0.07556 \nF-statistic: 41.85 on 6 and 2993 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n\nWe should be careful about the interpretatio here.  We have estimated a model like \n\n$$\n  \\E[Birthweight|Smoker, Age, X] = \\beta_0 + \\beta_1 Smoker + \\beta_2 Smoker \\cdot Age + \\cdots\n$$\nTherefore, the partial effect of smoking is given by\n\n$$\n  \\E[Birthweight | Smoker=1, Age, X] - \\E[Birthweight | Smoker=0, Age, X] = \\beta_1 + \\beta_2 Age\n$$\nTherefore, the partial effect of smoking depends on $Age$.  For example, for $Age=18$, the partial effect is $\\beta_1 + \\beta_2 (18)$.  For $Age=25$, the partial effect is $\\beta_1 + \\beta_2 (25)$, and for $Age=35$, the partial effect is $\\beta_1 + \\beta_2 (35)$.  Let's calculate the partial effect at each of those ages.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbet1 <- coef(reg4)[2]\nbet2 <- coef(reg4)[3]\n\npe_18 <- bet1 + bet2*18\npe_25 <- bet1 + bet2*25\npe_35 <- bet1 + bet2*35\n\nround(cbind.data.frame(pe_18, pe_25, pe_35),2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        pe_18   pe_25   pe_35\nsmoker -77.04 -197.05 -368.51\n```\n\n\n:::\n:::\n\n\n\n\n\n\nThis suggests substantially larger effects of smoking on birthweight for older mothers.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg5 <- lm(birthweight ~ smoker + I(smoker*alcohol) + educ + nprevist + age + alcohol,\n           data=Birthweight_Smoking)\nsummary(reg5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = birthweight ~ smoker + I(smoker * alcohol) + educ + \n    nprevist + age + alcohol, data = Birthweight_Smoking)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2728.99  -304.16    24.54   359.92  2222.10 \n\nCoefficients:\n                    Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         2924.844     74.185  39.426  < 2e-16 ***\nsmoker              -201.852     27.765  -7.270 4.57e-13 ***\nI(smoker * alcohol) -151.860    152.717  -0.994    0.320    \neduc                   5.612      5.532   1.014    0.310    \nnprevist              32.844      2.917  11.260  < 2e-16 ***\nage                    2.403      2.178   1.103    0.270    \nalcohol               39.824    110.440   0.361    0.718    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 570.3 on 2993 degrees of freedom\nMultiple R-squared:  0.07432,\tAdjusted R-squared:  0.07247 \nF-statistic: 40.05 on 6 and 2993 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n\nThe point estimate suggests that the effect of smoking is larger for women who consume alcohol and smoke than for women who do not drink alcohol.  This seems plausible, but our evidence is not very strong here --- the estimates are not statistically significant at any conventional significance level (the p-value is equal to 0.32).\n\n6.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg6 <- lm(birthweight ~ age + I(age^2), data=Birthweight_Smoking)\nsummary(reg6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = birthweight ~ age + I(age^2), data = Birthweight_Smoking)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2949.81  -312.81    30.43   371.03  2452.72 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 2502.8949   225.6016  11.094  < 2e-16 ***\nage           58.1670    16.9212   3.438 0.000595 ***\nI(age^2)      -0.9099     0.3099  -2.936 0.003353 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 589.6 on 2997 degrees of freedom\nMultiple R-squared:  0.009261,\tAdjusted R-squared:  0.0086 \nF-statistic: 14.01 on 2 and 2997 DF,  p-value: 8.813e-07\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npreds <- predict(reg6, newdata=data.frame(age=seq(18,40)))\nggplot(data.frame(preds=preds, age=seq(18,40)), aes(x=age, y=preds)) + \n  geom_line() + \n  geom_point(size=3) + \n  theme_bw() + \n  ylab(\"predicted values\")\n```\n\n::: {.cell-output-display}\n![](04-linear_regression_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n\n\n\nThe figure suggests that predicted birthweight is increasing in mother's age up until about age 34 and then decreasing after that.\n\n7.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg7 <- lm(I(log(birthweight)) ~ smoker + educ + nprevist + age + alcohol,\n           data=Birthweight_Smoking)\nsummary(reg7)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = I(log(birthweight)) ~ smoker + educ + nprevist + \n    age + alcohol, data = Birthweight_Smoking)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.96324 -0.07696  0.02435  0.12092  0.50070 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  7.9402678  0.0270480 293.562  < 2e-16 ***\nsmoker      -0.0635764  0.0099782  -6.372 2.16e-10 ***\neduc         0.0022169  0.0020171   1.099    0.272    \nnprevist     0.0129662  0.0010624  12.205  < 2e-16 ***\nage          0.0003059  0.0007941   0.385    0.700    \nalcohol     -0.0181053  0.0278428  -0.650    0.516    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.2079 on 2994 degrees of freedom\nMultiple R-squared:  0.07322,\tAdjusted R-squared:  0.07167 \nF-statistic: 47.31 on 5 and 2994 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n\nThe estimated coefficient on $smoker$ says that smoking during pregnancy decreases a baby's birthweight by 6.3%, on average, holding education, number of pre-natal visits, age of the mother, and whether or not the mother consumed alcohol during the pregnancy constant.\n\n## Coding Questions\n\n1. For this problem, we will use the data `Caschool`.  This data contains information about test scores for schools from California from the 1998-1999 academic year.  For this problem, we will use the variables `testscr` (average test score in the school), `str` (student teacher ratio in the school), `avginc` (the average income in the school district), and `elpct` (the percent of English learners in the school). \n\n    a) Run a regression of test scores on student teacher ratio, average income, and English learners percentage.  Report your results.  Which regressors are statistically significant?  How do you know?\n\n    b) What is the average test score across all schools in the data?\n\n    c) What is the predicted average test score for a school with a student teacher ratio of 20, average income of \\$30,000, and 10% English learners?  How does this compare to the overall average test score from part (b)?\n    \n    d) What is the predicted average test score for a school with a student teacher ratio of 15, average income of \\$30,000, and 10% English learners?  How does this compare to your answer from part (c)?\n\n2. For this problem, we will use the data `intergenerational_mobility`.  \n\n    a) Run a regression of child family income ($child\\_fincome$) on parents' family income ($parent\\_fincome$).  How should you interpret the estimated coefficient on parents' family income?  What is the p-value for the coefficient on parents' family income?  \n    \n    b) Run a regression of $\\log(child\\_fincome)$ on $parent\\_fincome$.  How should you interpret the estimated cofficient on $parent\\_fincome$?\n    \n    c) Run a regression of $child\\_fincome$ on $\\log(parent\\_fincome)$.  How should you interpret the estimated coefficient on $\\log(parent\\_fincome)$?\n    \n    d) Run a regression of $\\log(child\\_fincome)$ on $\\log(parent\\_fincome)$.  How should you interpret the estimated coefficient on $\\log(parent\\_fincome)$?\n\n3. For this question, we'll use the `fertilizer_2000` data.  \n\n    a) Run a regression of $\\log(avyield)$ on $\\log(avfert)$.  How do you interpret the estimated coefficient on $\\log(avfert)$?  \n    \n    b) Now suppose that you additionally want to control for precipitation and the region that a country is located in.  How would you do this?  Estimate the model that you propose here, report the results, and interpret the coefficient on $\\log(avfert)$.\n    \n    c) Now suppose that you are interested in whether the effect of fertilizer varies by region that a country is located in (while still controlling for the same covariates as in part (b)).  Propose a model that can be used for this purpose.  Estimate the model that you proposed, report the results, and discuss whether the effect of fertilizer appears to vary by region or not.\n\n4. For this question, we will use the data `mutual_funds`.  We'll be interested in whether mutual funds that have higher expense ratios (these are typically actively managed funds) have higher returns relative to mutual funds that have lower expense ratios (e.g., index funds).  For this problem, we will use the variables `fund_return_3years`, `investment_type`, `risk_rating`, `size_type`, `fund_net_annual_expense_ratio`, `asset_cash`, `asset_stocks`, `asset_bonds`.  \n\n    a) Calculate the median `fund_net_annual_expense_ratio`.\n    \n    b) Use the `datasummary_balance` function from the `modelsummary` package to report summary statistics for `fund_return_3year`, `fund_net_annual_expense_ratio`, `risk_rating`, `asset_cash`, `asset_stocks`, `asset_bonds` based on whether their expense ratio is above or below the median.  Do you notice any interesting patterns?\n    \n    c) Run a regression of `fund_return_3years` on `fund_net_annual_expense_ratio`.  How do you interpret the results?\n    \n    d) Now, additionally control for `investment_type`, `risk_rating`, and `size_type` **Hint:** think carefully about what type of variables each of these are and how they should enter the model.  How do these results compare to the ones from part c?\n    \n    e) Now, add the variables `assets_cash`, `assets_stocks`, and `assets_bonds` to the model from part d.  How do you interpret these results?  Compare and interpret the differences between parts c, d, and e.\n\n5. For this question, we'll use the data `Lead_Mortality` to study the effect of lead pipes on infant mortality in 1900.    \n\n    a) Run a regression of infant mortality (`infrate`) on whether or not a city had lead pipes (`lead`) and interpret/discuss the results.\n    \n    b) It turns out that the amount of lead in drinking water depends on how acidic the water is, with more acidic water leaching more of the lead (so that there is more exposure to lead with more acidic water).  To measure acidity, we'll use the pH of the water in a particular city (`ph`); recall that, a lower value of pH indicates higher acidity.  Run a regression of infant mortality on whether or not a city has lead pipes, the pH of its water, and the interaction between having lead pipes and pH.  Report your results.  What is the estimated partial effect of having lead pipes from this model?\n    \n    c) Given the results in part b, calculate an estimate of the average partial effect of having lead pipes on infant mortality.\n    \n    d) Given the results in part b, how much does the partial effect of having lead pipes differ for cities that have a pH of 6.5 relative to a pH of 7.5?\n    \n\n## Extra Questions\n\n1. Suppose you run the following regression\n\\begin{align*}\n  Earnings = \\beta_0 + \\beta_1 Education + U\n\\end{align*}\nwith $\\E[U|Education] = 0$.  How do you interpret $\\beta_1$ here?\n\n2. Suppose you run the following regression\n\\begin{align*}\n  Earnings = \\beta_0 + \\beta_1 Education + \\beta_2 Experience + \\beta_3 Female + U\n\\end{align*}\nwith $\\E[U|Education, Experience, Female] = 0$.  How do you interpret $\\beta_1$ here?\n\n3. Suppose you are interested in testing whether an extra year of education increases earnings by the same amount for men and women.  \n\n    a) Propose a regression and strategy for this sort of test.  \n    \n    b) Suppose you also want to control for experience in conducting this test, how would do it?\n    \n4. Suppose you run the following regression\n\\begin{align*}\n  \\log(Earnings) = \\beta_0 + \\beta_1 Education + \\beta_2 Experience + \\beta_3 Female + U\n\\end{align*}\nwith $\\E[U|Education, Experience, Female] = 0$.  How do you interpret $\\beta_1$ here?\n\n5. A common extra condition (though somewhat old-fashioned) is to impose *homoskedasticity*.  Homoskedasticity says that $\\E[U^2|X] = \\sigma^2$ (i.e., the variance of the error term does not change across different values of $X$).\n\n    a) Under homoskedasticity, the expression for $V$ in \\@ref(eq:V) simplifies.  Provide a new expression for $V$ under homoskedasticity.  **Hint:** you will need to use the law of iterated expectations.\n    \n    b) Using this expression for $V$, explain how to calculate standard errors for an estimate of $\\beta_1$ in a simple linear regression.\n    \n    c) Explain how to construct a t-statistic for testing $H_0: \\beta_1=0$ under homoskedasticity.\n    \n    d) Explain how to contruct a p-value for $\\beta_1$ under homoskedasticity.\n    \n    e) Explain how to construct a 95\\% confidence interval for $\\beta_1$ under homoskedasticity.\n    \n## Answers to Some Extra Questions\n\n**Answer to Question 2**\n\n$\\beta_1$ is how much $Earnings$ increase on average when $Education$ increases by one year holding $Experience$ and $Female$ constant.\n\n**Answer to Question 3**\n\na) Run the regression\n    \\begin{align*}\n        Earnings &= \\beta_0 + \\beta_1 Education + \\beta_2 Female + \\beta_3 Education \\times Female + U\n    \\end{align*}\n    and test (e.g., calculate a t-statistic and check if it is greater than 1.96 in absolute value) if $\\beta_3=0$.\n\nb) You can run the following regression:\n   \\begin{align*}\n      Earnings &= \\beta_0 + \\beta_1 Education + \\beta_2 Female \\\\\n      & \\hspace{25pt} + \\beta_3 Education \\times Female + \\beta_4 Experience + U\n   \\end{align*}\n   Here, you would still be interested in $\\beta_3$.  If you thought that the return to experience varied for men and women, you might also include an interaction term involving $Experience$ and $Female$. \n\n**Partial Answer to Question 5**\n\na) Starting from \\@ref(eq:V)\n\n  \\begin{align*}\n    V &= \\E\\left[ \\frac{(X - \\E[X])^2 U^2}{\\var(X)^2} \\right] \\\\\n    &= \\frac{1}{\\var(X)^2} \\E[(X-\\E[X])^2 U^2] \\\\\n    &= \\frac{1}{\\var(X)^2} \\E\\big[(X-\\E[X])^2 \\E[U^2|X] \\big] \\\\\n    &= \\frac{1}{\\var(X)^2} \\E[(X-\\E[X])^2 \\sigma^2 ] \\\\\n    &= \\frac{\\sigma^2}{\\var(X)^2} \\E[(X-\\E[X])^2] \\\\\n    &= \\frac{\\sigma^2}{\\var(X)^2} \\var(X) \\\\\n    &= \\frac{\\sigma^2}{\\var(X)}\n  \\end{align*}\n\n  where \n\n  * the second equality holds because $\\var(X)^2$ is non-random and can come out of the expectation, \n    \n  * the third equality uses the law of iterated expectations, \n    \n  * the fourth equality holds by the condition of homoskedasticity, \n    \n  * the fifth equality holds because $\\sigma^2$ is non-random and can come out of the expectation, \n    \n  * the sixth equality holds by the definition of variance, and \n    \n  * the last equality holds by canceling $\\var(X)$ in the numerator with one of the $\\var(X)$'s in the denominator.",
    "supporting": [
      "04-linear_regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}