<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Detailed Course Notes for ECON 4750 - 9&nbsp; Interpreting Regressions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./09-regression_computation.html" rel="next">
<link href="./07-inference.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="4750_style.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./08-interpreting_regressions.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Interpreting Regressions</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Detailed Course Notes for ECON 4750</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Start</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Statistical Programming</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-introduction_to_R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-programming_in_R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Programming in R</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Probability</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-random_variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Random Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-expectations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Expectation, Variance, and More</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Properties of Estimators</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-finite_sample_properties.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Finite Sample Properties</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-asymptotic_properties.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Asymptotic Properties</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Regression</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-interpreting_regressions.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Interpreting Regressions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-regression_computation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Computation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-regression_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Advanced Topics</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-binary_outcomes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Binary Outcome Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Prediction</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-model_selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Model Selection</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-machine_learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Machine Learning</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Causal Inference</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-causal_inference_concepts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Concepts</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-experiments.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Experiments</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-unconfoundedness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Unconfoundedness</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-quasi_experiments.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Quasi-Experiments</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#nonparametric-regression-curse-of-dimensionality" id="toc-nonparametric-regression-curse-of-dimensionality" class="nav-link active" data-scroll-target="#nonparametric-regression-curse-of-dimensionality"><span class="header-section-number">9.1</span> Nonparametric Regression / Curse of Dimensionality</a></li>
  <li><a href="#linear-regression-models" id="toc-linear-regression-models" class="nav-link" data-scroll-target="#linear-regression-models"><span class="header-section-number">9.2</span> Linear Regression Models</a></li>
  <li><a href="#computation" id="toc-computation" class="nav-link" data-scroll-target="#computation"><span class="header-section-number">9.3</span> Computation</a></li>
  <li><a href="#partial-effects" id="toc-partial-effects" class="nav-link" data-scroll-target="#partial-effects"><span class="header-section-number">9.4</span> Partial Effects</a>
  <ul class="collapse">
  <li><a href="#computation-1" id="toc-computation-1" class="nav-link" data-scroll-target="#computation-1"><span class="header-section-number">9.4.1</span> Computation</a></li>
  </ul></li>
  <li><a href="#binary-regressors" id="toc-binary-regressors" class="nav-link" data-scroll-target="#binary-regressors"><span class="header-section-number">9.5</span> Binary Regressors</a>
  <ul class="collapse">
  <li><a href="#computation-2" id="toc-computation-2" class="nav-link" data-scroll-target="#computation-2"><span class="header-section-number">9.5.1</span> Computation</a></li>
  </ul></li>
  <li><a href="#nonlinear-regression-functions" id="toc-nonlinear-regression-functions" class="nav-link" data-scroll-target="#nonlinear-regression-functions"><span class="header-section-number">9.6</span> Nonlinear Regression Functions</a>
  <ul class="collapse">
  <li><a href="#computation-3" id="toc-computation-3" class="nav-link" data-scroll-target="#computation-3"><span class="header-section-number">9.6.1</span> Computation</a></li>
  </ul></li>
  <li><a href="#interpreting-interaction-terms" id="toc-interpreting-interaction-terms" class="nav-link" data-scroll-target="#interpreting-interaction-terms"><span class="header-section-number">9.7</span> Interpreting Interaction Terms</a>
  <ul class="collapse">
  <li><a href="#computation-4" id="toc-computation-4" class="nav-link" data-scroll-target="#computation-4"><span class="header-section-number">9.7.1</span> Computation</a></li>
  </ul></li>
  <li><a href="#elasticities" id="toc-elasticities" class="nav-link" data-scroll-target="#elasticities"><span class="header-section-number">9.8</span> Elasticities</a>
  <ul class="collapse">
  <li><a href="#computation-5" id="toc-computation-5" class="nav-link" data-scroll-target="#computation-5"><span class="header-section-number">9.8.1</span> Computation</a></li>
  </ul></li>
  <li><a href="#omitted-variable-bias" id="toc-omitted-variable-bias" class="nav-link" data-scroll-target="#omitted-variable-bias"><span class="header-section-number">9.9</span> Omitted Variable Bias</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Interpreting Regressions</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><span class="math display">\[
\newcommand{\E}{\mathbb{E}}
\renewcommand{\P}{\textrm{P}}
\let\L\relax
\newcommand{\L}{\textrm{L}} %doesn't work in .qmd, place this command at start of qmd file to use it
\newcommand{\F}{\textrm{F}}
\newcommand{\var}{\textrm{var}}
\newcommand{\cov}{\textrm{cov}}
\newcommand{\corr}{\textrm{corr}}
\newcommand{\Var}{\mathrm{Var}}
\newcommand{\Cov}{\mathrm{Cov}}
\newcommand{\Corr}{\mathrm{Corr}}
\newcommand{\sd}{\mathrm{sd}}
\newcommand{\se}{\mathrm{s.e.}}
\newcommand{\T}{T}
\newcommand{\indicator}[1]{\mathbb{1}\{#1\}}
\newcommand\independent{\perp \!\!\! \perp}
\newcommand{\N}{\mathcal{N}}
\]</span></p>
<p>In this chapter, our interest will shift to conditional expectations, such as <span class="math inline">\(\E[Y|X_1,X_2,X_3]\)</span> (I’ll write <span class="math inline">\(X_1\)</span>, <span class="math inline">\(X_2\)</span>, and <span class="math inline">\(X_3\)</span> in a lot of examples in this chapter, but you can think of there being an arbitrary number of <span class="math inline">\(X\)</span>’s).</p>
<p>I’ll refer to <span class="math inline">\(Y\)</span> as the <strong>outcome</strong>. You might also sometimes heae it called the <strong>dependent variable</strong>.</p>
<p>I’ll refer to the <span class="math inline">\(X\)</span>’s as either <strong>covariates</strong> or <strong>regressors</strong> or <strong>characteristics</strong>. You might also hear them called <strong>independent variables</strong> sometimes.</p>
<p>Before we start to get into the details, let us first discuss why we’re interested in conditional expectations. First, if we are interested in <em>making predictions</em>, it will often be the case that the “best” prediction that one can make is the conditional expectation. This should make sense to you — if you want to make a reasonable prediction about what the outcome will be for a new observation that has characteristics <span class="math inline">\(x_1\)</span>, <span class="math inline">\(x_2\)</span>, and <span class="math inline">\(x_3\)</span>, a good way to do it would be to predict that their outcome would be the same as the mean outcome in the population among those that have the same characteristics; that is, <span class="math inline">\(\E[Y|X_1=x_1, X_2=x_2, X_3=x_3]\)</span>.</p>
<p>Next, in economics, we are often interested in how much some outcome of interest changes when a particular covariate changes, holding other covariates constants. To give some examples, we might be interested in the average return of actively managed mutual funds relative to passively managed mutual funds conditional on investing in assets in the same class (e.g., large cap stocks or international bonds). As another example, we might be interested in the effect of an increase in the amount of fertilizer on average crop yield but while holding constant the temperature and precipitation.</p>
<p>How much the outcome, <span class="math inline">\(Y\)</span>, changes on average when one of the covariates, <span class="math inline">\(X_1\)</span>, changes by 1 unit and holding other covariates constant is what we’ll call the <strong>partial effect</strong> of <span class="math inline">\(X_1\)</span> on <span class="math inline">\(Y\)</span>. Suppose <span class="math inline">\(X_1\)</span> is binary, then it is given by</p>
<p><span class="math display">\[
  PE(x_2,x_3) = \E[Y | X_1=1, X_2=x_2, X_3=x_3] - \E[Y | X_1=0,X_2=x_2,X_3=x_3]
\]</span> Notice that the partial effect can depend on <span class="math inline">\(x_2\)</span> and <span class="math inline">\(x_3\)</span>. For example, it could be that the effect of active management relative to passive management could be different across different asset classes.</p>
<p>Slightly more generally, if <span class="math inline">\(X_1\)</span> is discrete, so that it can take on several different discrete values, then we define the partial effect as</p>
<p><span class="math display">\[
  PE(x_1,x_2,x_3) = \E[Y | X_1=x_1+1, X_2=x_2, X_3=x_3] - \E[Y | X_1=x_1,X_2=x_2,X_3=x_3]
\]</span> which now can depend on <span class="math inline">\(x_1\)</span>, <span class="math inline">\(x_2\)</span>, and <span class="math inline">\(x_3\)</span>. This is the average effect of going from <span class="math inline">\(X_1=x_1\)</span> to <span class="math inline">\(X_1=x_1+1\)</span> holding <span class="math inline">\(x_2\)</span> and <span class="math inline">\(x_3\)</span> constant.</p>
<p>Finally, consider the case where we are interested in the partial effect of <span class="math inline">\(X_1\)</span> which is continuous (for example, the partial effect of fertilizer input on crop yield). In this case the partial effect is given by the <em>partial derivative</em> of <span class="math inline">\(\E[Y|X_1,X_2,X_3]\)</span> with respect to <span class="math inline">\(X_1\)</span>.</p>
<p><span class="math display">\[
  PE(x_1,x_2,x_3) = \frac{\partial \, \E[Y|X_1=x_1, X_2=x_2, X_3=x_3]}{\partial \, x_1}
\]</span> This partial derivative is analogous to what we have been doing before — we are making a small change of <span class="math inline">\(X_1\)</span> while holding <span class="math inline">\(X_2\)</span> and <span class="math inline">\(X_3\)</span> constant at <span class="math inline">\(x_2\)</span> and <span class="math inline">\(x_3\)</span>.</p>
<div class="side-comment">
<p><span class="side-comment">Side-Comment:</span> This is probably the part of the class where we will jump around in the book the most this semester.</p>
<p>The pedagogical approach of the textbook is to introduce the notion of causality very early and to emphasize the requirements on linear regression models in order to deliver causality, while increasing the complexity of the models over several chapters.</p>
<p>This is totally reasonable, but I prefer to start by teaching the mechanics of regressions: how to compute them, how to interpret them (even if you are not able to meet the requirements of causality), and how to use them to make predictions. Then, we’ll have a serious discussion about causality over the last few weeks of the semester.</p>
<p>In practice, this means we’ll cover parts Chapters 4-8 in the textbook now, and then we’ll circle back to some of the issues covered in these chapters again towards the end of the semester.</p>
</div>
<section id="nonparametric-regression-curse-of-dimensionality" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="nonparametric-regression-curse-of-dimensionality"><span class="header-section-number">9.1</span> Nonparametric Regression / Curse of Dimensionality</h2>
<p>If you knew nothing about regressions, it would seem natural to try to estimate <span class="math inline">\(\E[Y|X_1=x_1,X_2=x_2,X_3=x_3]\)</span> by just calculating the average of <span class="math inline">\(Y\)</span> among observations that have values of the regressors equal to <span class="math inline">\(x_1\)</span>, <span class="math inline">\(x_2\)</span>, and <span class="math inline">\(x_3\)</span> (if these are discrete) or that are, in some sense, close to <span class="math inline">\(x_1\)</span>, <span class="math inline">\(x_2\)</span>, and <span class="math inline">\(x_3\)</span> (if these are continuous).</p>
<p>This is actually a pretty attractive idea.</p>
<p>However, you run into the issue that it is practically challenging to do this when the number of regressors starts to get large (i.e., if you have 10 regressors, generally, you would need tons of data to be able to find a suitable number of observations that are “close” to any particular value of the regressors).</p>
<p>Let me give a more concrete example. Suppose that you were trying to estimate mean house price as a function of a house’s characteristics. If the only characteristic of the house that you knew was the number of bedrooms, then it would be pretty easy to just calculate the average house price among houses with 2, 3, 4, etc. bedrooms. Now suppose that you knew both the number of bedrooms and the number of square feet. In this case, if we wanted to estimate mean house prices as a function of these characteristics, we would need to find houses that have the same number of bedrooms and (at least) a similar number of square feet. This starts to “slice” the data that you have more thinly. If you continue with this idea (suppose that you want to estimate mean house price as a function of number of bedrooms, number of bathrooms, number of square feet, what year the house was built in, whether or not it has a basement, what zip code it is located in, etc.) then you will start to stretch your data extremely thin to the point that you may have very few relevant observations (or perhaps no relevant observations) for particular values of the characteristics.</p>
<p>This issue is called the “curse of dimensionality”.</p>
<p>We will focus on linear models for <span class="math inline">\(\E[Y|X_1,X_2,X_3]\)</span> largely to get around the curse of dimensionality.</p>
<div class="side-comment">
<p>This idea of using observations that are very close in terms of characteristics in order to estimate a conditional expectation is called <strong>nonparametric</strong> econometrics/statistics. You can take entire courses (typically graduate-level) on this topic if you were interested. The reason that it is is called nonparametric is that it doesn’t involve making any functional form assumptions (like linearity) but the cost is that it would typically require many more observations (due to the curse of dimensionality).</p>
</div>
</section>
<section id="linear-regression-models" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="linear-regression-models"><span class="header-section-number">9.2</span> Linear Regression Models</h2>
<p>SW 4.1</p>
<p>In order to get around the curse of dimensionality that we discussed in the previous section, we will often an impose a <strong>linear model</strong> for the conditional expectation. For example,</p>
<p><span class="math display">\[
  \E[Y|X] = \beta_0 + \beta_1 X
\]</span> or</p>
<p><span class="math display">\[
  \E[Y|X_1,X_2,X_3] = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \beta_3 X_3
\]</span> If we know the values of <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_1\)</span>, <span class="math inline">\(\beta_2\)</span>, and <span class="math inline">\(\beta_3\)</span>, then it is straighforward for us to make predictions. In particular, suppose that we want to predict the outcome for a new observation with characteristics <span class="math inline">\(x_1\)</span>, <span class="math inline">\(x_2\)</span>, and <span class="math inline">\(x_3\)</span>. Our prediction would be</p>
<p><span class="math display">\[
  \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \beta_3 x_3
\]</span></p>
<div class="example">
<p><span class="example">Example: </span>Suppose that you are studying intergenerational income mobility and that you are interested in predicting a child’s income whose parents’ income was $50,000 and whose mother had 12 years of education. Let <span class="math inline">\(Y\)</span> denote child’s income, <span class="math inline">\(X_1\)</span> denote parents’ income, and <span class="math inline">\(X_2\)</span> denote mother’s education. Further, suppose that <span class="math inline">\(\E[Y|X_1,X_2] = 20,000 + 0.5 X_1 + 1000 X_2\)</span>.</p>
<p>In this case, you would predict child’s income to be</p>
<p><span class="math display">\[
  20,000 + 0.5 (50,000) + 1000(12) = 57,000
\]</span></p>
</div>
<div class="side-comment">
<p><span class="side-comment">Side-Comment:</span></p>
<p>The above model can be equivalently written as <span class="math display">\[\begin{align*}
  Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \beta_3 X_3 + U
\end{align*}\]</span> where <span class="math inline">\(U\)</span> is called the <strong>error term</strong> and satisfies <span class="math inline">\(\E[U|X_1,X_2,X_3] = 0\)</span>. There will be a few times where this formulation will be useful for us.</p>
</div>
</section>
<section id="computation" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="computation"><span class="header-section-number">9.3</span> Computation</h2>
<p>Even if we know that <span class="math inline">\(\E[Y|X_1,X_2,X_3] = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \beta_3 X_3\)</span>, in general, we do not know the values of the population parameters (the <span class="math inline">\(\beta\)</span>’s). This is analogous to the framework in the previous chapter where we were interested in the population parameter <span class="math inline">\(\E[Y]\)</span> and estimated it by <span class="math inline">\(\bar{Y}\)</span>.</p>
<p>In this section, we’ll discuss how to estimate <span class="math inline">\((\beta_0,\beta_1,\beta_2,\beta_3)\)</span> using <code>R</code>. We’ll refer to the estimated values of the parameters as <span class="math inline">\((\hat{\beta}_0, \hat{\beta}_1, \hat{\beta}_2, \hat{\beta}_3)\)</span>. As in the previous section, it will not be the case that the estimated <span class="math inline">\(\hat{\beta}\)</span>’s are exactly equal to the population <span class="math inline">\(\beta\)</span>’s. Later on in this chapter, we will establish properties like consistency (so that, as long as we have a large sample, the estimated <span class="math inline">\(\hat{\beta}\)</span>’s should be “close” to the population <span class="math inline">\(\beta\)</span>’s) and asymptotic normality (so that we can conduct inference).</p>
<p>Also later on in this chapter, we’ll talk about how <code>R</code> itself actually makes these computations.</p>
<p>The main function in <code>R</code> for estimating linear regressions is the <code>lm</code> function (<code>lm</code> stands for linear model). The key things to specify for running a regression in <code>R</code> are a <code>formula</code> argument which tells <code>lm</code> which variables are the outcome and which variables are the regressors and a <code>data</code> argument which tells the <code>lm</code> command what data we are using to estimate the regression. Let’s give an example using the <code>mtcars</code> data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>reg <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> hp <span class="sc">+</span> wt, <span class="at">data=</span>mtcars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>What this line of code does is to run a regression. The formula is <code>mpg ~ hp + wt</code>. In other words <code>mpg</code> (standing for miles per gallon) is the outcome, and we are running a regression on <code>hp</code> (horse power) and <code>wt</code> (weight). The <code>~</code> symbol is a “tilde”. In order to add regressors, we separate them with a <code>+</code>. The second argument <code>data=mtcars</code> says to use the <code>mtcars</code> data. All of the variables in the formula need to correspond to column names in the data. We saved the results of the regression in a variable called <code>reg</code>. It’s most common to report the results of the regression using the <code>summary</code> command.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ hp + wt, data = mtcars)

Residuals:
   Min     1Q Median     3Q    Max 
-3.941 -1.600 -0.182  1.050  5.854 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 37.22727    1.59879  23.285  &lt; 2e-16 ***
hp          -0.03177    0.00903  -3.519  0.00145 ** 
wt          -3.87783    0.63273  -6.129 1.12e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.593 on 29 degrees of freedom
Multiple R-squared:  0.8268,    Adjusted R-squared:  0.8148 
F-statistic: 69.21 on 2 and 29 DF,  p-value: 9.109e-12</code></pre>
</div>
</div>
<p>The main thing that this reports is the estimated parameters. Our estimate of the “Intercept” (i.e., this is <span class="math inline">\(\hat{\beta}_0\)</span>) is in the first row of the table; our estimate is <code>37.227</code>. The estimated coefficient on <code>hp</code> is <code>-0.0318</code>, and the estimated coefficient on <code>wt</code> is <code>-3.878</code>.</p>
<p>You can also see standard errors for each estimated parameter, a t-statistic, and a p-value in the other columns. We will talk about these in more detail in the next section.</p>
<p>For now, we’ll also ignore the information provided at the bottom of the summary.</p>
<p>Now that we have estimated the parameters, we can use these to predict <span class="math inline">\(mpg\)</span> given a value of <span class="math inline">\(hp\)</span> and <span class="math inline">\(wt\)</span>. For example, suppose that you wanted to predict the <span class="math inline">\(mpg\)</span> of a 2500 pound car (note: weight in <span class="math inline">\(mtcars\)</span> is in 1000s of pounds) and 120 horsepower car, you could compute</p>
<p><span class="math display">\[
  37.227 - 0.0318(120) - 3.878(2.5) = 23.716
\]</span> Alternatively, there is a built-in function in <code>R</code> called <code>predict</code> that can be used to generate predicted values. We just need to specify the values that we would like to get predicted values for by passing in a data frame with the relevant columns though the <code>newdata</code> argument. For example,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(reg, <span class="at">newdata=</span><span class="fu">data.frame</span>(<span class="at">hp=</span><span class="dv">120</span>,<span class="at">wt=</span><span class="fl">2.5</span>))</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(pred,<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    1 
23.72 </code></pre>
</div>
</div>
<div class="side-comment">
<p>A popular alternative to <code>R</code>’s <code>lm</code> function is the <code>lm_robust</code> function from the <code>estimatr</code> package. This provides different standard errors from the default standard errors provided by <code>lm</code> that are, at least in most applications in economics, typically a better choice — we’ll have a further discussion on this topic when we talk about inference later on in this chapter.</p>
</div>
</section>
<section id="partial-effects" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="partial-effects"><span class="header-section-number">9.4</span> Partial Effects</h2>
<p>As we discussed in the beginning of this chapter, besides predicting outcomes, a second main goal for us is to think about partial effects of a regressor on the outcome. We’ll consider partial effects over the next few sections.</p>
<p>In the model, <span class="math display">\[\begin{align*}
  \E[Y | X_1, X_2, X_3]  &amp;= \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \beta_3 X_3
\end{align*}\]</span></p>
<p>If <span class="math inline">\(X_1\)</span> is continuous, then <span class="math display">\[\begin{align*}
  \beta_1 = \frac{\partial \E[Y|X_1,X_2,X_3]}{\partial X_1}
\end{align*}\]</span></p>
<p>Thus, <span class="math inline">\(\beta_1\)</span> is the partial effect of <span class="math inline">\(X_1\)</span> on <span class="math inline">\(Y\)</span>. In other words, <span class="math inline">\(\beta_1\)</span> should be interpreted as how much <span class="math inline">\(Y\)</span> increases, on average, when <span class="math inline">\(X_1\)</span> increases by one unit holding <span class="math inline">\(X_2\)</span> and <span class="math inline">\(X_3\)</span> constant. <em>Make sure to get this interpretation right!</em></p>
<div class="example">
<p><span class="example">Example: </span>Continuing the same example as above about intergenerational income mobility and where <span class="math inline">\(Y\)</span> denotes child’s income, <span class="math inline">\(X_1\)</span> denotes parents’ income, <span class="math inline">\(X_2\)</span> denotes mother’s education, and</p>
<p><span class="math display">\[
  \E[Y|X_1,X_2] = 20,000 + 0.5 X_1 + 1000 X_2
\]</span> The partial effect of parents’ income on child’s income is 0.5. This means that, for every one dollar increase in parents’ income, child’s income is 0.5 dollars higher on average holding mother’s education constant.</p>
</div>
<section id="computation-1" class="level3" data-number="9.4.1">
<h3 data-number="9.4.1" class="anchored" data-anchor-id="computation-1"><span class="header-section-number">9.4.1</span> Computation</h3>
<p>Let’s run the same regression as in the previous section, but think about partial effects in this case.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>reg1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> hp <span class="sc">+</span> wt, <span class="at">data=</span>mtcars)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ hp + wt, data = mtcars)

Residuals:
   Min     1Q Median     3Q    Max 
-3.941 -1.600 -0.182  1.050  5.854 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 37.22727    1.59879  23.285  &lt; 2e-16 ***
hp          -0.03177    0.00903  -3.519  0.00145 ** 
wt          -3.87783    0.63273  -6.129 1.12e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.593 on 29 degrees of freedom
Multiple R-squared:  0.8268,    Adjusted R-squared:  0.8148 
F-statistic: 69.21 on 2 and 29 DF,  p-value: 9.109e-12</code></pre>
</div>
</div>
<p>The partial effect of horsepower on miles per gallon is -0.032. In other words, we estimate that if horsepower increases by one then, on average, miles per gallon decreases by 0.032 holding weight constant.</p>
<p>The t-statistic and p-value are computed for the null hypothesis that the corresponding coefficient is equal to 0. For example, for <code>hp</code> the t-statistic is equal to <code>-3.519</code> which is greater than 1.96 and indicates that the partial effect of <code>hp</code> is statistically significant at a 5% significance level. The corresponding p-value for <code>hp</code> is <code>0.0145</code> indicating that there is only about a 1.5% chance of getting a t-statistic this extreme if the partial effect of <code>hp</code> were actually 0 (i.e., under <span class="math inline">\(H_0 : \beta_1=0\)</span>).</p>
<div class="practice">
<p><span class="practice">Practice: </span>What is the partial effect of <code>wt</code> in the previous example? Provide a careful interpretation. Is the partial effect of <code>wt</code> statistically significant? Explain. What is the p-value for <code>wt</code>? How do you interpret the p-value?</p>
</div>
<div class="side-comment">
<p><span class="side-comment">Side-Comment:</span> One horsepower is a very small increase in horsepower, so it might be a good idea to multiply the coefficient by some larger number, say 50. In this case, we could say that we estimate that if horsepower increases by 50 then, on average, miles per gallon decreases by 1.59 (<span class="math inline">\(=50 \times 0.03177\)</span>) holding weight constant. From the above discussion, we know that this effect is statistically different from 0. That said, it is not clear to me if we should interpret this as a large partial effect; I do not know too much about cars, but a 50 horsepower increase seems rather large while a 1.59 decrease in miles per gallon seems relatively small (at least to me).</p>
</div>
</section>
</section>
<section id="binary-regressors" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="binary-regressors"><span class="header-section-number">9.5</span> Binary Regressors</h2>
<p>SW 5.3</p>
<p>Let’s continue with the same model as above</p>
<p><span class="math display">\[
  \E[Y|X_1,X_2,X_3] = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \beta_3 X_3
\]</span></p>
<p>If <span class="math inline">\(X_1\)</span> is discrete (let’s say binary): <span class="math display">\[\begin{align*}
  \beta_1 = \E[Y|X_1=1,X_2,X_3] - \E[Y|X_1=0,X_2,X_3]
\end{align*}\]</span> <span class="math inline">\(\beta_1\)</span> is still the partial effect of <span class="math inline">\(X_1\)</span> on <span class="math inline">\(Y\)</span> and should be interpreted as how much <span class="math inline">\(Y\)</span> increases, on average, when <span class="math inline">\(X_1\)</span> changes from 0 to 1, holding <span class="math inline">\(X_2\)</span> and <span class="math inline">\(X_3\)</span> constant.</p>
<p>If <span class="math inline">\(X_1\)</span> can take more than just the values 0 and 1, but is still discrete (an example is a person’s years of education), then</p>
<p><span class="math display">\[
  \beta_1 = \E[Y | X_1=x_1+1, X_2, X_3] - \E[Y|X_1=x_1, X_2, X_3]
\]</span> which holds for any possible value that <span class="math inline">\(X_1\)</span> could take, so that <span class="math inline">\(\beta_1\)</span> is the effect of a 1 unit increase in <span class="math inline">\(X_1\)</span> on <span class="math inline">\(Y\)</span>, on average, holding constant <span class="math inline">\(X_2\)</span> and <span class="math inline">\(X_3\)</span>.</p>
<div class="example">
<p><span class="example">Example: </span>Suppose that you work for an airline and you are interested in predicting the number of passengers for a Saturday morning flight from Atlanta to Memphis. Let <span class="math inline">\(Y\)</span> denote the number of passengers, <span class="math inline">\(X_1\)</span> be equal to 1 for a morning flight and 0 otherwise, and let <span class="math inline">\(X_2\)</span> be equal to 1 for a weekday flight and 0 otherwise. Further suppose that <span class="math inline">\(\E[Y|X_1,X_2] = 80 + 20 X_1 - 15 X_2\)</span>.</p>
<p>In this case, you would predict,</p>
<p><span class="math display">\[
  80 + 20 (1) - 15 (0) = 100
\]</span> passengers on the flight.</p>
<p>In addition, the partial effect of being morning flight is equal to 20. This indicates that, on average, morning flights have 20 more passengers than non-morning flights holding whether or not the flight occurs on a weekday constant.</p>
</div>
<section id="computation-2" class="level3" data-number="9.5.1">
<h3 data-number="9.5.1" class="anchored" data-anchor-id="computation-2"><span class="header-section-number">9.5.1</span> Computation</h3>
<p>In order to include a binary or discrete covariate in a regression in <code>R</code> is straightforward. The following regression uses the <code>mtcars</code> data and adds a binary regressor, <code>am</code>, indicating whether or not a car has an automatic transmission.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>reg2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> hp <span class="sc">+</span> wt <span class="sc">+</span> am, <span class="at">data=</span>mtcars)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ hp + wt + am, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.4221 -1.7924 -0.3788  1.2249  5.5317 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 34.002875   2.642659  12.867 2.82e-13 ***
hp          -0.037479   0.009605  -3.902 0.000546 ***
wt          -2.878575   0.904971  -3.181 0.003574 ** 
am           2.083710   1.376420   1.514 0.141268    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.538 on 28 degrees of freedom
Multiple R-squared:  0.8399,    Adjusted R-squared:  0.8227 
F-statistic: 48.96 on 3 and 28 DF,  p-value: 2.908e-11</code></pre>
</div>
</div>
<p>In this example, cars that had an automatic transmission got about 2 more miles per gallon than cars that had an automatic transmission on average, holding horsepower and weight constant (though the p-value is only 0.14).</p>
</section>
</section>
<section id="nonlinear-regression-functions" class="level2" data-number="9.6">
<h2 data-number="9.6" class="anchored" data-anchor-id="nonlinear-regression-functions"><span class="header-section-number">9.6</span> Nonlinear Regression Functions</h2>
<p>SW 8.1, 8.2</p>
<p>Also, please read all of SW Ch. 8</p>
<p>So far, the the partial effects that we have been interested in have corresponded to a particular parameter in the regression, usually <span class="math inline">\(\beta_1\)</span>. I think this can sometimes be a source of confusion as, at least in my view, we are not typically interested in the parameters for their own sake, but rather are interested in partial effects. It just so happens that in some leading cases, they coincide.</p>
<p>In addition, while the <span class="math inline">\(\beta\)</span>’s in the sort of models we have considered so far are easy to interpret, in some cases, it might be <em>restrictive</em> to think that the partial effects are the same across different values of the covariates.</p>
<p>In this section, we’ll see the first of several cases where partial effects do not coincide with a particular parameter.</p>
<p>Suppose that</p>
<p><span class="math display">\[
  \E[Y|X_1,X_2,X_3] = \beta_0 + \beta_1 X_1 + \beta_2 X_1^2 + \beta_3 X_2 + \beta_4 X_3
\]</span></p>
<p>Let’s start with making predictions using this model. If you know the values of <span class="math inline">\(\beta_0,\beta_1,\beta_2,\beta_3,\)</span> and <span class="math inline">\(\beta_4\)</span>, then to get a prediction, you would still just plug in the values of the regressors that you’d like to get a prediction for (including <span class="math inline">\(x_1^2\)</span>).</p>
<p>Next, in this model, the partial effect of <span class="math inline">\(X_1\)</span> is given by</p>
<p><span class="math display">\[
  \frac{\partial \, \E[Y|X_1,X_2,X_3]}{\partial \, X_1} = \beta_1 + 2\beta_2 X_1
\]</span> In other words, the partial effect of <span class="math inline">\(X_1\)</span> depends on the value that <span class="math inline">\(X_1\)</span> takes.</p>
<p>In this case, it is sometimes useful to report the partial effect for some different values of <span class="math inline">\(X_1\)</span>. In other cases, it is useful to report the <strong>average partial effect</strong> (APE) which is the mean of the partial effects across the distribution of the covariates. In this case, the APE is given by</p>
<p><span class="math display">\[
  APE = \beta_1 + 2 \beta_2 \E[X_1]
\]</span> and, once you have estimated the regression, you can compute an estimate of <span class="math inline">\(APE\)</span> by</p>
<p><span class="math display">\[
  \widehat{APE} = \hat{\beta}_1 + 2 \hat{\beta}_2 \bar{X}_1
\]</span></p>
<div class="example">
<p><span class="example">Example: </span>Let’s continue our example on intergenerational income mobility where <span class="math inline">\(Y\)</span> denotes child’s income, <span class="math inline">\(X_1\)</span> denotes parents’ income, and <span class="math inline">\(X_2\)</span> denotes mother’s education. Now, suppose that</p>
<p><span class="math display">\[
  \E[Y|X_1,X_2] = 15,000 + 0.7 X_1 - 0.000002 X_1^2 + 800 X_2
\]</span> Then, predicted child’s income when parents’ income is equal to $50,000 is given by</p>
<p><span class="math display">\[
  15,000 + 0.7 (50,000) - 0.000002 (50,000)^2 + 800 (12) = 54,600
\]</span> In addition, the partial effect of parents’ income is given by</p>
<p><span class="math display">\[
  0.7 - 0.000004 X_1
\]</span> Let’s compute a few different partial effects for different values of parents’ income</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(X_1\)</span></th>
<th style="text-align: center;">PE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">20,000</td>
<td style="text-align: center;">0.62</td>
</tr>
<tr class="even">
<td style="text-align: center;">50,000</td>
<td style="text-align: center;">0.50</td>
</tr>
<tr class="odd">
<td style="text-align: center;">100,000</td>
<td style="text-align: center;">0.30</td>
</tr>
</tbody>
</table>
<p>which indicates that the partial effect of parents’ income is decreasing — i.e., the effect of additional parents’ income is largest for children whose parents have the lowest income and gets smaller for those whose parents have high incomes.</p>
<p>Finally, if you wanted to compute the <span class="math inline">\(APE\)</span>, you would just plug in <span class="math inline">\(\E[X_1]\)</span> (or <span class="math inline">\(\bar{X}_1\)</span>) into the expression for the partial effect.</p>
</div>
<section id="computation-3" class="level3" data-number="9.6.1">
<h3 data-number="9.6.1" class="anchored" data-anchor-id="computation-3"><span class="header-section-number">9.6.1</span> Computation</h3>
<p>Including a quadratic (or other higher order term) in <code>R</code> is relatively straightforward. Let’s just do an example.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>reg3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> hp <span class="sc">+</span> <span class="fu">I</span>(hp<span class="sc">^</span><span class="dv">2</span>), <span class="at">data=</span>mtcars)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ hp + I(hp^2), data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.5512 -1.6027 -0.6977  1.5509  8.7213 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.041e+01  2.741e+00  14.744 5.23e-15 ***
hp          -2.133e-01  3.488e-02  -6.115 1.16e-06 ***
I(hp^2)      4.208e-04  9.844e-05   4.275 0.000189 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.077 on 29 degrees of freedom
Multiple R-squared:  0.7561,    Adjusted R-squared:  0.7393 
F-statistic: 44.95 on 2 and 29 DF,  p-value: 1.301e-09</code></pre>
</div>
</div>
<p>The only thing that is new here is <code>I(hp^2)</code>. The <code>I</code> function stands for inhibit (you can read the documentation using <code>?I</code>). For us, this is not too important. You can understand it like this: there is no variable names <code>hp^2</code> in the data, but if we put the name of a variable that is in the data (here: <code>hp</code>) then we can apply a function to it (here: squaring it) before including it as a regressor.</p>
<p>Interestingly, here it seems there are nonlinear effects of horsepower on miles per gallon. Let’s just quickly report the estimated partial effects for a few different values of horsepower.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>hp_vec <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">100</span>,<span class="dv">200</span>,<span class="dv">300</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># there might be a native function in r</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co"># to compute these partial effects; I just</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># don't know it.</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>pe <span class="ot">&lt;-</span> <span class="cf">function</span>(hp) {</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># partial effect is b1 + 2b2*hp</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  pes <span class="ot">&lt;-</span> <span class="fu">coef</span>(reg3)[<span class="dv">2</span>] <span class="sc">+</span> <span class="dv">2</span><span class="sc">*</span><span class="fu">coef</span>(reg3)[<span class="dv">3</span>]<span class="sc">*</span>hp</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># print using a data frame</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">hp=</span>hp, <span class="at">pe=</span><span class="fu">round</span>(pes,<span class="dv">3</span>))</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="fu">pe</span>(hp_vec)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   hp     pe
1 100 -0.129
2 200 -0.045
3 300  0.039</code></pre>
</div>
</div>
<p>which suggests that the partial effect of horsepower on miles per gallon is large (though negative) at small values of horsepower and decreasing up to essentially no effect at larger values of horsepower.</p>
</section>
</section>
<section id="interpreting-interaction-terms" class="level2" data-number="9.7">
<h2 data-number="9.7" class="anchored" data-anchor-id="interpreting-interaction-terms"><span class="header-section-number">9.7</span> Interpreting Interaction Terms</h2>
<p>SW 8.3</p>
<p>Another way to allow for partial effects that vary across different values of the regressors is to include <strong>interaction terms</strong>.</p>
<p>Consider the following regression model</p>
<p><span class="math display">\[
  \E[Y|X_1,X_2,X_3] = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \beta_3 X_1 X_2 + \beta_4 X_3
\]</span></p>
<p>The term <span class="math inline">\(X_1 X_2\)</span> is called the interaction term. In this model, the partial effect of <span class="math inline">\(X_1\)</span> is given by</p>
<p><span class="math display">\[
  \frac{\partial \, \E[Y|X_1,X_2,X_3]}{\partial \, X_1} = \beta_1 + \beta_3 X_2
\]</span></p>
<p>In this model, the effect of <span class="math inline">\(X_1\)</span> varies with <span class="math inline">\(X_2\)</span>. As in the previous section, you could report the partial effect for different values of <span class="math inline">\(X_2\)</span> or consider <span class="math inline">\(APE = \beta_1 + \beta_3 \E[X_2]\)</span>.</p>
<p>There are a couple of other things worth pointing out for interaction terms</p>
<ul>
<li><p>It is very common for one of the interaction terms, say, <span class="math inline">\(X_2\)</span> to be a binary variable. This gives a way to easily test if the effect of <span class="math inline">\(X_1\)</span> is the same across the two “groups” defined by <span class="math inline">\(X_2\)</span>. For example, suppose you wanted to check if the partial effect of education was the same for men and women. You could run a regression like</p>
<p><span class="math display">\[
    Wage = \beta_0 + \beta_1 Education + \beta_2 Female + \beta_3 Education \cdot Female + U
  \]</span></p>
<p>From the previous discussion, the partial effect of education is given by</p>
<p><span class="math display">\[
    \beta_1 + \beta_3 Female
  \]</span></p>
<p>Thus, the partial effect education for men is given by <span class="math inline">\(\beta_1\)</span>, and the partial effect of education for women is given by <span class="math inline">\(\beta_1 + \beta_3\)</span>. Thus, if you want to test if the partial effect of education differs for men and women, you can just test if <span class="math inline">\(\beta_3=0\)</span>. If <span class="math inline">\(\beta_3&gt;0\)</span>, it suggests a higher partial effect of education for women, and if <span class="math inline">\(\beta_3 &lt; 0\)</span>, it suggests a lower partial effect of education for women.</p></li>
<li><p>Another interesting case is when <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span> are both binary. In this case, a model that includes an interaction term is called a <strong>saturated model</strong>. It is called this because it is actually nonparametric. In particular, notice that in the model <span class="math inline">\(\E[Y|X_1,X_2] = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \beta_3 X_1 X_2\)</span>,</p>
<p><span class="math display">\[
  \begin{aligned}
    \E[Y|X_1=0,X_2=0] &amp;= \beta_0 \\
    \E[Y|X_1=1,X_2=0] &amp;= \beta_0 + \beta_1 \\
    \E[Y|X_1=0,X_2=1] &amp;= \beta_0 + \beta_2 \\
    \E[Y|X_1=1,X_2=1] &amp;= \beta_0 + \beta_1 + \beta_2 + \beta_3
  \end{aligned}
  \]</span></p>
<p>This exhausts all possible combinations of the regressors and means that you can recover each possible value of the conditional expectation from the parameters of the model.</p>
<p>It would be possible to write down a saturated model in cases with more than two binary regressors (or even discrete regressors) — you would just need to include more interaction terms. The key thing is that there be no continuous regressors. That said, as you start to add more and more discrete regressors and their interactions, you will effectively start to run into the curse of dimensionality issues that we discussed earlier.</p>
<p>As an example, consider our earlier example of flights from Atlanta to Memphis where <span class="math inline">\(Y\)</span> denoted the number of passengers, <span class="math inline">\(X_1\)</span> was equal to 1 for a a morning flight and 0 otherwise, and <span class="math inline">\(X_2\)</span> was equal to one for a weekday flight and 0 otherwise. Suppose that <span class="math inline">\(\E[Y|X_1,X_2] = 90 - 15 X_1 - 5 X_2 + 25 X_1 X_2\)</span>. Then,</p>
<p><span class="math display">\[
  \begin{aligned}
    \E[Y|X_1=0,X_2=0] &amp;= 90 \quad &amp; \textrm{non-morning, weekend} \\
    \E[Y|X_1=1,X_2=0] &amp;= 90 - 15 = 75 \quad &amp; \textrm{morning, weekend} \\
    \E[Y|X_1=0,X_2=1] &amp;= 90 - 5 = 85 \quad  &amp; \textrm{non-morning, weekday} \\
    \E[Y|X_1=1,X_2=1] &amp;= 90 - 15 - 5 + 25 = 100 \quad &amp; \textrm{morning, weekend}
  \end{aligned}
  \]</span></p></li>
</ul>
<section id="computation-4" class="level3" data-number="9.7.1">
<h3 data-number="9.7.1" class="anchored" data-anchor-id="computation-4"><span class="header-section-number">9.7.1</span> Computation</h3>
<p>Including interaction terms in regressions in <code>R</code> is straightforward. Using the <code>mtcars</code> data, we can do it as follows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>reg4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> hp <span class="sc">+</span> wt <span class="sc">+</span> am <span class="sc">+</span> hp<span class="sc">*</span>am, <span class="at">data=</span>mtcars)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ hp + wt + am + hp * am, data = mtcars)

Residuals:
   Min     1Q Median     3Q    Max 
-3.435 -1.510 -0.697  1.284  5.245 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 33.34196    2.79711  11.920 2.89e-12 ***
hp          -0.02918    0.01449  -2.014  0.05407 .  
wt          -3.05617    0.94036  -3.250  0.00309 ** 
am           3.55141    2.35742   1.506  0.14355    
hp:am       -0.01129    0.01466  -0.770  0.44809    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.556 on 27 degrees of freedom
Multiple R-squared:  0.8433,    Adjusted R-squared:  0.8201 
F-statistic: 36.33 on 4 and 27 DF,  p-value: 1.68e-10</code></pre>
</div>
</div>
<p>The interaction term in the results is in the row that starts with <code>hp:am</code>. These estimates suggest that, while horsepower does seem to decrease miles per gallon controlling for weight and whether or not the car has an automatic transmission, the effect of horsepower does not seem to vary much by whether or not the car has an automatic transmission (at least not in a big enough way that we can detect it with the data that we have).</p>
</section>
</section>
<section id="elasticities" class="level2" data-number="9.8">
<h2 data-number="9.8" class="anchored" data-anchor-id="elasticities"><span class="header-section-number">9.8</span> Elasticities</h2>
<p>SW 8.2</p>
<p>Economists are often interested in <strong>elasticities</strong>, that is, the percentage change in <span class="math inline">\(Y\)</span> when <span class="math inline">\(X\)</span> changes by 1%.</p>
<p>Recall that the definition of percentage change of moving from, say, <span class="math inline">\(x_{old}\)</span> to <span class="math inline">\(x_{new}\)</span> is given by</p>
<p><span class="math display">\[
  \textrm{\% change} = \frac{x_{new} - x_{old}}{x_{old}} \times 100
\]</span></p>
<p>Elasticities are closely connected to natural logarithms; following the most common notation in economics, we’ll refer to the natural logarithm using the notation: <span class="math inline">\(\log\)</span>. Further, recall that the derivative of the <span class="math inline">\(\log\)</span> function is given by</p>
<p><span class="math display">\[
  \frac{d \, \log(x)}{d \, x} = \frac{1}{x} \implies d\, \log(x) = \frac{d \, x}{x}
\]</span> which further implies that</p>
<p><span class="math display">\[
  \Delta \log(x) := \log(x_{new}) - \log(x_{old}) \approx \frac{x_{new} - x_{old}}{x_{old}}
\]</span> and, thus, that</p>
<p><span class="math display">\[
  100 \cdot \Delta \log(x) \approx \textrm{\% change}
\]</span> where the approximation is better when <span class="math inline">\(x_{new}\)</span> and <span class="math inline">\(x_{old}\)</span> are close to each other.</p>
<p>Now, we’ll use these properties of logarithms in order to interpret several linear models</p>
<ul>
<li><p>For simplicity, I am going to not include an error term or extra covariates, but you should continue to interpret parameter estimates as “on average” and “holding other regressors constant” (if there are other regressors in the model).</p></li>
<li><p><strong>Log-Log</strong> Model</p>
<p><span class="math display">\[
  \log(Y) = \beta_0 + \beta_1 \log(X)
  \]</span></p>
<p>In this case,</p>
<p><span class="math display">\[
  \begin{aligned}
  \beta_1 &amp;= \frac{ d \, \log(Y) }{d \, \log(X)} \\
  &amp;= \frac{ d \, \log(Y) \cdot 100 }{d \, \log(X) \cdot 100} \\
  &amp;\approx \frac{ \% \Delta Y}{ \% \Delta X}
  \end{aligned}
  \]</span></p>
<p>All that to say, in a regression of the log of an outcome on the log of a regressor, you should interpret the corresponding coefficient as the average percentage change in the outcome when the regressor changes by 1%. The log-log model is sometimes called a <strong>constant elasticity</strong> model.</p></li>
<li><p><strong>Log-Level</strong> model</p>
<p><span class="math display">\[
  \log(Y) = \beta_0 + \beta_1 X
  \]</span></p>
<p>In this case,</p>
<p><span class="math display">\[
  \begin{aligned}
  \beta_1 &amp;= \frac{ d \, \log(Y) }{d \, X} \\
  \implies 100 \beta_1 &amp;= \frac{ d \, \log(Y) \cdot 100 }{d \, X} \\
  \implies 100 \beta_1 &amp;\approx \frac{ \% \Delta Y}{ d \, X}
  \end{aligned}
  \]</span></p>
<p>Thus, in a regression of the log of an outcome on the <em>level</em> of a regressor, you should multiply the corresponding coefficient by 100 and interpret it as the average percentage change in the outcome when the regressor changes by 1 unit.</p></li>
<li><p><strong>Level-Log</strong> model</p>
<p><span class="math display">\[
    Y = \beta_0 + \beta_1 \log(X)
  \]</span></p>
<p>In this case,</p>
<p><span class="math display">\[
    \begin{aligned}
    \beta_1 &amp;= \frac{d\, Y}{d \, \log(X)} \\
    \implies \frac{\beta_1}{100} &amp;= \frac{d \, Y}{d \, \log(X) \cdot 100} \\
    \implies \frac{\beta_1}{100} &amp;\approx \frac{d \, Y}{\% \Delta X}
    \end{aligned}
  \]</span></p>
<p>Thus, in a regression of the level of an outcome on the log of a regressor, you should divide the corresponding coefficient by 100 and interpret it as the average change in the outcome when the regressor changes by 1%.</p></li>
</ul>
<div class="example">
<p><span class="example">Example: </span>Let’s continue the same example on intergenerational income mobility where <span class="math inline">\(Y\)</span> denotes child’s income, <span class="math inline">\(X_1\)</span> denotes parents’ income and <span class="math inline">\(X_2\)</span> denotes mother’s education. We’ll consider how to interpret several different models.</p>
<p><span class="math display">\[
  \log(Y) = 8.8 + 0.4 \log(X_1) + 0.008 X_2 + U
\]</span> In this model, we estimate that, on average, when parents’ income increases by 1%, child’s income increases by 0.4% holding mother’s education constant.</p>
<p>Next, consider, <span class="math display">\[
  \log(Y) = 8.9 + 0.00004 X_1 + 0.007 X_2 + U
\]</span> In this model, we estimate that, on average, when parents’ income increases by $1, child’s income increases by 0.004% (alternatively, when parents’ income increase by $1000, child’s income increases by 4%) holding mother’s education constant.</p>
<p>Finally, consider</p>
<p><span class="math display">\[
  Y = -1,680,000 + 160,000 \log(X_1) + 900 X_2 + U
\]</span> In this case, we estimate that, on average, when parents’ income increases by 1%, child’s income increases by $1,600 holding mother’s education constant.</p>
</div>
<section id="computation-5" class="level3" data-number="9.8.1">
<h3 data-number="9.8.1" class="anchored" data-anchor-id="computation-5"><span class="header-section-number">9.8.1</span> Computation</h3>
<p>Estimating models that include logarithms in <code>R</code> is straightforward.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>reg5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(mpg) <span class="sc">~</span> <span class="fu">log</span>(hp) <span class="sc">+</span> wt, <span class="at">data=</span>mtcars) </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>reg6 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(mpg) <span class="sc">~</span> hp <span class="sc">+</span> wt, <span class="at">data=</span>mtcars) </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>reg7 <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> <span class="fu">log</span>(hp) <span class="sc">+</span> wt, <span class="at">data=</span>mtcars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s show the results all at once using the <code>modelsummary</code> function from the <code>modelsummary</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(modelsummary)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>model_list <span class="ot">&lt;-</span> <span class="fu">list</span>(reg5, reg6, reg7)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">modelsummary</span>(model_list)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<!-- preamble start -->

    <script>
      function styleCell_1rfi612szz2d43nokbnw(i, j, css_id) {
        var table = document.getElementById("tinytable_1rfi612szz2d43nokbnw");
        table.rows[i].cells[j].classList.add(css_id);
      }
      function insertSpanRow(i, colspan, content) {
        var table = document.getElementById('tinytable_1rfi612szz2d43nokbnw');
        var newRow = table.insertRow(i);
        var newCell = newRow.insertCell(0);
        newCell.setAttribute("colspan", colspan);
        // newCell.innerText = content;
        // this may be unsafe, but innerText does not interpret <br>
        newCell.innerHTML = content;
      }
      function spanCell_1rfi612szz2d43nokbnw(i, j, rowspan, colspan) {
        var table = document.getElementById("tinytable_1rfi612szz2d43nokbnw");
        const targetRow = table.rows[i];
        const targetCell = targetRow.cells[j];
        for (let r = 0; r < rowspan; r++) {
          // Only start deleting cells to the right for the first row (r == 0)
          if (r === 0) {
            // Delete cells to the right of the target cell in the first row
            for (let c = colspan - 1; c > 0; c--) {
              if (table.rows[i + r].cells[j + c]) {
                table.rows[i + r].deleteCell(j + c);
              }
            }
          }
          // For rows below the first, delete starting from the target column
          if (r > 0) {
            for (let c = colspan - 1; c >= 0; c--) {
              if (table.rows[i + r] && table.rows[i + r].cells[j]) {
                table.rows[i + r].deleteCell(j);
              }
            }
          }
        }
        // Set rowspan and colspan of the target cell
        targetCell.rowSpan = rowspan;
        targetCell.colSpan = colspan;
      }
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(0, 0, 'tinytable_css_id4yuxzwpgqges7ohu1sdz') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(0, 1, 'tinytable_css_id81xce0ext26ic75sljhk') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(0, 2, 'tinytable_css_id81xce0ext26ic75sljhk') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(0, 3, 'tinytable_css_id81xce0ext26ic75sljhk') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(1, 0, 'tinytable_css_idretnvgov3cra64izox1t') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(1, 1, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(1, 2, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(1, 3, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(2, 0, 'tinytable_css_idretnvgov3cra64izox1t') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(2, 1, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(2, 2, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(2, 3, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(3, 0, 'tinytable_css_idretnvgov3cra64izox1t') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(3, 1, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(3, 2, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(3, 3, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(4, 0, 'tinytable_css_idretnvgov3cra64izox1t') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(4, 1, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(4, 2, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(4, 3, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(5, 0, 'tinytable_css_idretnvgov3cra64izox1t') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(5, 1, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(5, 2, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(5, 3, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(6, 0, 'tinytable_css_idretnvgov3cra64izox1t') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(6, 1, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(6, 2, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(6, 3, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(7, 0, 'tinytable_css_idretnvgov3cra64izox1t') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(7, 1, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(7, 2, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(7, 3, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(8, 0, 'tinytable_css_idw8zqd28qqyk08pmasp39') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(8, 1, 'tinytable_css_idvh9eg37o3mqq7t7vpnlc') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(8, 2, 'tinytable_css_idvh9eg37o3mqq7t7vpnlc') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(8, 3, 'tinytable_css_idvh9eg37o3mqq7t7vpnlc') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(9, 0, 'tinytable_css_idretnvgov3cra64izox1t') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(9, 1, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(9, 2, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(9, 3, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(10, 0, 'tinytable_css_idretnvgov3cra64izox1t') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(10, 1, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(10, 2, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(10, 3, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(11, 0, 'tinytable_css_idretnvgov3cra64izox1t') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(11, 1, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(11, 2, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(11, 3, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(12, 0, 'tinytable_css_idretnvgov3cra64izox1t') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(12, 1, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(12, 2, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(12, 3, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(13, 0, 'tinytable_css_idretnvgov3cra64izox1t') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(13, 1, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(13, 2, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(13, 3, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(14, 0, 'tinytable_css_idretnvgov3cra64izox1t') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(14, 1, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(14, 2, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(14, 3, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(15, 0, 'tinytable_css_idretnvgov3cra64izox1t') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(15, 1, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(15, 2, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(15, 3, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(16, 0, 'tinytable_css_idretnvgov3cra64izox1t') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(16, 1, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(16, 2, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
window.addEventListener('load', function () { styleCell_1rfi612szz2d43nokbnw(16, 3, 'tinytable_css_idiq3i1x2fsp53h97nw6su') })
    </script>

    <style>
    .table td.tinytable_css_id4yuxzwpgqges7ohu1sdz, .table th.tinytable_css_id4yuxzwpgqges7ohu1sdz {  text-align: left;  border-bottom: solid 0.1em #d3d8dc; }
    .table td.tinytable_css_id81xce0ext26ic75sljhk, .table th.tinytable_css_id81xce0ext26ic75sljhk {  text-align: center;  border-bottom: solid 0.1em #d3d8dc; }
    .table td.tinytable_css_idretnvgov3cra64izox1t, .table th.tinytable_css_idretnvgov3cra64izox1t {  text-align: left; }
    .table td.tinytable_css_idiq3i1x2fsp53h97nw6su, .table th.tinytable_css_idiq3i1x2fsp53h97nw6su {  text-align: center; }
    .table td.tinytable_css_idw8zqd28qqyk08pmasp39, .table th.tinytable_css_idw8zqd28qqyk08pmasp39 {  border-bottom: solid 0.05em black;  text-align: left; }
    .table td.tinytable_css_idvh9eg37o3mqq7t7vpnlc, .table th.tinytable_css_idvh9eg37o3mqq7t7vpnlc {  border-bottom: solid 0.05em black;  text-align: center; }
    </style>
    <div class="container">
      <table class="table table-borderless" id="tinytable_1rfi612szz2d43nokbnw" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        <thead>
        
              <tr>
                <th scope="col"> </th>
                <th scope="col">(1)</th>
                <th scope="col">(2)</th>
                <th scope="col">(3)</th>
              </tr>
        </thead>
        
        <tbody>
                <tr>
                  <td>(Intercept)</td>
                  <td>4.832  </td>
                  <td>3.829  </td>
                  <td>59.571 </td>
                </tr>
                <tr>
                  <td>           </td>
                  <td>(0.222)</td>
                  <td>(0.069)</td>
                  <td>(4.977)</td>
                </tr>
                <tr>
                  <td>log(hp)    </td>
                  <td>-0.266 </td>
                  <td>       </td>
                  <td>-5.922 </td>
                </tr>
                <tr>
                  <td>           </td>
                  <td>(0.056)</td>
                  <td>       </td>
                  <td>(1.266)</td>
                </tr>
                <tr>
                  <td>wt         </td>
                  <td>-0.179 </td>
                  <td>-0.201 </td>
                  <td>-3.286 </td>
                </tr>
                <tr>
                  <td>           </td>
                  <td>(0.027)</td>
                  <td>(0.027)</td>
                  <td>(0.615)</td>
                </tr>
                <tr>
                  <td>hp         </td>
                  <td>       </td>
                  <td>-0.002 </td>
                  <td>       </td>
                </tr>
                <tr>
                  <td>           </td>
                  <td>       </td>
                  <td>(0.000)</td>
                  <td>       </td>
                </tr>
                <tr>
                  <td>Num.Obs.   </td>
                  <td>32     </td>
                  <td>32     </td>
                  <td>32     </td>
                </tr>
                <tr>
                  <td>R2         </td>
                  <td>0.885  </td>
                  <td>0.869  </td>
                  <td>0.859  </td>
                </tr>
                <tr>
                  <td>R2 Adj.    </td>
                  <td>0.877  </td>
                  <td>0.860  </td>
                  <td>0.849  </td>
                </tr>
                <tr>
                  <td>AIC        </td>
                  <td>140.3  </td>
                  <td>144.5  </td>
                  <td>150.0  </td>
                </tr>
                <tr>
                  <td>BIC        </td>
                  <td>146.1  </td>
                  <td>150.4  </td>
                  <td>155.9  </td>
                </tr>
                <tr>
                  <td>Log.Lik.   </td>
                  <td>28.501 </td>
                  <td>26.395 </td>
                  <td>-71.017</td>
                </tr>
                <tr>
                  <td>F          </td>
                  <td>111.812</td>
                  <td>96.232 </td>
                  <td>88.442 </td>
                </tr>
                <tr>
                  <td>RMSE       </td>
                  <td>0.10   </td>
                  <td>0.11   </td>
                  <td>2.23   </td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
</div>
</div>
<ul>
<li><p>In the first model, we estimate that, on average, a 1% increase in horsepower decreases miles per gallon by 0.266% holding weight constant.</p></li>
<li><p>In the second model, we estimate that, on average, a 1 unit increase in horsepower decreases miles per gallon by 0.2% holding weight constant.</p></li>
<li><p>In the third model, we estimate that, on average, a 1% increase in horsepower decreases miles per gallon by .059 holding weight constant.</p></li>
</ul>
</section>
</section>
<section id="omitted-variable-bias" class="level2" data-number="9.9">
<h2 data-number="9.9" class="anchored" data-anchor-id="omitted-variable-bias"><span class="header-section-number">9.9</span> Omitted Variable Bias</h2>
<p>SW 6.1</p>
<p>Suppose that we are interested in the following regression model</p>
<p><span class="math display">\[
  \E[Y|X_1, X_2, Q] = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \beta_3 Q
\]</span> and, in particular, we are interested in the the partial effect</p>
<p><span class="math display">\[
  \frac{ \partial \, \E[Y|X_1,X_2,Q]}{\partial \, X_1} = \beta_1
\]</span> But we are faced with the issue that we do not observe <span class="math inline">\(Q\)</span> (which implies that we cannot control for it in the regression)</p>
<p>Recall that we can equivalently write</p>
<p><span id="eq-ovb-y"><span class="math display">\[
  Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \beta_3 Q + U
\tag{9.1}\]</span></span> where <span class="math inline">\(\E[U|X_1,X_2,Q]=0\)</span>.</p>
<p>Now, for simplicity, suppose that</p>
<p><span class="math display">\[
  \E[Q | X_1, X_2] = \gamma_0 + \gamma_1 X_1 + \gamma_2 X_2
\]</span></p>
<p>Now, let’s consider the idea of just running a regression of <span class="math inline">\(Y\)</span> on <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span> (and just not including <span class="math inline">\(Q\)</span>); in other words, consider the regression <span class="math display">\[
  \E[Y|X_1,X_2] = \delta_0 + \delta_1 X_1 + \delta_2 X_2
\]</span> We are interested in the question of whether or not we can recover <span class="math inline">\(\beta_1\)</span> if we do this. If we consider this “feasible” regression, notice if we plug in the expression for <span class="math inline">\(Y\)</span> from <a href="#eq-ovb-y" class="quarto-xref">Equation&nbsp;<span>9.1</span></a>,</p>
<p><span class="math display">\[
  \begin{aligned}
  \E[Y|X_1,X_2] &amp;= \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \beta_3 \E[Q|X_1,X_2] \\
  &amp;= \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \beta_3 (\gamma_0 + \gamma_1 X_1 + \gamma_2 X_2) \\
  &amp;= \underbrace{(\beta_0 + \beta_3 \gamma_0)}_{\delta_0} + \underbrace{(\beta_1 + \beta_3 \gamma_1)}_{\delta_1} X_1 + \underbrace{(\beta_2 + \beta_3 \gamma_2)}_{\delta_2} X_2
  \end{aligned}
\]</span></p>
<p>In other words, if we run the feasible regression of <span class="math inline">\(Y\)</span> on <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span>, <span class="math inline">\(\delta_1\)</span> (the coefficient on <span class="math inline">\(X_1\)</span>) is not equal to <span class="math inline">\(\beta_1\)</span>; rather, it is equal to <span class="math inline">\((\beta_1 + \beta_3 \gamma_1)\)</span>.</p>
<p>That you are not generally able to recover <span class="math inline">\(\beta_1\)</span> in this case is called <strong>omitted variable bias</strong></p>
<p>There are two cases where you will recover <span class="math inline">\(\delta_1 = \beta_1\)</span> though which occur when <span class="math inline">\(\beta_3 \gamma_1 = 0\)</span>:</p>
<ul>
<li><p><span class="math inline">\(\beta_3=0\)</span>. This would be the case where <span class="math inline">\(Q\)</span> has no effect on <span class="math inline">\(Y\)</span></p></li>
<li><p><span class="math inline">\(\gamma_1=0\)</span>. This would be the case where <span class="math inline">\(X_1\)</span> and <span class="math inline">\(Q\)</span> are uncorrelated after controlling for <span class="math inline">\(X_2\)</span>.</p></li>
</ul>
<p>Interestingly, there may be some case where you can “sign” the bias; i.e., figure out if <span class="math inline">\(\beta_3 \gamma_1\)</span> is positive or negative. For example, you might have theoretical reasons to suspect that <span class="math inline">\(\gamma_1 &gt; 0\)</span> and <span class="math inline">\(\beta_3 &gt; 0\)</span>. In this case,</p>
<p><span class="math display">\[
  \delta_1 = \beta_1 + \textrm{something positive}
\]</span> which implies that <span class="math inline">\(\delta_1\)</span> (i.e., running a regression that ignores <span class="math inline">\(Q\)</span>) would cause us to tend to over-estimate <span class="math inline">\(\beta_1\)</span>.</p>
<div class="side-comment">
<p><span class="side-comment">Side-Comment:</span></p>
<ul>
<li><p>The book talks about omitted variable bias in the context of causality (this is probably the leading case), but we have not talked about causality yet. The same issues arise if we just say that we have some <em>regression of interest</em> but are unable to estimate it because some covariates are unobserved.</p></li>
<li><p>The relationship to causality (which is not so important for now), is that under certain conditions, we may have a particular partial effect that we would be willing to interpret as being the “causal effect”, but if we are unable to control for some variables that would lead to this interpretation, then we get to the issues pointed out in the textbook.</p></li>
</ul>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./07-inference.html" class="pagination-link  aria-label=" &lt;span="">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Inference</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./09-regression_computation.html" class="pagination-link" aria-label="<span class='chapter-number'>10</span>&nbsp; <span class='chapter-title'>Computation</span>">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Computation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>